---
# Base system configuration

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - wireguard
      - prometheus-node-exporter
      - certbot
      - nginx
      - python3-pip
      - acl
      - jq
    state: present

- name: Configure system limits
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    mode: '0644'

- name: Configure sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: '0644'
  notify: reload sysctl

- name: Create frameworks user
  user:
    name: frameworks
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Create service directories
  file:
    path: "{{ item }}"
    state: directory
    owner: frameworks
    group: frameworks
    mode: '0755'
  loop:
    - /opt/frameworks
    - /var/log/frameworks
    - /etc/frameworks

- name: Install certificates from Terraform
  copy:
    content: "{{ item.certificate }}"
    dest: "/etc/ssl/certs/{{ item.name }}.pem"
    mode: '0644'
  loop: "{{ ssl_certificates }}"
  notify: reload nginx

- name: Install private keys
  copy:
    content: "{{ item.private_key }}"
    dest: "/etc/ssl/private/{{ item.name }}.key"
    mode: '0600'
  loop: "{{ ssl_certificates }}"
  notify: reload nginx

- name: Configure firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22   # SSH
    - 80   # HTTP
    - 443  # HTTPS
    - "{{ frameworks_ports }}"  # Service ports 