// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grpc_billing_details.sql

package purserdb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getTenantBillingDetails = `-- name: GetTenantBillingDetails :one
SELECT billing_email, billing_name, billing_company, tax_id,
       COALESCE(billing_address, '{}'::jsonb) AS billing_address,
       COALESCE(updated_at, TIMESTAMP 'epoch') AS updated_at,
       presentment_currency::text AS presentment_currency
FROM purser.tenant_subscriptions
WHERE tenant_id = $1::text::uuid AND status != 'cancelled'
ORDER BY created_at DESC
LIMIT 1
`

type GetTenantBillingDetailsRow struct {
	BillingEmail        sql.NullString  `db:"billing_email" json:"billing_email"`
	BillingName         sql.NullString  `db:"billing_name" json:"billing_name"`
	BillingCompany      sql.NullString  `db:"billing_company" json:"billing_company"`
	TaxID               sql.NullString  `db:"tax_id" json:"tax_id"`
	BillingAddress      json.RawMessage `db:"billing_address" json:"billing_address"`
	UpdatedAt           sql.NullTime    `db:"updated_at" json:"updated_at"`
	PresentmentCurrency string          `db:"presentment_currency" json:"presentment_currency"`
}

func (q *Queries) GetTenantBillingDetails(ctx context.Context, tenantID string) (GetTenantBillingDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantBillingDetails, tenantID)
	var i GetTenantBillingDetailsRow
	err := row.Scan(
		&i.BillingEmail,
		&i.BillingName,
		&i.BillingCompany,
		&i.TaxID,
		&i.BillingAddress,
		&i.UpdatedAt,
		&i.PresentmentCurrency,
	)
	return i, err
}

const lockTenantPresentmentCurrency = `-- name: LockTenantPresentmentCurrency :one
SELECT presentment_currency::text AS presentment_currency,
       purser.tenant_presentment_currency_locked(tenant_id)::boolean AS presentment_locked
FROM purser.tenant_subscriptions
WHERE tenant_id = $1::text::uuid AND status != 'cancelled'
FOR UPDATE
`

type LockTenantPresentmentCurrencyRow struct {
	PresentmentCurrency string `db:"presentment_currency" json:"presentment_currency"`
	PresentmentLocked   bool   `db:"presentment_locked" json:"presentment_locked"`
}

func (q *Queries) LockTenantPresentmentCurrency(ctx context.Context, tenantID string) (LockTenantPresentmentCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, lockTenantPresentmentCurrency, tenantID)
	var i LockTenantPresentmentCurrencyRow
	err := row.Scan(&i.PresentmentCurrency, &i.PresentmentLocked)
	return i, err
}

const setTenantPresentmentCurrency = `-- name: SetTenantPresentmentCurrency :execrows
UPDATE purser.tenant_subscriptions
SET presentment_currency = $1::text,
    updated_at = NOW()
WHERE tenant_id = $2::text::uuid
  AND status != 'cancelled'
  AND presentment_currency <> $1::text
`

type SetTenantPresentmentCurrencyParams struct {
	PresentmentCurrency string `db:"presentment_currency" json:"presentment_currency"`
	TenantID            string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) SetTenantPresentmentCurrency(ctx context.Context, arg SetTenantPresentmentCurrencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTenantPresentmentCurrency, arg.PresentmentCurrency, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTenantBillingDetails = `-- name: UpdateTenantBillingDetails :execrows
UPDATE purser.tenant_subscriptions
SET billing_email = CASE WHEN $1::boolean THEN $2::text ELSE billing_email END,
    billing_name = CASE WHEN $3::boolean THEN $4::text ELSE billing_name END,
    billing_company = CASE WHEN $5::boolean THEN $6::text ELSE billing_company END,
    tax_id = CASE WHEN $7::boolean THEN $8::text ELSE tax_id END,
    billing_address = CASE WHEN $9::boolean THEN $10::jsonb ELSE billing_address END,
    updated_at = NOW()
WHERE tenant_id = $11::text::uuid AND status != 'cancelled'
`

type UpdateTenantBillingDetailsParams struct {
	SetEmail     bool            `db:"set_email" json:"set_email"`
	Email        string          `db:"email" json:"email"`
	SetName      bool            `db:"set_name" json:"set_name"`
	Name         string          `db:"name" json:"name"`
	SetCompany   bool            `db:"set_company" json:"set_company"`
	Company      string          `db:"company" json:"company"`
	SetVatNumber bool            `db:"set_vat_number" json:"set_vat_number"`
	VatNumber    string          `db:"vat_number" json:"vat_number"`
	SetAddress   bool            `db:"set_address" json:"set_address"`
	Address      json.RawMessage `db:"address" json:"address"`
	TenantID     string          `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateTenantBillingDetails(ctx context.Context, arg UpdateTenantBillingDetailsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTenantBillingDetails,
		arg.SetEmail,
		arg.Email,
		arg.SetName,
		arg.Name,
		arg.SetCompany,
		arg.Company,
		arg.SetVatNumber,
		arg.VatNumber,
		arg.SetAddress,
		arg.Address,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
