// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_revenue.sql

package purserdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getOperatorRevenue = `-- name: GetOperatorRevenue :many
SELECT cluster_id, currency,
       SUM(gross_cents)::bigint AS gross_cents,
       SUM(platform_fee_cents)::bigint AS platform_fee_cents,
       SUM(payable_cents)::bigint AS payable_cents,
       COUNT(*) FILTER (WHERE entry_type = 'accrual')::integer AS line_count
FROM purser.operator_credit_ledger
WHERE cluster_owner_tenant_id = $1::text::uuid
  AND period_start < $2
  AND period_end > $3
  AND status IN ('accruing', 'eligible', 'paid_out', 'clawed_back')
  AND (NOT $4::boolean OR cluster_id = $5)
GROUP BY cluster_id, currency
ORDER BY cluster_id, currency
`

type GetOperatorRevenueParams struct {
	TenantID      string    `db:"tenant_id" json:"tenant_id"`
	RangeEnd      time.Time `db:"range_end" json:"range_end"`
	RangeStart    time.Time `db:"range_start" json:"range_start"`
	FilterCluster bool      `db:"filter_cluster" json:"filter_cluster"`
	ClusterID     string    `db:"cluster_id" json:"cluster_id"`
}

type GetOperatorRevenueRow struct {
	ClusterID        string `db:"cluster_id" json:"cluster_id"`
	Currency         string `db:"currency" json:"currency"`
	GrossCents       int64  `db:"gross_cents" json:"gross_cents"`
	PlatformFeeCents int64  `db:"platform_fee_cents" json:"platform_fee_cents"`
	PayableCents     int64  `db:"payable_cents" json:"payable_cents"`
	LineCount        int32  `db:"line_count" json:"line_count"`
}

func (q *Queries) GetOperatorRevenue(ctx context.Context, arg GetOperatorRevenueParams) ([]GetOperatorRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, getOperatorRevenue,
		arg.TenantID,
		arg.RangeEnd,
		arg.RangeStart,
		arg.FilterCluster,
		arg.ClusterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOperatorRevenueRow{}
	for rows.Next() {
		var i GetOperatorRevenueRow
		if err := rows.Scan(
			&i.ClusterID,
			&i.Currency,
			&i.GrossCents,
			&i.PlatformFeeCents,
			&i.PayableCents,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorClusters = `-- name: ListOperatorClusters :many
SELECT cluster_id, currency,
       SUM(gross_cents)::bigint AS gross_cents,
       SUM(platform_fee_cents)::bigint AS platform_fee_cents,
       SUM(payable_cents)::bigint AS payable_cents,
       COUNT(*) FILTER (WHERE entry_type = 'accrual')::integer AS line_count
FROM purser.operator_credit_ledger
WHERE cluster_owner_tenant_id = $1::text::uuid
  AND status IN ('accruing', 'eligible', 'paid_out', 'clawed_back')
GROUP BY cluster_id, currency
ORDER BY cluster_id, currency
`

type ListOperatorClustersRow struct {
	ClusterID        string `db:"cluster_id" json:"cluster_id"`
	Currency         string `db:"currency" json:"currency"`
	GrossCents       int64  `db:"gross_cents" json:"gross_cents"`
	PlatformFeeCents int64  `db:"platform_fee_cents" json:"platform_fee_cents"`
	PayableCents     int64  `db:"payable_cents" json:"payable_cents"`
	LineCount        int32  `db:"line_count" json:"line_count"`
}

func (q *Queries) ListOperatorClusters(ctx context.Context, tenantID string) ([]ListOperatorClustersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorClusters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorClustersRow{}
	for rows.Next() {
		var i ListOperatorClustersRow
		if err := rows.Scan(
			&i.ClusterID,
			&i.Currency,
			&i.GrossCents,
			&i.PlatformFeeCents,
			&i.PayableCents,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperatorPayouts = `-- name: ListOperatorPayouts :many
SELECT id, currency, total_cents, status,
       COALESCE(method, '')::text AS method,
       COALESCE(external_reference, '')::text AS external_reference,
       created_at, paid_at
FROM purser.operator_payouts
WHERE cluster_owner_tenant_id = $1::text::uuid
  AND (NOT $2::boolean OR created_at >= $3)
  AND (NOT $4::boolean OR created_at < $5)
ORDER BY created_at DESC, id DESC
`

type ListOperatorPayoutsParams struct {
	TenantID    string    `db:"tenant_id" json:"tenant_id"`
	FilterStart bool      `db:"filter_start" json:"filter_start"`
	RangeStart  time.Time `db:"range_start" json:"range_start"`
	FilterEnd   bool      `db:"filter_end" json:"filter_end"`
	RangeEnd    time.Time `db:"range_end" json:"range_end"`
}

type ListOperatorPayoutsRow struct {
	ID                uuid.UUID    `db:"id" json:"id"`
	Currency          string       `db:"currency" json:"currency"`
	TotalCents        int64        `db:"total_cents" json:"total_cents"`
	Status            string       `db:"status" json:"status"`
	Method            string       `db:"method" json:"method"`
	ExternalReference string       `db:"external_reference" json:"external_reference"`
	CreatedAt         time.Time    `db:"created_at" json:"created_at"`
	PaidAt            sql.NullTime `db:"paid_at" json:"paid_at"`
}

func (q *Queries) ListOperatorPayouts(ctx context.Context, arg ListOperatorPayoutsParams) ([]ListOperatorPayoutsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperatorPayouts,
		arg.TenantID,
		arg.FilterStart,
		arg.RangeStart,
		arg.FilterEnd,
		arg.RangeEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorPayoutsRow{}
	for rows.Next() {
		var i ListOperatorPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.TotalCents,
			&i.Status,
			&i.Method,
			&i.ExternalReference,
			&i.CreatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
