// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prepaid_statements.sql

package purserdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const collectPostpaidInvoiceDimensionedUsage = `-- name: CollectPostpaidInvoiceDimensionedUsage :many
WITH params AS (
    SELECT $1::text::uuid AS tenant_id,
           $2::timestamptz AS window_start,
           $3::timestamptz AS window_end,
           LEAST($4::timestamptz, $2::timestamptz) AS unsettled_from
), dimensioned_rows AS (
    SELECT ur.cluster_id, ur.usage_type, ur.unit, ur.dimensions, ur.usage_value
    FROM purser.usage_records ur CROSS JOIN params p
    WHERE ur.tenant_id = p.tenant_id
      AND ur.period_start < p.window_end
      AND ur.period_end > p.unsettled_from
      AND (ur.period_end > p.window_start OR ur.created_at >= p.window_start)
      AND ur.value_kind = 'delta' AND ur.granularity = 'minute_5'
      AND NOT EXISTS (
          SELECT 1 FROM purser.prepaid_usage_settlements settlement
          WHERE settlement.report_id = ur.report_id AND settlement.tenant_id = ur.tenant_id
      )
    UNION ALL
    SELECT ua.cluster_id, ua.usage_type, ua.unit, ua.dimensions, ua.delta_value
    FROM purser.usage_adjustments ua CROSS JOIN params p
    WHERE ua.tenant_id = p.tenant_id
      AND ua.period_start < p.window_end
      AND ua.period_end > p.window_start
      AND ua.status = 'applied' AND ua.value_kind = 'correction_delta'
)
SELECT COALESCE(r.cluster_id, '') AS cluster_id,
       r.usage_type, r.unit, r.dimensions,
       (CASE WHEN d.aggregation = 'max' THEN MAX(r.usage_value)
             ELSE SUM(r.usage_value) END)::float8 AS quantity
FROM dimensioned_rows r
JOIN purser.meter_definitions d ON d.meter = r.usage_type AND d.active = TRUE
GROUP BY r.cluster_id, r.usage_type, r.unit, r.dimensions, d.aggregation
`

type CollectPostpaidInvoiceDimensionedUsageParams struct {
	TenantID      string    `db:"tenant_id" json:"tenant_id"`
	WindowStart   time.Time `db:"window_start" json:"window_start"`
	WindowEnd     time.Time `db:"window_end" json:"window_end"`
	UnsettledFrom time.Time `db:"unsettled_from" json:"unsettled_from"`
}

type CollectPostpaidInvoiceDimensionedUsageRow struct {
	ClusterID  string          `db:"cluster_id" json:"cluster_id"`
	UsageType  string          `db:"usage_type" json:"usage_type"`
	Unit       string          `db:"unit" json:"unit"`
	Dimensions json.RawMessage `db:"dimensions" json:"dimensions"`
	Quantity   float64         `db:"quantity" json:"quantity"`
}

// CollectPostpaidInvoiceUsage per meter dimension.
func (q *Queries) CollectPostpaidInvoiceDimensionedUsage(ctx context.Context, arg CollectPostpaidInvoiceDimensionedUsageParams) ([]CollectPostpaidInvoiceDimensionedUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, collectPostpaidInvoiceDimensionedUsage,
		arg.TenantID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.UnsettledFrom,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectPostpaidInvoiceDimensionedUsageRow{}
	for rows.Next() {
		var i CollectPostpaidInvoiceDimensionedUsageRow
		if err := rows.Scan(
			&i.ClusterID,
			&i.UsageType,
			&i.Unit,
			&i.Dimensions,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectPostpaidInvoiceUsage = `-- name: CollectPostpaidInvoiceUsage :many
WITH params AS (
    SELECT $1::text::uuid AS tenant_id,
           $2::timestamptz AS window_start,
           $3::timestamptz AS window_end,
           LEAST($4::timestamptz, $2::timestamptz) AS unsettled_from
), usage_rows AS (
    SELECT COALESCE(ur.cluster_id, '') AS cluster_id, ur.usage_type, ur.usage_value
    FROM purser.usage_records ur CROSS JOIN params p
    WHERE ur.tenant_id = p.tenant_id
      AND ur.period_start < p.window_end
      AND ur.period_end > p.unsettled_from
      AND (ur.period_end > p.window_start OR ur.created_at >= p.window_start)
      AND ur.usage_type NOT IN ('unique_users', 'total_streams', 'total_viewers', 'unique_users_period')
      AND ur.value_kind = 'delta'
      AND ur.granularity = 'minute_5'
      AND NOT EXISTS (
          SELECT 1 FROM purser.prepaid_usage_settlements settlement
          WHERE settlement.report_id = ur.report_id AND settlement.tenant_id = ur.tenant_id
      )
    UNION ALL
    SELECT COALESCE(ua.cluster_id, '') AS cluster_id, ua.usage_type, ua.delta_value AS usage_value
    FROM purser.usage_adjustments ua CROSS JOIN params p
    WHERE ua.tenant_id = p.tenant_id
      AND ua.period_start < p.window_end
      AND ua.period_end > p.window_start
      AND ua.status = 'applied'
      AND ua.value_kind = 'correction_delta'
      AND ua.usage_type NOT IN ('unique_users', 'total_streams', 'total_viewers', 'unique_users_period')
)
SELECT cluster_id, usage_type,
       (CASE WHEN usage_type IN ('peak_bandwidth_mbps', 'max_viewers')
             THEN MAX(usage_value) ELSE SUM(usage_value) END)::float8 AS aggregated_value
FROM usage_rows
GROUP BY cluster_id, usage_type
`

type CollectPostpaidInvoiceUsageParams struct {
	TenantID      string    `db:"tenant_id" json:"tenant_id"`
	WindowStart   time.Time `db:"window_start" json:"window_start"`
	WindowEnd     time.Time `db:"window_end" json:"window_end"`
	UnsettledFrom time.Time `db:"unsettled_from" json:"unsettled_from"`
}

type CollectPostpaidInvoiceUsageRow struct {
	ClusterID       string  `db:"cluster_id" json:"cluster_id"`
	UsageType       string  `db:"usage_type" json:"usage_type"`
	AggregatedValue float64 `db:"aggregated_value" json:"aggregated_value"`
}

// The usage a postpaid invoice of [window_start, window_end) rates. A usage
// record a prepaid usage settlement paid from the balance belongs to the
// prepaid statement, never to an invoice. A period that starts at a switch
// from prepaid also rates the records of the prepaid phase before it that
// reached Purser after the switch, which the balance never paid:
// unsettled_from is where that phase began, or window_start otherwise.
func (q *Queries) CollectPostpaidInvoiceUsage(ctx context.Context, arg CollectPostpaidInvoiceUsageParams) ([]CollectPostpaidInvoiceUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, collectPostpaidInvoiceUsage,
		arg.TenantID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.UnsettledFrom,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectPostpaidInvoiceUsageRow{}
	for rows.Next() {
		var i CollectPostpaidInvoiceUsageRow
		if err := rows.Scan(&i.ClusterID, &i.UsageType, &i.AggregatedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const convertDraftToPrepaidStatement = `-- name: ConvertDraftToPrepaidStatement :one
UPDATE purser.billing_invoices
SET invoice_number = 'STM-' || LPAD(nextval('purser.billing_invoice_number_seq')::text, 10, '0'),
    document_kind = 'prepaid_statement',
    status = 'paid',
    currency = 'EUR',
    amount = 0,
    due_date = $1::timestamptz,
    paid_at = $1::timestamptz,
    base_amount = $2::text::numeric,
    metered_amount = $3::text::numeric,
    gross_metered_amount = $4::text::numeric,
    prepaid_credit_applied = 0,
    usage_details = $5::jsonb,
    period_end = $6::timestamptz,
    presentment_amount_cents = 0,
    presentment_currency = 'EUR',
    presentment_units_per_eur = 1,
    presentment_reference_date = $1::date,
    finalized_at = $1::timestamptz,
    updated_at = NOW()
WHERE id = $7::text::uuid
  AND tenant_id = $8::text::uuid
  AND status IN ('draft', 'manual_review')
RETURNING id::text AS id, invoice_number
`

type ConvertDraftToPrepaidStatementParams struct {
	FinalizedAt        time.Time       `db:"finalized_at" json:"finalized_at"`
	BaseAmount         string          `db:"base_amount" json:"base_amount"`
	MeteredAmount      string          `db:"metered_amount" json:"metered_amount"`
	GrossMeteredAmount string          `db:"gross_metered_amount" json:"gross_metered_amount"`
	UsageDetails       json.RawMessage `db:"usage_details" json:"usage_details"`
	PeriodEnd          time.Time       `db:"period_end" json:"period_end"`
	InvoiceID          string          `db:"invoice_id" json:"invoice_id"`
	TenantID           string          `db:"tenant_id" json:"tenant_id"`
}

type ConvertDraftToPrepaidStatementRow struct {
	ID            string `db:"id" json:"id"`
	InvoiceNumber string `db:"invoice_number" json:"invoice_number"`
}

// An open draft of the period, left by postpaid billing earlier in the period,
// becomes the period's statement.
func (q *Queries) ConvertDraftToPrepaidStatement(ctx context.Context, arg ConvertDraftToPrepaidStatementParams) (ConvertDraftToPrepaidStatementRow, error) {
	row := q.db.QueryRowContext(ctx, convertDraftToPrepaidStatement,
		arg.FinalizedAt,
		arg.BaseAmount,
		arg.MeteredAmount,
		arg.GrossMeteredAmount,
		arg.UsageDetails,
		arg.PeriodEnd,
		arg.InvoiceID,
		arg.TenantID,
	)
	var i ConvertDraftToPrepaidStatementRow
	err := row.Scan(&i.ID, &i.InvoiceNumber)
	return i, err
}

const enqueuePrepaidStatementEmail = `-- name: EnqueuePrepaidStatementEmail :exec
INSERT INTO purser.invoice_email_outbox
    (invoice_id, tenant_id, recipient, notification_type, reminder_stage)
VALUES (
    $1::text::uuid,
    $2::text::uuid,
    $3,
    'prepaid_statement',
    0
)
ON CONFLICT (invoice_id, notification_type, reminder_stage) DO NOTHING
`

type EnqueuePrepaidStatementEmailParams struct {
	InvoiceID string `db:"invoice_id" json:"invoice_id"`
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	Recipient string `db:"recipient" json:"recipient"`
}

func (q *Queries) EnqueuePrepaidStatementEmail(ctx context.Context, arg EnqueuePrepaidStatementEmailParams) error {
	_, err := q.db.ExecContext(ctx, enqueuePrepaidStatementEmail, arg.InvoiceID, arg.TenantID, arg.Recipient)
	return err
}

const getClosedPrepaidPhaseStart = `-- name: GetClosedPrepaidPhaseStart :one
SELECT period_start::timestamptz AS phase_start
FROM purser.billing_invoices
WHERE tenant_id = $1::text::uuid
  AND document_kind = 'prepaid_statement'
  AND period_end = $2::timestamptz
  AND period_start < $2::timestamptz
  AND usage_details->'statement'->>'closes_prepaid_phase' = 'true'
ORDER BY period_start
LIMIT 1
`

type GetClosedPrepaidPhaseStartParams struct {
	TenantID    string    `db:"tenant_id" json:"tenant_id"`
	PeriodStart time.Time `db:"period_start" json:"period_start"`
}

// Where the prepaid phase began that a switch to postpaid closed at
// period_start, from the statement that closed it.
func (q *Queries) GetClosedPrepaidPhaseStart(ctx context.Context, arg GetClosedPrepaidPhaseStartParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getClosedPrepaidPhaseStart, arg.TenantID, arg.PeriodStart)
	var phase_start time.Time
	err := row.Scan(&phase_start)
	return phase_start, err
}

const getPrepaidStatement = `-- name: GetPrepaidStatement :one
SELECT invoice_number, status, period_start, period_end,
       metered_amount::float8 AS metered_amount,
       usage_details
FROM purser.billing_invoices
WHERE id = $1::text::uuid
  AND tenant_id = $2::text::uuid
  AND document_kind = 'prepaid_statement'
`

type GetPrepaidStatementParams struct {
	InvoiceID string `db:"invoice_id" json:"invoice_id"`
	TenantID  string `db:"tenant_id" json:"tenant_id"`
}

type GetPrepaidStatementRow struct {
	InvoiceNumber string          `db:"invoice_number" json:"invoice_number"`
	Status        string          `db:"status" json:"status"`
	PeriodStart   sql.NullTime    `db:"period_start" json:"period_start"`
	PeriodEnd     sql.NullTime    `db:"period_end" json:"period_end"`
	MeteredAmount float64         `db:"metered_amount" json:"metered_amount"`
	UsageDetails  json.RawMessage `db:"usage_details" json:"usage_details"`
}

func (q *Queries) GetPrepaidStatement(ctx context.Context, arg GetPrepaidStatementParams) (GetPrepaidStatementRow, error) {
	row := q.db.QueryRowContext(ctx, getPrepaidStatement, arg.InvoiceID, arg.TenantID)
	var i GetPrepaidStatementRow
	err := row.Scan(
		&i.InvoiceNumber,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.MeteredAmount,
		&i.UsageDetails,
	)
	return i, err
}

const getPrepaidStatementDocument = `-- name: GetPrepaidStatementDocument :one
SELECT invoice.invoice_number, invoice.status,
       COALESCE(invoice.created_at, NOW()) AS issued_at, invoice.retention_until,
       invoice.period_start, invoice.period_end,
       invoice.usage_details,
       COALESCE(subscription.billing_name, '')::text AS customer_name,
       COALESCE(subscription.billing_company, '')::text AS customer_company,
       COALESCE(subscription.billing_address::text, '')::text AS customer_address,
       COALESCE(subscription.tax_id, '')::text AS customer_vat
FROM purser.billing_invoices invoice
LEFT JOIN purser.tenant_subscriptions subscription ON subscription.tenant_id = invoice.tenant_id
WHERE invoice.id = $1::text::uuid
  AND invoice.tenant_id = $2::text::uuid
  AND invoice.document_kind = 'prepaid_statement'
`

type GetPrepaidStatementDocumentParams struct {
	DocumentID string `db:"document_id" json:"document_id"`
	TenantID   string `db:"tenant_id" json:"tenant_id"`
}

type GetPrepaidStatementDocumentRow struct {
	InvoiceNumber   string          `db:"invoice_number" json:"invoice_number"`
	Status          string          `db:"status" json:"status"`
	IssuedAt        sql.NullTime    `db:"issued_at" json:"issued_at"`
	RetentionUntil  time.Time       `db:"retention_until" json:"retention_until"`
	PeriodStart     sql.NullTime    `db:"period_start" json:"period_start"`
	PeriodEnd       sql.NullTime    `db:"period_end" json:"period_end"`
	UsageDetails    json.RawMessage `db:"usage_details" json:"usage_details"`
	CustomerName    string          `db:"customer_name" json:"customer_name"`
	CustomerCompany string          `db:"customer_company" json:"customer_company"`
	CustomerAddress string          `db:"customer_address" json:"customer_address"`
	CustomerVat     string          `db:"customer_vat" json:"customer_vat"`
}

func (q *Queries) GetPrepaidStatementDocument(ctx context.Context, arg GetPrepaidStatementDocumentParams) (GetPrepaidStatementDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getPrepaidStatementDocument, arg.DocumentID, arg.TenantID)
	var i GetPrepaidStatementDocumentRow
	err := row.Scan(
		&i.InvoiceNumber,
		&i.Status,
		&i.IssuedAt,
		&i.RetentionUntil,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.UsageDetails,
		&i.CustomerName,
		&i.CustomerCompany,
		&i.CustomerAddress,
		&i.CustomerVat,
	)
	return i, err
}

const getPrepaidStatementLedger = `-- name: GetPrepaidStatementLedger :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint AS since_period_start_cents,
       COALESCE(SUM(amount_cents) FILTER (WHERE created_at >= $1::timestamptz), 0)::bigint AS since_period_end_cents,
       COALESCE(SUM(amount_cents) FILTER (
           WHERE created_at < $1::timestamptz AND transaction_type = 'topup'
       ), 0)::bigint AS topup_cents,
       COUNT(*) FILTER (
           WHERE created_at < $1::timestamptz AND transaction_type = 'topup'
       )::bigint AS topups,
       COALESCE(SUM(amount_cents) FILTER (
           WHERE created_at < $1::timestamptz AND reference_type = 'usage_summary'
       ), 0)::bigint AS usage_cents
FROM purser.balance_transactions
WHERE tenant_id = $2::text::uuid
  AND created_at >= $3::timestamptz
`

type GetPrepaidStatementLedgerParams struct {
	PeriodEnd   time.Time `db:"period_end" json:"period_end"`
	TenantID    string    `db:"tenant_id" json:"tenant_id"`
	PeriodStart time.Time `db:"period_start" json:"period_start"`
}

type GetPrepaidStatementLedgerRow struct {
	SincePeriodStartCents int64 `db:"since_period_start_cents" json:"since_period_start_cents"`
	SincePeriodEndCents   int64 `db:"since_period_end_cents" json:"since_period_end_cents"`
	TopupCents            int64 `db:"topup_cents" json:"topup_cents"`
	Topups                int64 `db:"topups" json:"topups"`
	UsageCents            int64 `db:"usage_cents" json:"usage_cents"`
}

// Balance movements a statement states, read under the prepaid balance lock:
// everything posted since the period start and since its end, and the
// top-ups and usage deductions posted inside the period.
func (q *Queries) GetPrepaidStatementLedger(ctx context.Context, arg GetPrepaidStatementLedgerParams) (GetPrepaidStatementLedgerRow, error) {
	row := q.db.QueryRowContext(ctx, getPrepaidStatementLedger, arg.PeriodEnd, arg.TenantID, arg.PeriodStart)
	var i GetPrepaidStatementLedgerRow
	err := row.Scan(
		&i.SincePeriodStartCents,
		&i.SincePeriodEndCents,
		&i.TopupCents,
		&i.Topups,
		&i.UsageCents,
	)
	return i, err
}

const getSubscriptionPrepaidPhase = `-- name: GetSubscriptionPrepaidPhase :one
SELECT billing_model, status, billing_email,
       billing_period_start, billing_period_end,
       stripe_subscription_id, mollie_subscription_id,
       NOW()::timestamptz AS database_now
FROM purser.tenant_subscriptions
WHERE tenant_id = $1::text::uuid
`

type GetSubscriptionPrepaidPhaseRow struct {
	BillingModel         string         `db:"billing_model" json:"billing_model"`
	Status               string         `db:"status" json:"status"`
	BillingEmail         sql.NullString `db:"billing_email" json:"billing_email"`
	BillingPeriodStart   sql.NullTime   `db:"billing_period_start" json:"billing_period_start"`
	BillingPeriodEnd     sql.NullTime   `db:"billing_period_end" json:"billing_period_end"`
	StripeSubscriptionID sql.NullString `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	MollieSubscriptionID sql.NullString `db:"mollie_subscription_id" json:"mollie_subscription_id"`
	DatabaseNow          time.Time      `db:"database_now" json:"database_now"`
}

// The subscription facts that decide a prepaid phase and its statement, and
// the database clock that usage record receipt times are written with.
func (q *Queries) GetSubscriptionPrepaidPhase(ctx context.Context, tenantID string) (GetSubscriptionPrepaidPhaseRow, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionPrepaidPhase, tenantID)
	var i GetSubscriptionPrepaidPhaseRow
	err := row.Scan(
		&i.BillingModel,
		&i.Status,
		&i.BillingEmail,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.StripeSubscriptionID,
		&i.MollieSubscriptionID,
		&i.DatabaseNow,
	)
	return i, err
}

const insertPrepaidStatement = `-- name: InsertPrepaidStatement :one
INSERT INTO purser.billing_invoices (
    tenant_id, invoice_number, document_kind, status, currency, amount, due_date, paid_at,
    base_amount, metered_amount, gross_metered_amount, prepaid_credit_applied,
    usage_details, period_start, period_end,
    presentment_amount_cents, presentment_currency, presentment_units_per_eur,
    presentment_reference_date, finalized_at, created_at, updated_at
) VALUES (
    $1::text::uuid,
    'STM-' || LPAD(nextval('purser.billing_invoice_number_seq')::text, 10, '0'),
    'prepaid_statement', 'paid', 'EUR', 0,
    $2::timestamptz, $2::timestamptz,
    $3::text::numeric, $4::text::numeric,
    $5::text::numeric, 0,
    $6::jsonb, $7::timestamptz, $8::timestamptz,
    0, 'EUR', 1, $2::date, $2::timestamptz, NOW(), NOW()
)
ON CONFLICT (tenant_id, period_start) WHERE period_start IS NOT NULL
DO NOTHING
RETURNING id::text AS id, invoice_number
`

type InsertPrepaidStatementParams struct {
	TenantID           string          `db:"tenant_id" json:"tenant_id"`
	FinalizedAt        time.Time       `db:"finalized_at" json:"finalized_at"`
	BaseAmount         string          `db:"base_amount" json:"base_amount"`
	MeteredAmount      string          `db:"metered_amount" json:"metered_amount"`
	GrossMeteredAmount string          `db:"gross_metered_amount" json:"gross_metered_amount"`
	UsageDetails       json.RawMessage `db:"usage_details" json:"usage_details"`
	PeriodStart        time.Time       `db:"period_start" json:"period_start"`
	PeriodEnd          time.Time       `db:"period_end" json:"period_end"`
}

type InsertPrepaidStatementRow struct {
	ID            string `db:"id" json:"id"`
	InvoiceNumber string `db:"invoice_number" json:"invoice_number"`
}

// A statement is finalized when it is written: nothing is due, so it is paid.
// It is stated in EUR, the currency of the prepaid balance.
func (q *Queries) InsertPrepaidStatement(ctx context.Context, arg InsertPrepaidStatementParams) (InsertPrepaidStatementRow, error) {
	row := q.db.QueryRowContext(ctx, insertPrepaidStatement,
		arg.TenantID,
		arg.FinalizedAt,
		arg.BaseAmount,
		arg.MeteredAmount,
		arg.GrossMeteredAmount,
		arg.UsageDetails,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i InsertPrepaidStatementRow
	err := row.Scan(&i.ID, &i.InvoiceNumber)
	return i, err
}

const insertPrepaidStatementFeeTransaction = `-- name: InsertPrepaidStatementFeeTransaction :exec
INSERT INTO purser.balance_transactions (
    tenant_id, amount_cents, balance_after_cents, transaction_type, description,
    reference_id, reference_type, actor_kind, created_at
) VALUES (
    $1::text::uuid, $2, $3,
    'usage', $4, $5::text::uuid, 'prepaid_statement_fees',
    'system', NOW()
)
`

type InsertPrepaidStatementFeeTransactionParams struct {
	TenantID          string         `db:"tenant_id" json:"tenant_id"`
	AmountCents       int64          `db:"amount_cents" json:"amount_cents"`
	BalanceAfterCents int64          `db:"balance_after_cents" json:"balance_after_cents"`
	Description       sql.NullString `db:"description" json:"description"`
	StatementID       string         `db:"statement_id" json:"statement_id"`
}

// The period's monthly fees a prepaid statement charged to the balance; the
// statement is the reference, so the charge is written once.
func (q *Queries) InsertPrepaidStatementFeeTransaction(ctx context.Context, arg InsertPrepaidStatementFeeTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertPrepaidStatementFeeTransaction,
		arg.TenantID,
		arg.AmountCents,
		arg.BalanceAfterCents,
		arg.Description,
		arg.StatementID,
	)
	return err
}

const listPrepaidDoubleCharges = `-- name: ListPrepaidDoubleCharges :many
SELECT invoice.id::text AS invoice_id,
       invoice.tenant_id::text AS tenant_id,
       invoice.invoice_number,
       invoice.status,
       invoice.period_start::timestamptz AS period_start,
       invoice.period_end::timestamptz AS period_end,
       invoice.amount::text AS amount,
       invoice.prepaid_credit_applied::text AS prepaid_credit_applied,
       COALESCE(invoice.presentment_currency, invoice.currency)::text AS presentment_currency,
       COALESCE(invoice.presentment_amount_cents, ROUND(invoice.amount * 100)::bigint)::bigint AS presentment_amount_cents,
       settled.amount_micro::bigint AS settled_micro,
       COALESCE(lines.usage_amount, 0)::text AS usage_amount
FROM purser.billing_invoices invoice
JOIN LATERAL (
    SELECT SUM(settlement.amount_micro) AS amount_micro
    FROM purser.prepaid_usage_settlements settlement
    WHERE settlement.tenant_id = invoice.tenant_id
      AND settlement.billing_period_start >= invoice.period_start
      AND settlement.billing_period_start < invoice.period_end
) settled ON settled.amount_micro IS NOT NULL
LEFT JOIN LATERAL (
    SELECT SUM(line.amount) AS usage_amount
    FROM purser.invoice_line_items line
    WHERE line.invoice_id = invoice.id
      AND line.line_key <> 'base_subscription'
      AND line.pricing_source <> 'cluster_monthly'
) lines ON TRUE
WHERE invoice.document_kind = 'invoice'
  AND invoice.period_start IS NOT NULL
  AND invoice.period_end IS NOT NULL
  AND invoice.base_fee_period_start IS NULL
  AND invoice.status NOT IN ('draft', 'manual_review', 'cancelled')
  AND invoice.usage_details->>'prepaid_settled_usage_excluded' IS NULL
  AND (NOT $1::boolean OR invoice.tenant_id = $2::text::uuid)
ORDER BY invoice.period_start, invoice.tenant_id, invoice.id
LIMIT $3::integer
`

type ListPrepaidDoubleChargesParams struct {
	FilterTenant bool   `db:"filter_tenant" json:"filter_tenant"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
	ResultLimit  int32  `db:"result_limit" json:"result_limit"`
}

type ListPrepaidDoubleChargesRow struct {
	InvoiceID              string    `db:"invoice_id" json:"invoice_id"`
	TenantID               string    `db:"tenant_id" json:"tenant_id"`
	InvoiceNumber          string    `db:"invoice_number" json:"invoice_number"`
	Status                 string    `db:"status" json:"status"`
	PeriodStart            time.Time `db:"period_start" json:"period_start"`
	PeriodEnd              time.Time `db:"period_end" json:"period_end"`
	Amount                 string    `db:"amount" json:"amount"`
	PrepaidCreditApplied   string    `db:"prepaid_credit_applied" json:"prepaid_credit_applied"`
	PresentmentCurrency    string    `db:"presentment_currency" json:"presentment_currency"`
	PresentmentAmountCents int64     `db:"presentment_amount_cents" json:"presentment_amount_cents"`
	SettledMicro           int64     `db:"settled_micro" json:"settled_micro"`
	UsageAmount            string    `db:"usage_amount" json:"usage_amount"`
}

// Finalized usage invoices whose period holds prepaid usage settlements: the
// tenant was prepaid during the period, and usage its prepaid balance had
// already paid was rated again on the invoice. Invoices that leave
// prepaid-settled usage out record prepaid_settled_usage_excluded and are not
// listed. usage_amount is the invoice's usage lines without base and monthly
// cluster fees.
func (q *Queries) ListPrepaidDoubleCharges(ctx context.Context, arg ListPrepaidDoubleChargesParams) ([]ListPrepaidDoubleChargesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrepaidDoubleCharges, arg.FilterTenant, arg.TenantID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrepaidDoubleChargesRow{}
	for rows.Next() {
		var i ListPrepaidDoubleChargesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.TenantID,
			&i.InvoiceNumber,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Amount,
			&i.PrepaidCreditApplied,
			&i.PresentmentCurrency,
			&i.PresentmentAmountCents,
			&i.SettledMicro,
			&i.UsageAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startPostpaidPhase = `-- name: StartPostpaidPhase :execrows
UPDATE purser.tenant_subscriptions
SET billing_period_start = $1::timestamp,
    billing_period_end = $2::timestamp,
    next_billing_date = $2::timestamp,
    updated_at = NOW()
WHERE tenant_id = $3::text::uuid
`

type StartPostpaidPhaseParams struct {
	PeriodStart time.Time `db:"period_start" json:"period_start"`
	PeriodEnd   time.Time `db:"period_end" json:"period_end"`
	TenantID    string    `db:"tenant_id" json:"tenant_id"`
}

// A switch from prepaid to postpaid closed the prepaid phase at
// period_start: the postpaid period runs from there.
func (q *Queries) StartPostpaidPhase(ctx context.Context, arg StartPostpaidPhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startPostpaidPhase, arg.PeriodStart, arg.PeriodEnd, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumPrepaidUsageSettlementsForStatement = `-- name: SumPrepaidUsageSettlementsForStatement :one
SELECT COALESCE(SUM(amount_micro), 0)::bigint AS amount_micro,
       COUNT(*)::bigint AS settlements
FROM purser.prepaid_usage_settlements
WHERE tenant_id = $1::text::uuid
  AND billing_period_start >= $2::timestamptz
  AND billing_period_start < $3::timestamptz
`

type SumPrepaidUsageSettlementsForStatementParams struct {
	TenantID    string    `db:"tenant_id" json:"tenant_id"`
	PeriodStart time.Time `db:"period_start" json:"period_start"`
	PeriodEnd   time.Time `db:"period_end" json:"period_end"`
}

type SumPrepaidUsageSettlementsForStatementRow struct {
	AmountMicro int64 `db:"amount_micro" json:"amount_micro"`
	Settlements int64 `db:"settlements" json:"settlements"`
}

// What prepaid usage settlements took from the balance for usage of billing
// periods starting inside [period_start, period_end).
func (q *Queries) SumPrepaidUsageSettlementsForStatement(ctx context.Context, arg SumPrepaidUsageSettlementsForStatementParams) (SumPrepaidUsageSettlementsForStatementRow, error) {
	row := q.db.QueryRowContext(ctx, sumPrepaidUsageSettlementsForStatement, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var i SumPrepaidUsageSettlementsForStatementRow
	err := row.Scan(&i.AmountMicro, &i.Settlements)
	return i, err
}
