---
# WireGuard mesh network configuration

- name: Install WireGuard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: Create WireGuard directory
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Get node private key from Terraform
  slurp:
    src: "{{ terraform_keys_dir }}/{{ inventory_hostname }}.key"
  register: wg_private_key
  delegate_to: localhost
  become: false

- name: Configure WireGuard interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  notify: restart wireguard
  vars:
    node_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    peers: "{{ groups['all'] | difference([inventory_hostname]) }}"

- name: Enable WireGuard service
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: Configure sysctl for IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes 