---
- name: Install Nginx
  ansible.builtin.package:
    name: "{{ nginx_package_by_family[ansible_facts.os_family] | default('nginx') }}"
    state: present

- name: Install openssl (placeholder cert generation)
  ansible.builtin.package:
    name: "{{ nginx_openssl_package_by_family[ansible_facts.os_family] | default('openssl') }}"
    state: present
