// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cluster_access.sql

package quartermasterdb

import (
	"context"
	"database/sql"
)

const bootstrapTenantClusterAccess = `-- name: BootstrapTenantClusterAccess :exec
INSERT INTO quartermaster.tenant_cluster_access
    (tenant_id, cluster_id, access_level, subscription_status, resource_limits,
     is_active, granted_at, created_at, updated_at)
VALUES ($1::uuid, $2, 'shared', 'active',
        COALESCE($3::text::jsonb, '{}'::jsonb), true, NOW(), NOW(), NOW())
ON CONFLICT (tenant_id, cluster_id) DO UPDATE SET
    subscription_status = 'active',
    is_active = true,
    resource_limits = COALESCE(NULLIF(quartermaster.tenant_cluster_access.resource_limits, '{}'::jsonb), EXCLUDED.resource_limits),
    updated_at = NOW()
`

type BootstrapTenantClusterAccessParams struct {
	TenantID       string         `db:"tenant_id" json:"tenant_id"`
	ClusterID      string         `db:"cluster_id" json:"cluster_id"`
	ResourceLimits sql.NullString `db:"resource_limits" json:"resource_limits"`
}

func (q *Queries) BootstrapTenantClusterAccess(ctx context.Context, arg BootstrapTenantClusterAccessParams) error {
	_, err := q.db.ExecContext(ctx, bootstrapTenantClusterAccess, arg.TenantID, arg.ClusterID, arg.ResourceLimits)
	return err
}

const deactivateTenantClusterAccess = `-- name: DeactivateTenantClusterAccess :exec
UPDATE quartermaster.tenant_cluster_access
SET is_active = false, subscription_status = 'suspended', updated_at = NOW()
WHERE tenant_id = $1::uuid
  AND cluster_id = $2
  AND is_active = true
`

type DeactivateTenantClusterAccessParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	ClusterID string `db:"cluster_id" json:"cluster_id"`
}

func (q *Queries) DeactivateTenantClusterAccess(ctx context.Context, arg DeactivateTenantClusterAccessParams) error {
	_, err := q.db.ExecContext(ctx, deactivateTenantClusterAccess, arg.TenantID, arg.ClusterID)
	return err
}

const getClusterDeploymentModel = `-- name: GetClusterDeploymentModel :one
SELECT deployment_model
FROM quartermaster.infrastructure_clusters
WHERE cluster_id = $1
`

func (q *Queries) GetClusterDeploymentModel(ctx context.Context, clusterID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getClusterDeploymentModel, clusterID)
	var deployment_model sql.NullString
	err := row.Scan(&deployment_model)
	return deployment_model, err
}

const getClusterOfficialState = `-- name: GetClusterOfficialState :one
SELECT is_platform_official, is_active
FROM quartermaster.infrastructure_clusters
WHERE cluster_id = $1
`

type GetClusterOfficialStateRow struct {
	IsPlatformOfficial sql.NullBool `db:"is_platform_official" json:"is_platform_official"`
	IsActive           sql.NullBool `db:"is_active" json:"is_active"`
}

func (q *Queries) GetClusterOfficialState(ctx context.Context, clusterID string) (GetClusterOfficialStateRow, error) {
	row := q.db.QueryRowContext(ctx, getClusterOfficialState, clusterID)
	var i GetClusterOfficialStateRow
	err := row.Scan(&i.IsPlatformOfficial, &i.IsActive)
	return i, err
}

const getTenantPrimaryClusterClass = `-- name: GetTenantPrimaryClusterClass :one
SELECT c.cluster_class
FROM quartermaster.tenants t
LEFT JOIN quartermaster.infrastructure_clusters c ON c.cluster_id = t.primary_cluster_id
WHERE t.id = $1::uuid
`

func (q *Queries) GetTenantPrimaryClusterClass(ctx context.Context, tenantID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTenantPrimaryClusterClass, tenantID)
	var cluster_class sql.NullString
	err := row.Scan(&cluster_class)
	return cluster_class, err
}

const grantTenantClusterAccess = `-- name: GrantTenantClusterAccess :exec
INSERT INTO quartermaster.tenant_cluster_access
    (tenant_id, cluster_id, access_level, expires_at, created_at, updated_at)
VALUES ($1::uuid, $2, $3,
        $4::timestamptz, NOW(), NOW())
ON CONFLICT (tenant_id, cluster_id) DO UPDATE SET
    access_level = EXCLUDED.access_level,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
`

type GrantTenantClusterAccessParams struct {
	TenantID    string         `db:"tenant_id" json:"tenant_id"`
	ClusterID   string         `db:"cluster_id" json:"cluster_id"`
	AccessLevel sql.NullString `db:"access_level" json:"access_level"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GrantTenantClusterAccess(ctx context.Context, arg GrantTenantClusterAccessParams) error {
	_, err := q.db.ExecContext(ctx, grantTenantClusterAccess,
		arg.TenantID,
		arg.ClusterID,
		arg.AccessLevel,
		arg.ExpiresAt,
	)
	return err
}

const listRunningServiceClusterAssignments = `-- name: ListRunningServiceClusterAssignments :many
SELECT DISTINCT sca.cluster_id
FROM quartermaster.service_cluster_assignments sca
JOIN quartermaster.service_instances si ON si.id = sca.service_instance_id
JOIN quartermaster.services svc ON svc.service_id = si.service_id
WHERE si.instance_id = $1
  AND svc.type = $2
  AND si.status = 'running'
  AND sca.is_active = true
`

type ListRunningServiceClusterAssignmentsParams struct {
	InstanceID  string         `db:"instance_id" json:"instance_id"`
	ServiceType sql.NullString `db:"service_type" json:"service_type"`
}

func (q *Queries) ListRunningServiceClusterAssignments(ctx context.Context, arg ListRunningServiceClusterAssignmentsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRunningServiceClusterAssignments, arg.InstanceID, arg.ServiceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cluster_id string
		if err := rows.Scan(&cluster_id); err != nil {
			return nil, err
		}
		items = append(items, cluster_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantClusterAccessRows = `-- name: ListTenantClusterAccessRows :many
SELECT tca.cluster_id, tca.is_active, tca.subscription_status,
       COALESCE(ic.is_platform_official, false)::boolean AS is_platform_official
FROM quartermaster.tenant_cluster_access tca
LEFT JOIN quartermaster.infrastructure_clusters ic ON ic.cluster_id = tca.cluster_id
WHERE tca.tenant_id = $1::uuid
`

type ListTenantClusterAccessRowsRow struct {
	ClusterID          string         `db:"cluster_id" json:"cluster_id"`
	IsActive           sql.NullBool   `db:"is_active" json:"is_active"`
	SubscriptionStatus sql.NullString `db:"subscription_status" json:"subscription_status"`
	IsPlatformOfficial bool           `db:"is_platform_official" json:"is_platform_official"`
}

func (q *Queries) ListTenantClusterAccessRows(ctx context.Context, tenantID string) ([]ListTenantClusterAccessRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantClusterAccessRows, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantClusterAccessRowsRow{}
	for rows.Next() {
		var i ListTenantClusterAccessRowsRow
		if err := rows.Scan(
			&i.ClusterID,
			&i.IsActive,
			&i.SubscriptionStatus,
			&i.IsPlatformOfficial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantEntitledClusterIDs = `-- name: ListTenantEntitledClusterIDs :many
SELECT cluster_id
FROM quartermaster.tenant_cluster_access
WHERE tenant_id = $1::uuid
  AND is_active = TRUE
  AND subscription_status = 'active'
ORDER BY cluster_id
`

func (q *Queries) ListTenantEntitledClusterIDs(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTenantEntitledClusterIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cluster_id string
		if err := rows.Scan(&cluster_id); err != nil {
			return nil, err
		}
		items = append(items, cluster_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeTenantToCluster = `-- name: SubscribeTenantToCluster :exec
INSERT INTO quartermaster.tenant_cluster_access
    (tenant_id, cluster_id, access_level, is_active, created_at, updated_at)
VALUES ($1::uuid, $2, 'subscriber', true, NOW(), NOW())
ON CONFLICT (tenant_id, cluster_id) DO UPDATE SET
    is_active = true,
    updated_at = NOW()
`

type SubscribeTenantToClusterParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	ClusterID string `db:"cluster_id" json:"cluster_id"`
}

func (q *Queries) SubscribeTenantToCluster(ctx context.Context, arg SubscribeTenantToClusterParams) error {
	_, err := q.db.ExecContext(ctx, subscribeTenantToCluster, arg.TenantID, arg.ClusterID)
	return err
}

const unsubscribeTenantFromCluster = `-- name: UnsubscribeTenantFromCluster :exec
UPDATE quartermaster.tenant_cluster_access
SET is_active = false, updated_at = NOW()
WHERE tenant_id = $1::uuid AND cluster_id = $2
`

type UnsubscribeTenantFromClusterParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	ClusterID string `db:"cluster_id" json:"cluster_id"`
}

func (q *Queries) UnsubscribeTenantFromCluster(ctx context.Context, arg UnsubscribeTenantFromClusterParams) error {
	_, err := q.db.ExecContext(ctx, unsubscribeTenantFromCluster, arg.TenantID, arg.ClusterID)
	return err
}
