---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Apply frameworks.infra.clickhouse
      ansible.builtin.include_role:
        name: frameworks.infra.clickhouse
