---
role_name_check: 1
prerun: false

dependency:
  name: galaxy

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy

driver:
  name: docker

platforms:
  - name: clickhouse-instance
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    dns_servers:
      - "1.1.1.1"
      - "8.8.8.8"
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  playbooks:
    prepare: ../../../../molecule/prepare-apt.yml
  inventory:
    group_vars:
      all:
        clickhouse_version: "24.8.9.95"
        clickhouse_listen_host: "0.0.0.0"
        clickhouse_default_password: "molecule-test-password"
        clickhouse_databases:
          - analytics
          - tenants

verifier:
  name: ansible
