run:
  timeout: 10m
  go: "1.24"
  modules-download-mode: readonly

linters:
  enable:
    - unused        # Finds unused code (variables, constants, functions, types)
    - ineffassign   # Detects useless assignments

linters-settings:
  unused:
    # Treat exported symbols as potentially used by external code
    exported-is-used: true

issues:
  exclude-rules:
    # Exclude generated protobuf files
    - path: ".*\\.pb\\.go$"
      linters: [unused, ineffassign]

    # Exclude generated gRPC files
    - path: ".*_grpc\\.pb\\.go$"
      linters: [unused, ineffassign]

    # Exclude GraphQL generated code
    - path: "api_gateway/graph/generated/.*\\.go$"
      linters: [unused, ineffassign]

    - path: "api_gateway/graph/model/models_gen\\.go$"
      linters: [unused, ineffassign]

    # Test files may have intentionally unused fixtures
    - path: "_test\\.go$"
      linters: [unused]
      text: "unused"

  exclude-dirs:
    - vendor

  # Maximum issues to report (0 = unlimited)
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: line-number
  sort-results: true
