version: 2

run:
  timeout: 10m
  go: "1.24"
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Tier 1: Bug finders (essential, low false positives)
    - errcheck # Unchecked errors
    - govet # Go vet checks
    - ineffassign # Useless assignments
    - staticcheck # Comprehensive static analysis
    - unused # Unused code
    # Tier 2: Quality (catches real issues in HTTP/SQL/error handling)
    - bodyclose # HTTP response body leaks
    - durationcheck # time.Duration calculation mistakes
    - errorlint # Error wrapping correctness (Go 1.13+)
    - nilerr # Returns nil on non-nil error
    - noctx # HTTP requests without context
    - sqlclosecheck # Unclosed SQL rows/statements
    # Tier 3: Style (commented out - enable if desired)
    # - gofmt       # Formatting (redundant if using go fmt)
    # - goimports   # Import ordering (can be noisy)
    # - misspell    # Typo detection
    # - unconvert   # Unnecessary type conversions
    # - unparam     # Unused function parameters (false positives on interfaces)
    # Future consideration:
    # - gocritic    # Opinionated code suggestions (many rules, can be noisy)
    # - gocyclo     # Cyclomatic complexity (subjective thresholds)
    # - gocognit    # Cognitive complexity (subjective thresholds)
    # - funlen      # Function length limits (can be annoying)
    # - lll         # Line length limits (style preference)
    # - exhaustive  # Enum exhaustiveness in switches (causes churn)
    # - prealloc    # Slice preallocation hints (micro-optimization)
    # - wrapcheck   # Ensure errors from external packages are wrapped

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false # Allow _ = fn() for intentional ignores
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  govet:
    enable-all: true
    disable:
      - fieldalignment # Micro-optimization, too noisy
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016"]
    # ST1000: Package comments (not enforced)
    # ST1003: CamelCase naming (generated code has odd names)
    # ST1016: Method receiver names (style preference)

issues:
  exclude-rules:
    # Exclude generated protobuf files
    - path: ".*\\.pb\\.go$"
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
        - ineffassign

    # Exclude generated gRPC files
    - path: ".*_grpc\\.pb\\.go$"
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
        - ineffassign

    # Exclude GraphQL generated code
    - path: "api_gateway/graph/generated/.*\\.go$"
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
        - ineffassign

    - path: "api_gateway/graph/model/models_gen\\.go$"
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
        - ineffassign

    # Test files: allow unused fixtures and unchecked errors in tests
    - path: "_test\\.go$"
      linters:
        - errcheck
        - unused

    # Allow context.Background() in main/cmd packages (entry points)
    - path: "cmd/"
      linters:
        - noctx

  exclude-dirs:
    - vendor

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
  text:
    colors: true
    print-issued-lines: true
    print-linter-name: true
  sort-results: true
