version: "2"

run:
  go: "1.24"
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Tier 1: Bug finders (essential, low false positives)
    - errcheck # Unchecked errors
    - govet # Go vet checks
    - ineffassign # Useless assignments
    - staticcheck # Comprehensive static analysis
    - unused # Unused code
    # Tier 2: Quality (catches real issues in HTTP/SQL/error handling)
    - bodyclose # HTTP response body leaks
    - durationcheck # time.Duration calculation mistakes
    - errorlint # Error wrapping correctness (Go 1.13+)
    - nilerr # Returns nil on non-nil error
    - noctx # HTTP requests without context
    - sqlclosecheck # Unclosed SQL rows/statements

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false # Allow _ = fn() for intentional ignores
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    govet:
      enable-all: true
      disable:
        - fieldalignment # Micro-optimization, too noisy
    staticcheck:
      checks:
        - all
        - -ST1000 # Package comments (not enforced)
        - -ST1003 # CamelCase naming (generated code has odd names)
        - -ST1016 # Method receiver names (style preference)

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude generated protobuf files
      - linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
        path: .*\.pb\.go$

      # Exclude generated gRPC files
      - linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
        path: .*_grpc\.pb\.go$

      # Exclude GraphQL generated code
      - linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
        path: api_gateway/graph/generated/.*\.go$

      - linters:
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
        path: api_gateway/graph/model/models_gen\.go$

      # Test files: allow unused fixtures and unchecked errors in tests
      - linters:
          - errcheck
          - unused
        path: _test\.go$

      # Allow context.Background() in main/cmd packages (entry points)
      - linters:
          - noctx
        path: cmd/

    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
