packages:
  - packages/site-config
  - packages/map-core
  - website_marketing
  - website_application
  - npm_player/packages/*
  - npm_player/playground
  - npm_studio/packages/*
  - npm_api
  - website_docs

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  "@reown/appkit": true
  "@swc/core": true
  bufferutil: true
  esbuild: true
  lefthook: true
  sharp: true
  utf-8-validate: true

patchedDependencies:
  "@codecov/sveltekit-plugin": patches/@codecov__sveltekit-plugin.patch
