packages:
  - packages/site-config
  - website_marketing
  - website_application
  - npm_player/packages/*
  - npm_player/playground
  - npm_studio/packages/*
  - website_docs

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
