// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_retention.sql

package commodoredb

import (
	"context"
	"database/sql"
)

const applyClipRetentionState = `-- name: ApplyClipRetentionState :exec
UPDATE commodore.clips
SET retention_override_days = $1::integer,
    retention_override_until = $2::timestamptz,
    retention_source = $3,
    retention_until = $4::timestamptz,
    updated_at = NOW()
WHERE clip_hash = $5
  AND tenant_id = $6::uuid
`

type ApplyClipRetentionStateParams struct {
	OverrideDays    sql.NullInt32  `db:"override_days" json:"override_days"`
	OverrideUntil   sql.NullTime   `db:"override_until" json:"override_until"`
	RetentionSource sql.NullString `db:"retention_source" json:"retention_source"`
	RetentionUntil  sql.NullTime   `db:"retention_until" json:"retention_until"`
	ArtifactHash    string         `db:"artifact_hash" json:"artifact_hash"`
	TenantID        string         `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ApplyClipRetentionState(ctx context.Context, arg ApplyClipRetentionStateParams) error {
	_, err := q.db.ExecContext(ctx, applyClipRetentionState,
		arg.OverrideDays,
		arg.OverrideUntil,
		arg.RetentionSource,
		arg.RetentionUntil,
		arg.ArtifactHash,
		arg.TenantID,
	)
	return err
}

const applyDVRRetentionState = `-- name: ApplyDVRRetentionState :exec
UPDATE commodore.dvr_recordings
SET retention_override_days = $1::integer,
    retention_override_until = $2::timestamptz,
    retention_source = $3,
    retention_until = $4::timestamptz,
    updated_at = NOW()
WHERE dvr_hash = $5
  AND tenant_id = $6::uuid
`

type ApplyDVRRetentionStateParams struct {
	OverrideDays    sql.NullInt32  `db:"override_days" json:"override_days"`
	OverrideUntil   sql.NullTime   `db:"override_until" json:"override_until"`
	RetentionSource sql.NullString `db:"retention_source" json:"retention_source"`
	RetentionUntil  sql.NullTime   `db:"retention_until" json:"retention_until"`
	ArtifactHash    string         `db:"artifact_hash" json:"artifact_hash"`
	TenantID        string         `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ApplyDVRRetentionState(ctx context.Context, arg ApplyDVRRetentionStateParams) error {
	_, err := q.db.ExecContext(ctx, applyDVRRetentionState,
		arg.OverrideDays,
		arg.OverrideUntil,
		arg.RetentionSource,
		arg.RetentionUntil,
		arg.ArtifactHash,
		arg.TenantID,
	)
	return err
}

const applyVODRetentionState = `-- name: ApplyVODRetentionState :exec
UPDATE commodore.vod_assets
SET retention_override_days = $1::integer,
    retention_override_until = $2::timestamptz,
    retention_source = $3,
    retention_until = $4::timestamptz,
    updated_at = NOW()
WHERE vod_hash = $5
  AND tenant_id = $6::uuid
`

type ApplyVODRetentionStateParams struct {
	OverrideDays    sql.NullInt32  `db:"override_days" json:"override_days"`
	OverrideUntil   sql.NullTime   `db:"override_until" json:"override_until"`
	RetentionSource sql.NullString `db:"retention_source" json:"retention_source"`
	RetentionUntil  sql.NullTime   `db:"retention_until" json:"retention_until"`
	ArtifactHash    string         `db:"artifact_hash" json:"artifact_hash"`
	TenantID        string         `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ApplyVODRetentionState(ctx context.Context, arg ApplyVODRetentionStateParams) error {
	_, err := q.db.ExecContext(ctx, applyVODRetentionState,
		arg.OverrideDays,
		arg.OverrideUntil,
		arg.RetentionSource,
		arg.RetentionUntil,
		arg.ArtifactHash,
		arg.TenantID,
	)
	return err
}

const getClipRetentionStreamID = `-- name: GetClipRetentionStreamID :one
SELECT COALESCE(stream_id::text, ''::text)::text AS stream_id
FROM commodore.clips
WHERE clip_hash = $1
  AND tenant_id = $2::uuid
`

type GetClipRetentionStreamIDParams struct {
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetClipRetentionStreamID(ctx context.Context, arg GetClipRetentionStreamIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getClipRetentionStreamID, arg.ArtifactHash, arg.TenantID)
	var stream_id string
	err := row.Scan(&stream_id)
	return stream_id, err
}

const getClipRetentionUntil = `-- name: GetClipRetentionUntil :one
SELECT retention_until
FROM commodore.clips
WHERE clip_hash = $1
  AND tenant_id = $2::uuid
`

type GetClipRetentionUntilParams struct {
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetClipRetentionUntil(ctx context.Context, arg GetClipRetentionUntilParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getClipRetentionUntil, arg.ArtifactHash, arg.TenantID)
	var retention_until sql.NullTime
	err := row.Scan(&retention_until)
	return retention_until, err
}

const getDVRRetentionStreamID = `-- name: GetDVRRetentionStreamID :one
SELECT COALESCE(stream_id::text, ''::text)::text AS stream_id
FROM commodore.dvr_recordings
WHERE dvr_hash = $1
  AND tenant_id = $2::uuid
`

type GetDVRRetentionStreamIDParams struct {
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDVRRetentionStreamID(ctx context.Context, arg GetDVRRetentionStreamIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDVRRetentionStreamID, arg.ArtifactHash, arg.TenantID)
	var stream_id string
	err := row.Scan(&stream_id)
	return stream_id, err
}

const getDVRRetentionUntil = `-- name: GetDVRRetentionUntil :one
SELECT retention_until
FROM commodore.dvr_recordings
WHERE dvr_hash = $1
  AND tenant_id = $2::uuid
`

type GetDVRRetentionUntilParams struct {
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetDVRRetentionUntil(ctx context.Context, arg GetDVRRetentionUntilParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getDVRRetentionUntil, arg.ArtifactHash, arg.TenantID)
	var retention_until sql.NullTime
	err := row.Scan(&retention_until)
	return retention_until, err
}

const getStreamRetentionOverrides = `-- name: GetStreamRetentionOverrides :one
SELECT id::text AS stream_id,
       dvr_retention_days_override,
       clip_retention_days_override
FROM commodore.streams
WHERE id = $1::uuid
  AND tenant_id = $2::uuid
`

type GetStreamRetentionOverridesParams struct {
	StreamID string `db:"stream_id" json:"stream_id"`
	TenantID string `db:"tenant_id" json:"tenant_id"`
}

type GetStreamRetentionOverridesRow struct {
	StreamID                  string        `db:"stream_id" json:"stream_id"`
	DvrRetentionDaysOverride  sql.NullInt32 `db:"dvr_retention_days_override" json:"dvr_retention_days_override"`
	ClipRetentionDaysOverride sql.NullInt32 `db:"clip_retention_days_override" json:"clip_retention_days_override"`
}

func (q *Queries) GetStreamRetentionOverrides(ctx context.Context, arg GetStreamRetentionOverridesParams) (GetStreamRetentionOverridesRow, error) {
	row := q.db.QueryRowContext(ctx, getStreamRetentionOverrides, arg.StreamID, arg.TenantID)
	var i GetStreamRetentionOverridesRow
	err := row.Scan(&i.StreamID, &i.DvrRetentionDaysOverride, &i.ClipRetentionDaysOverride)
	return i, err
}

const getTenantMediaRetentionPolicy = `-- name: GetTenantMediaRetentionPolicy :one
SELECT default_vod_retention_days,
       default_dvr_retention_days,
       default_clip_retention_days,
       COALESCE(updated_by::text, ''::text)::text AS updated_by,
       updated_at
FROM commodore.tenant_media_retention_policies
WHERE tenant_id = $1::uuid
`

type GetTenantMediaRetentionPolicyRow struct {
	DefaultVodRetentionDays  sql.NullInt32 `db:"default_vod_retention_days" json:"default_vod_retention_days"`
	DefaultDvrRetentionDays  sql.NullInt32 `db:"default_dvr_retention_days" json:"default_dvr_retention_days"`
	DefaultClipRetentionDays sql.NullInt32 `db:"default_clip_retention_days" json:"default_clip_retention_days"`
	UpdatedBy                string        `db:"updated_by" json:"updated_by"`
	UpdatedAt                sql.NullTime  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantMediaRetentionPolicy(ctx context.Context, tenantID string) (GetTenantMediaRetentionPolicyRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantMediaRetentionPolicy, tenantID)
	var i GetTenantMediaRetentionPolicyRow
	err := row.Scan(
		&i.DefaultVodRetentionDays,
		&i.DefaultDvrRetentionDays,
		&i.DefaultClipRetentionDays,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getVODRetentionUntil = `-- name: GetVODRetentionUntil :one
SELECT retention_until
FROM commodore.vod_assets
WHERE vod_hash = $1
  AND tenant_id = $2::uuid
`

type GetVODRetentionUntilParams struct {
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetVODRetentionUntil(ctx context.Context, arg GetVODRetentionUntilParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getVODRetentionUntil, arg.ArtifactHash, arg.TenantID)
	var retention_until sql.NullTime
	err := row.Scan(&retention_until)
	return retention_until, err
}

const resolveClipTenantArtifact = `-- name: ResolveClipTenantArtifact :one
SELECT COALESCE(origin_cluster_id, '') AS origin_cluster_id, clip_hash
FROM commodore.clips
WHERE (clip_hash = $1 OR id::text = $1)
  AND tenant_id = $2::uuid
`

type ResolveClipTenantArtifactParams struct {
	Identifier string `db:"identifier" json:"identifier"`
	TenantID   string `db:"tenant_id" json:"tenant_id"`
}

type ResolveClipTenantArtifactRow struct {
	OriginClusterID string `db:"origin_cluster_id" json:"origin_cluster_id"`
	ClipHash        string `db:"clip_hash" json:"clip_hash"`
}

func (q *Queries) ResolveClipTenantArtifact(ctx context.Context, arg ResolveClipTenantArtifactParams) (ResolveClipTenantArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, resolveClipTenantArtifact, arg.Identifier, arg.TenantID)
	var i ResolveClipTenantArtifactRow
	err := row.Scan(&i.OriginClusterID, &i.ClipHash)
	return i, err
}

const resolveDVRTenantArtifact = `-- name: ResolveDVRTenantArtifact :one
SELECT COALESCE(origin_cluster_id, '') AS origin_cluster_id, dvr_hash
FROM commodore.dvr_recordings
WHERE (dvr_hash = $1
       OR id::text = $1
       OR lower(playback_id::text) = lower($1::text))
  AND tenant_id = $2::uuid
`

type ResolveDVRTenantArtifactParams struct {
	Identifier string `db:"identifier" json:"identifier"`
	TenantID   string `db:"tenant_id" json:"tenant_id"`
}

type ResolveDVRTenantArtifactRow struct {
	OriginClusterID string `db:"origin_cluster_id" json:"origin_cluster_id"`
	DvrHash         string `db:"dvr_hash" json:"dvr_hash"`
}

func (q *Queries) ResolveDVRTenantArtifact(ctx context.Context, arg ResolveDVRTenantArtifactParams) (ResolveDVRTenantArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, resolveDVRTenantArtifact, arg.Identifier, arg.TenantID)
	var i ResolveDVRTenantArtifactRow
	err := row.Scan(&i.OriginClusterID, &i.DvrHash)
	return i, err
}

const resolveVODTenantArtifact = `-- name: ResolveVODTenantArtifact :one
SELECT COALESCE(origin_cluster_id, '') AS origin_cluster_id,
       vod_hash,
       COALESCE(origin_type, '') AS origin_type
FROM commodore.vod_assets
WHERE (vod_hash = $1 OR id::text = $1)
  AND tenant_id = $2::uuid
`

type ResolveVODTenantArtifactParams struct {
	Identifier string `db:"identifier" json:"identifier"`
	TenantID   string `db:"tenant_id" json:"tenant_id"`
}

type ResolveVODTenantArtifactRow struct {
	OriginClusterID string `db:"origin_cluster_id" json:"origin_cluster_id"`
	VodHash         string `db:"vod_hash" json:"vod_hash"`
	OriginType      string `db:"origin_type" json:"origin_type"`
}

func (q *Queries) ResolveVODTenantArtifact(ctx context.Context, arg ResolveVODTenantArtifactParams) (ResolveVODTenantArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, resolveVODTenantArtifact, arg.Identifier, arg.TenantID)
	var i ResolveVODTenantArtifactRow
	err := row.Scan(&i.OriginClusterID, &i.VodHash, &i.OriginType)
	return i, err
}

const updateStreamRetentionOverrides = `-- name: UpdateStreamRetentionOverrides :one
UPDATE commodore.streams
SET dvr_retention_days_override = CASE
        WHEN $1::boolean THEN $2::integer
        ELSE dvr_retention_days_override
    END,
    clip_retention_days_override = CASE
        WHEN $3::boolean THEN $4::integer
        ELSE clip_retention_days_override
    END,
    updated_at = NOW()
WHERE id = $5::uuid
  AND tenant_id = $6::uuid
RETURNING dvr_retention_days_override, clip_retention_days_override
`

type UpdateStreamRetentionOverridesParams struct {
	ApplyDvr  bool          `db:"apply_dvr" json:"apply_dvr"`
	DvrDays   sql.NullInt32 `db:"dvr_days" json:"dvr_days"`
	ApplyClip bool          `db:"apply_clip" json:"apply_clip"`
	ClipDays  sql.NullInt32 `db:"clip_days" json:"clip_days"`
	StreamID  string        `db:"stream_id" json:"stream_id"`
	TenantID  string        `db:"tenant_id" json:"tenant_id"`
}

type UpdateStreamRetentionOverridesRow struct {
	DvrRetentionDaysOverride  sql.NullInt32 `db:"dvr_retention_days_override" json:"dvr_retention_days_override"`
	ClipRetentionDaysOverride sql.NullInt32 `db:"clip_retention_days_override" json:"clip_retention_days_override"`
}

func (q *Queries) UpdateStreamRetentionOverrides(ctx context.Context, arg UpdateStreamRetentionOverridesParams) (UpdateStreamRetentionOverridesRow, error) {
	row := q.db.QueryRowContext(ctx, updateStreamRetentionOverrides,
		arg.ApplyDvr,
		arg.DvrDays,
		arg.ApplyClip,
		arg.ClipDays,
		arg.StreamID,
		arg.TenantID,
	)
	var i UpdateStreamRetentionOverridesRow
	err := row.Scan(&i.DvrRetentionDaysOverride, &i.ClipRetentionDaysOverride)
	return i, err
}

const upsertTenantMediaRetentionPolicy = `-- name: UpsertTenantMediaRetentionPolicy :exec
INSERT INTO commodore.tenant_media_retention_policies
    (tenant_id,
     default_vod_retention_days,
     default_dvr_retention_days,
     default_clip_retention_days,
     updated_by,
     created_at,
     updated_at)
VALUES
    ($1::uuid,
     CASE WHEN $2::boolean THEN $3::integer ELSE NULL END,
     CASE WHEN $4::boolean THEN $5::integer ELSE NULL END,
     CASE WHEN $6::boolean THEN $7::integer ELSE NULL END,
     NULLIF($8::text, '')::uuid,
     NOW(),
     NOW())
ON CONFLICT (tenant_id) DO UPDATE
SET default_vod_retention_days = CASE
        WHEN $2::boolean THEN EXCLUDED.default_vod_retention_days
        ELSE tenant_media_retention_policies.default_vod_retention_days
    END,
    default_dvr_retention_days = CASE
        WHEN $4::boolean THEN EXCLUDED.default_dvr_retention_days
        ELSE tenant_media_retention_policies.default_dvr_retention_days
    END,
    default_clip_retention_days = CASE
        WHEN $6::boolean THEN EXCLUDED.default_clip_retention_days
        ELSE tenant_media_retention_policies.default_clip_retention_days
    END,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
`

type UpsertTenantMediaRetentionPolicyParams struct {
	TenantID  string        `db:"tenant_id" json:"tenant_id"`
	ApplyVod  bool          `db:"apply_vod" json:"apply_vod"`
	VodDays   sql.NullInt32 `db:"vod_days" json:"vod_days"`
	ApplyDvr  bool          `db:"apply_dvr" json:"apply_dvr"`
	DvrDays   sql.NullInt32 `db:"dvr_days" json:"dvr_days"`
	ApplyClip bool          `db:"apply_clip" json:"apply_clip"`
	ClipDays  sql.NullInt32 `db:"clip_days" json:"clip_days"`
	UpdatedBy string        `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpsertTenantMediaRetentionPolicy(ctx context.Context, arg UpsertTenantMediaRetentionPolicyParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenantMediaRetentionPolicy,
		arg.TenantID,
		arg.ApplyVod,
		arg.VodDays,
		arg.ApplyDvr,
		arg.DvrDays,
		arg.ApplyClip,
		arg.ClipDays,
		arg.UpdatedBy,
	)
	return err
}
