export const WRAPPER_PARITY_EVENT_NAMES = [
  "stateChange",
  "streamStateChange",
  "timeUpdate",
  "error",
  "errorCleared",
  "ready",
  "playerSelected",
  "volumeChange",
  "loopChange",
  "fullscreenChange",
  "pipChange",
  "holdSpeedStart",
  "holdSpeedEnd",
  "hoverStart",
  "hoverEnd",
  "captionsChange",
  "protocolSwapped",
  "playbackFailed",
] as const;

export const WRAPPER_PARITY_INITIAL_STATE = {
  state: "booting",
  streamState: null,
  endpoints: null,
  metadata: null,
  videoElement: null,
  currentTime: 0,
  isPlaying: false,
  isPaused: true,
  isBuffering: false,
  isMuted: true,
  volume: 1,
  error: null,
  errorDetails: null,
  isPassiveError: false,
  hasPlaybackStarted: false,
  isHoldingSpeed: false,
  holdSpeed: 2,
  isHovering: false,
  shouldShowControls: false,
  isLoopEnabled: false,
  isFullscreen: false,
  isPiPActive: false,
  isEffectivelyLive: false,
  shouldShowIdleScreen: true,
  currentPlayerInfo: null,
  currentSourceInfo: null,
  playbackQuality: null,
  subtitlesEnabled: false,
  toast: null,
} as const;

export const WRAPPER_PARITY_ACTION_METHODS = [
  "play",
  "pause",
  "togglePlay",
  "seek",
  "seekBy",
  "jumpToLive",
  "setVolume",
  "toggleMute",
  "toggleLoop",
  "toggleFullscreen",
  "togglePiP",
  "toggleSubtitles",
  "clearError",
  "dismissToast",
  "retry",
  "reload",
  "getQualities",
  "selectQuality",
  "handleMouseEnter",
  "handleMouseLeave",
  "handleMouseMove",
  "handleTouchStart",
  "setDevModeOptions",
] as const;

export const PLAYER_COMPONENT_PARITY_CONTEXT_MENU_COMMON_LABELS = [
  "showStats",
  "hideStats",
  "settings",
  "hideSettings",
  "pictureInPicture",
  "enableLoop",
  "disableLoop",
] as const;

export const PLAYER_COMPONENT_PARITY_CONTEXT_MENU_WC_ROLE_MARKERS = [
  'role="menuitemcheckbox"',
] as const;

export const PLAYER_COMPONENT_PARITY_CONTEXT_MENU_REACT_SVELTE_SELECT_MARKER =
  "<ContextMenuItem onSelect=" as const;
