query GetBillingDetails {
  billingDetails {
    email
    name
    company
    vatNumber
    address {
      street
      city
      state
      postalCode
      country
    }
    isComplete
    updatedAt
  }
}
