query GetClusterMediaConsentChange($clusterId: ID!, $idempotencyKey: String!) {
  clusterMediaConsentChange(clusterId: $clusterId, idempotencyKey: $idempotencyKey) {
    __typename
    ... on MediaCapacityConsentChange {
      ...MediaCapacityConsentChangeFields @mask_disable
    }
    ... on MediaPlacementError {
      ...MediaPlacementErrorFields @mask_disable
    }
    ... on AuthError {
      message
    }
    ... on NotFoundError {
      message
    }
  }
}
