# Fetch list of cluster subscriptions for the current tenant
query GetMySubscriptions {
  mySubscriptions {
    id
    clusterId
    clusterName
    clusterType
    healthStatus
    createdAt
    isDefaultCluster
    isSubscribed
  }
}
