# Fetch paginated list of streams with core fields and live status metrics
query GetStreamsConnection($first: Int = 50, $after: String) {
  streamsConnection(page: { first: $first, after: $after }) @paginate {
    edges {
      cursor
      node {
        ...StreamCoreFields
        metrics {
          ...StreamMetricsFields
        }
      }
    }
    pageInfo {
      ...PageInfoFields
    }
    totalCount
  }
}
