query GetStreamingConfig {
  streamingConfig {
    preferredClusterLabel
    ingestDomain
    edgeDomain
    playDomain
    chandlerDomain
    officialClusterLabel
    officialIngestDomain
    officialEdgeDomain
    officialPlayDomain
    officialChandlerDomain
    globalIngestDomain
    globalEdgeDomain
    globalPlayDomain
    globalChandlerDomain
    globalLivepeerDomain
    tenantIngestDomain
    tenantEdgeDomain
    tenantPlayDomain
    tenantChandlerDomain
    tenantLivepeerDomain
    srtPort
    rtmpPort
  }
}
