query GetStreamingConfig {
  streamingConfig {
    preferredClusterLabel
    ingestDomain
    edgeDomain
    playDomain
    officialClusterLabel
    officialIngestDomain
    officialEdgeDomain
    officialPlayDomain
    globalIngestDomain
    globalEdgeDomain
    globalPlayDomain
    globalLivepeerDomain
    tenantIngestDomain
    tenantEdgeDomain
    tenantPlayDomain
    tenantLivepeerDomain
    srtPort
    rtmpPort
  }
}
