query GetStreamPlacementContext($id: ID!) {
  stream(id: $id) {
    id
    streamId
    ingestMode
    pullSource {
      enabled
      class
    }
    managedSource {
      sourceKind
      alwaysOn
      placementCount
    }
    sourceLocation {
      mode
      clusters {
        clusterId
        nodeIds
      }
      avoidNodeIds
    }
  }
}
