# Get health status of service instances
query GetServiceInstancesHealth($serviceId: String) {
  analytics {
    infra {
      serviceInstancesHealth(serviceId: $serviceId) {
        instanceId
        serviceId
        clusterId
        protocol
        host
        port
        healthEndpoint
        status
        lastHealthCheck
      }
    }
  }
}
