query GetStreamingConfig {
  streamingConfig {
    preferredClusterLabel
    ingestDomain
    edgeDomain
    playDomain
    chandlerDomain
    officialClusterLabel
    officialIngestDomain
    officialEdgeDomain
    officialPlayDomain
    officialChandlerDomain
    srtPort
    rtmpPort
  }
}
