query GetVodUploadStatus($uploadId: ID!) {
  vodUploadStatus(uploadId: $uploadId) {
    ... on VodUploadStatus {
      uploadId
      state
      expiresAt
      retentionUntil
      uploadedParts {
        partNumber
        etag
        sizeBytes
      }
      missingParts
      lastErrorCode
      artifactHash
      playbackId
    }
    ... on ValidationError {
      message
      field
      code
    }
    ... on NotFoundError {
      message
      code
    }
    ... on AuthError {
      message
      code
    }
  }
}
