---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Apply frameworks.infra.kafka (combined mode)
      ansible.builtin.include_role:
        name: frameworks.infra.kafka

    - name: Apply frameworks.infra.kafka_mirrormaker
      ansible.builtin.include_role:
        name: frameworks.infra.kafka_mirrormaker
