-- artifact_state_current: explicit local-copy placement column.
--
-- The placement fact "a node holds a full local copy (origin or synced cache)" now has ONE explicit
-- name, has_local_copy, replacing the is_hot column. Additive expand step: a new ingest binary writes
-- has_local_copy while the old binary keeps writing the is_hot column (dropped in contract once every
-- binary is on the new name), so the rolling window never inserts an unknown column. The durable S3
-- facts is_synced / is_finalized are untouched.
--
-- IF NOT EXISTS keeps it idempotent against a freshly-baselined cluster whose baseline already carries
-- has_local_copy. Schema source of truth: pkg/database/sql/clickhouse/periscope.sql.
ALTER TABLE artifact_state_current ADD COLUMN IF NOT EXISTS has_local_copy Nullable(Bool);
