-- A monotonic revision that ORDERS source-ownership projections for the cluster-wide registry. The
-- ingest generation (session id) is globally unique but NOT ordered, so it cannot tell a stale
-- source-state write from a newer one. Each source transition (ProjectSourceIfCurrent, the offline
-- flip in FenceOfflineBackstop) draws nextval UNDER the (tenant, stream) advisory lock — which
-- serializes those transitions — so a later transition always carries a strictly higher revision.
--
-- The registry stores the revision on the source Location and merges source-ownership fields by it
-- (highest revision wins), independently of the last-writer-wins UpdatedAt used for unrelated location
-- state (replication/pull/liveness). That stops a stale replica — one whose unrelated-location write
-- carries an old source it has not yet caught up on — from making stale source ownership look "newer"
-- and clobbering the real publisher.
--
-- A global sequence is monotonic across all streams; per-stream ordering is implied because a stream's
-- transitions are serialized under its advisory lock. Revision 0 is "unversioned" (a pull-ownership
-- stamp or a test), which falls back to UpdatedAt in the merge.
CREATE SEQUENCE IF NOT EXISTS foghorn.source_projection_revision;
