---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Apply frameworks.infra.prometheus_stack
      ansible.builtin.include_role:
        name: frameworks.infra.prometheus_stack
