---
- name: Helmsman | install
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: Helmsman | configure
  ansible.builtin.import_tasks: configure.yml
  tags: [configure]

- name: Helmsman | flush handlers before service
  ansible.builtin.meta: flush_handlers
  tags: [configure, service]

- name: Helmsman | service
  ansible.builtin.import_tasks: service.yml
  tags: [service]

- name: Helmsman | flush handlers before validate
  ansible.builtin.meta: flush_handlers
  tags: [service, validate]

- name: Helmsman | validate
  ansible.builtin.import_tasks: validate.yml
  tags: [validate]

- name: Helmsman | restart
  ansible.builtin.import_tasks: restart.yml
  tags: [restart, never]

- name: Helmsman | cleanup
  ansible.builtin.import_tasks: cleanup.yml
  tags: [cleanup, never]
