// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lookout.proto

package lookoutpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LookoutService_ListIncidents_FullMethodName       = "/lookout.LookoutService/ListIncidents"
	LookoutService_GetIncident_FullMethodName         = "/lookout.LookoutService/GetIncident"
	LookoutService_AcknowledgeIncident_FullMethodName = "/lookout.LookoutService/AcknowledgeIncident"
	LookoutService_AssignIncident_FullMethodName      = "/lookout.LookoutService/AssignIncident"
	LookoutService_ResolveIncident_FullMethodName     = "/lookout.LookoutService/ResolveIncident"
	LookoutService_AddIncidentNote_FullMethodName     = "/lookout.LookoutService/AddIncidentNote"
	LookoutService_AttachInvestigation_FullMethodName = "/lookout.LookoutService/AttachInvestigation"
)

// LookoutServiceClient is the client API for LookoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LookoutService owns incidents built from Alertmanager notifications.
//
// Authorization: platform-scope incidents require a platform operator caller.
// Tenant-scope incidents require the caller's tenant to match the incident's
// tenant; platform operators may read and act on every scope.
// AttachInvestigation accepts service-token callers only.
type LookoutServiceClient interface {
	ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error)
	GetIncident(ctx context.Context, in *GetIncidentRequest, opts ...grpc.CallOption) (*GetIncidentResponse, error)
	AcknowledgeIncident(ctx context.Context, in *AcknowledgeIncidentRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error)
	AssignIncident(ctx context.Context, in *AssignIncidentRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error)
	ResolveIncident(ctx context.Context, in *ResolveIncidentRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error)
	AddIncidentNote(ctx context.Context, in *AddIncidentNoteRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error)
	AttachInvestigation(ctx context.Context, in *AttachInvestigationRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error)
}

type lookoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLookoutServiceClient(cc grpc.ClientConnInterface) LookoutServiceClient {
	return &lookoutServiceClient{cc}
}

func (c *lookoutServiceClient) ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIncidentsResponse)
	err := c.cc.Invoke(ctx, LookoutService_ListIncidents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookoutServiceClient) GetIncident(ctx context.Context, in *GetIncidentRequest, opts ...grpc.CallOption) (*GetIncidentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncidentResponse)
	err := c.cc.Invoke(ctx, LookoutService_GetIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookoutServiceClient) AcknowledgeIncident(ctx context.Context, in *AcknowledgeIncidentRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncidentMutationResponse)
	err := c.cc.Invoke(ctx, LookoutService_AcknowledgeIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookoutServiceClient) AssignIncident(ctx context.Context, in *AssignIncidentRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncidentMutationResponse)
	err := c.cc.Invoke(ctx, LookoutService_AssignIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookoutServiceClient) ResolveIncident(ctx context.Context, in *ResolveIncidentRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncidentMutationResponse)
	err := c.cc.Invoke(ctx, LookoutService_ResolveIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookoutServiceClient) AddIncidentNote(ctx context.Context, in *AddIncidentNoteRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncidentMutationResponse)
	err := c.cc.Invoke(ctx, LookoutService_AddIncidentNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lookoutServiceClient) AttachInvestigation(ctx context.Context, in *AttachInvestigationRequest, opts ...grpc.CallOption) (*IncidentMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncidentMutationResponse)
	err := c.cc.Invoke(ctx, LookoutService_AttachInvestigation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LookoutServiceServer is the server API for LookoutService service.
// All implementations must embed UnimplementedLookoutServiceServer
// for forward compatibility.
//
// LookoutService owns incidents built from Alertmanager notifications.
//
// Authorization: platform-scope incidents require a platform operator caller.
// Tenant-scope incidents require the caller's tenant to match the incident's
// tenant; platform operators may read and act on every scope.
// AttachInvestigation accepts service-token callers only.
type LookoutServiceServer interface {
	ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error)
	GetIncident(context.Context, *GetIncidentRequest) (*GetIncidentResponse, error)
	AcknowledgeIncident(context.Context, *AcknowledgeIncidentRequest) (*IncidentMutationResponse, error)
	AssignIncident(context.Context, *AssignIncidentRequest) (*IncidentMutationResponse, error)
	ResolveIncident(context.Context, *ResolveIncidentRequest) (*IncidentMutationResponse, error)
	AddIncidentNote(context.Context, *AddIncidentNoteRequest) (*IncidentMutationResponse, error)
	AttachInvestigation(context.Context, *AttachInvestigationRequest) (*IncidentMutationResponse, error)
	mustEmbedUnimplementedLookoutServiceServer()
}

// UnimplementedLookoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLookoutServiceServer struct{}

func (UnimplementedLookoutServiceServer) ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIncidents not implemented")
}
func (UnimplementedLookoutServiceServer) GetIncident(context.Context, *GetIncidentRequest) (*GetIncidentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncident not implemented")
}
func (UnimplementedLookoutServiceServer) AcknowledgeIncident(context.Context, *AcknowledgeIncidentRequest) (*IncidentMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeIncident not implemented")
}
func (UnimplementedLookoutServiceServer) AssignIncident(context.Context, *AssignIncidentRequest) (*IncidentMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignIncident not implemented")
}
func (UnimplementedLookoutServiceServer) ResolveIncident(context.Context, *ResolveIncidentRequest) (*IncidentMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIncident not implemented")
}
func (UnimplementedLookoutServiceServer) AddIncidentNote(context.Context, *AddIncidentNoteRequest) (*IncidentMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIncidentNote not implemented")
}
func (UnimplementedLookoutServiceServer) AttachInvestigation(context.Context, *AttachInvestigationRequest) (*IncidentMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachInvestigation not implemented")
}
func (UnimplementedLookoutServiceServer) mustEmbedUnimplementedLookoutServiceServer() {}
func (UnimplementedLookoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeLookoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LookoutServiceServer will
// result in compilation errors.
type UnsafeLookoutServiceServer interface {
	mustEmbedUnimplementedLookoutServiceServer()
}

func RegisterLookoutServiceServer(s grpc.ServiceRegistrar, srv LookoutServiceServer) {
	// If the following call panics, it indicates UnimplementedLookoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LookoutService_ServiceDesc, srv)
}

func _LookoutService_ListIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).ListIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_ListIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).ListIncidents(ctx, req.(*ListIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookoutService_GetIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).GetIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_GetIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).GetIncident(ctx, req.(*GetIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookoutService_AcknowledgeIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).AcknowledgeIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_AcknowledgeIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).AcknowledgeIncident(ctx, req.(*AcknowledgeIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookoutService_AssignIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).AssignIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_AssignIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).AssignIncident(ctx, req.(*AssignIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookoutService_ResolveIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).ResolveIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_ResolveIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).ResolveIncident(ctx, req.(*ResolveIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookoutService_AddIncidentNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIncidentNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).AddIncidentNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_AddIncidentNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).AddIncidentNote(ctx, req.(*AddIncidentNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LookoutService_AttachInvestigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachInvestigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookoutServiceServer).AttachInvestigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LookoutService_AttachInvestigation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookoutServiceServer).AttachInvestigation(ctx, req.(*AttachInvestigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LookoutService_ServiceDesc is the grpc.ServiceDesc for LookoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LookoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lookout.LookoutService",
	HandlerType: (*LookoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIncidents",
			Handler:    _LookoutService_ListIncidents_Handler,
		},
		{
			MethodName: "GetIncident",
			Handler:    _LookoutService_GetIncident_Handler,
		},
		{
			MethodName: "AcknowledgeIncident",
			Handler:    _LookoutService_AcknowledgeIncident_Handler,
		},
		{
			MethodName: "AssignIncident",
			Handler:    _LookoutService_AssignIncident_Handler,
		},
		{
			MethodName: "ResolveIncident",
			Handler:    _LookoutService_ResolveIncident_Handler,
		},
		{
			MethodName: "AddIncidentNote",
			Handler:    _LookoutService_AddIncidentNote_Handler,
		},
		{
			MethodName: "AttachInvestigation",
			Handler:    _LookoutService_AttachInvestigation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lookout.proto",
}
