# All fields available on DVRRequest type
fragment DVRRequestFields on DVRRequest {
  id
  dvrHash
  internalName
  title
  createdAt
  updatedAt
  expiresAt
  storageNodeId
  status
  startedAt
  endedAt
  durationSeconds
  sizeBytes
  manifestPath
  errorMessage
  storageLocation
  isFrozen
  frozenAt
  s3Url
}
