# All fields available on StreamTrack type
fragment StreamTrackFields on StreamTrack {
  trackName
  trackType
  codec
  bitrateKbps
  bitrateBps
  buffer
  jitter
  width
  height
  fps
  resolution
  hasBFrames
  channels
  sampleRate
}
