fragment MediaPlacementErrorFields on MediaPlacementError {
  code
  message
  fields {
    path
    groupId
    message
  }
  currentRevision
  conflictParentRevision: parentRevision
  retryAfterSeconds
}
