fragment NodeListFields on InfrastructureNode {
  id
  nodeId
  nodeName
  clusterId
  nodeType
  region
  externalIp
  cpuCores
  memoryGb
  diskGb
  lastHeartbeat
  tags
  liveState {
    cpuPercent
    ramUsedBytes
    ramTotalBytes
    isHealthy
    activeStreams
    updatedAt
    diskUsedBytes
    diskTotalBytes
    location
  }
}
