---
- name: Mistserver | install (linux)
  ansible.builtin.import_tasks: install-linux.yml
  when: ansible_facts.os_family != 'Darwin'

- name: Mistserver | install (darwin)
  ansible.builtin.import_tasks: install-darwin.yml
  when: ansible_facts.os_family == 'Darwin'
