---
# Main playbook for FrameWorks infrastructure

- name: Base system configuration
  hosts: all
  become: true
  roles:
    - common
    - monitoring

- name: Configure WireGuard mesh
  hosts: all
  become: true
  roles:
    - wireguard

- name: Deploy control plane services
  hosts: control
  become: true
  roles:
    - frameworks-api
  vars:
    frameworks_services:
      - name: commodore
        port: 9000
        replicas: 2
      - name: quartermaster
        port: 9008
        replicas: 2
      - name: purser
        port: 9007
        replicas: 2

- name: Deploy data plane services
  hosts: data
  become: true
  roles:
    - frameworks-api
  vars:
    frameworks_services:
      - name: periscope-query
        port: 9002
        replicas: 1
      - name: periscope-ingest
        port: 9004
        replicas: 2
      - name: decklog
        port: 9006
        replicas: 1

- name: Deploy media plane services
  hosts: media
  become: true
  roles:
    - frameworks-media
  vars:
    frameworks_services:
      - name: foghorn
        port: 9042
        replicas: 1
      - name: helmsman
        port: 9001
        replicas: 1 