// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package skipperdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const countReportsByTenant = `-- name: CountReportsByTenant :one
SELECT COUNT(*)
FROM skipper.skipper_reports
WHERE tenant_id = $1
`

func (q *Queries) CountReportsByTenant(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReportsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadReports = `-- name: CountUnreadReports :one
SELECT COUNT(*)
FROM skipper.skipper_reports
WHERE tenant_id = $1
  AND read_at IS NULL
`

func (q *Queries) CountUnreadReports(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadReports, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, tenant_id, trigger, summary,
       COALESCE(metrics_reviewed, 'null') AS metrics_reviewed,
       root_cause, COALESCE(recommendations, 'null') AS recommendations,
       created_at, read_at
FROM skipper.skipper_reports
WHERE id = $1
  AND tenant_id = $2
`

type GetReportByIDParams struct {
	ID       string `db:"id" json:"id"`
	TenantID string `db:"tenant_id" json:"tenant_id"`
}

type GetReportByIDRow struct {
	ID              string          `db:"id" json:"id"`
	TenantID        string          `db:"tenant_id" json:"tenant_id"`
	Trigger         string          `db:"trigger" json:"trigger"`
	Summary         string          `db:"summary" json:"summary"`
	MetricsReviewed json.RawMessage `db:"metrics_reviewed" json:"metrics_reviewed"`
	RootCause       string          `db:"root_cause" json:"root_cause"`
	Recommendations json.RawMessage `db:"recommendations" json:"recommendations"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	ReadAt          sql.NullTime    `db:"read_at" json:"read_at"`
}

func (q *Queries) GetReportByID(ctx context.Context, arg GetReportByIDParams) (GetReportByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, arg.ID, arg.TenantID)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Trigger,
		&i.Summary,
		&i.MetricsReviewed,
		&i.RootCause,
		&i.Recommendations,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listReportsByTenant = `-- name: ListReportsByTenant :many
SELECT id, tenant_id, trigger, summary,
       COALESCE(metrics_reviewed, 'null') AS metrics_reviewed,
       root_cause, COALESCE(recommendations, 'null') AS recommendations,
       created_at, read_at
FROM skipper.skipper_reports
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReportsByTenantParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	RowLimit int32  `db:"row_limit" json:"row_limit"`
}

type ListReportsByTenantRow struct {
	ID              string          `db:"id" json:"id"`
	TenantID        string          `db:"tenant_id" json:"tenant_id"`
	Trigger         string          `db:"trigger" json:"trigger"`
	Summary         string          `db:"summary" json:"summary"`
	MetricsReviewed json.RawMessage `db:"metrics_reviewed" json:"metrics_reviewed"`
	RootCause       string          `db:"root_cause" json:"root_cause"`
	Recommendations json.RawMessage `db:"recommendations" json:"recommendations"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	ReadAt          sql.NullTime    `db:"read_at" json:"read_at"`
}

func (q *Queries) ListReportsByTenant(ctx context.Context, arg ListReportsByTenantParams) ([]ListReportsByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByTenant, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsByTenantRow{}
	for rows.Next() {
		var i ListReportsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Trigger,
			&i.Summary,
			&i.MetricsReviewed,
			&i.RootCause,
			&i.Recommendations,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByTenantPaginated = `-- name: ListReportsByTenantPaginated :many
SELECT id, tenant_id, trigger, summary,
       COALESCE(metrics_reviewed, 'null') AS metrics_reviewed,
       root_cause, COALESCE(recommendations, 'null') AS recommendations,
       created_at, read_at
FROM skipper.skipper_reports
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListReportsByTenantPaginatedParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	RowOffset int32  `db:"row_offset" json:"row_offset"`
	RowLimit  int32  `db:"row_limit" json:"row_limit"`
}

type ListReportsByTenantPaginatedRow struct {
	ID              string          `db:"id" json:"id"`
	TenantID        string          `db:"tenant_id" json:"tenant_id"`
	Trigger         string          `db:"trigger" json:"trigger"`
	Summary         string          `db:"summary" json:"summary"`
	MetricsReviewed json.RawMessage `db:"metrics_reviewed" json:"metrics_reviewed"`
	RootCause       string          `db:"root_cause" json:"root_cause"`
	Recommendations json.RawMessage `db:"recommendations" json:"recommendations"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	ReadAt          sql.NullTime    `db:"read_at" json:"read_at"`
}

func (q *Queries) ListReportsByTenantPaginated(ctx context.Context, arg ListReportsByTenantPaginatedParams) ([]ListReportsByTenantPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByTenantPaginated, arg.TenantID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsByTenantPaginatedRow{}
	for rows.Next() {
		var i ListReportsByTenantPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Trigger,
			&i.Summary,
			&i.MetricsReviewed,
			&i.RootCause,
			&i.Recommendations,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllReportsRead = `-- name: MarkAllReportsRead :execrows
UPDATE skipper.skipper_reports
SET read_at = NOW()
WHERE tenant_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllReportsRead(ctx context.Context, tenantID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllReportsRead, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markReportsRead = `-- name: MarkReportsRead :execrows
UPDATE skipper.skipper_reports
SET read_at = NOW()
WHERE tenant_id = $1
  AND id = ANY($2::text[])
  AND read_at IS NULL
`

type MarkReportsReadParams struct {
	TenantID string   `db:"tenant_id" json:"tenant_id"`
	Ids      []string `db:"ids" json:"ids"`
}

func (q *Queries) MarkReportsRead(ctx context.Context, arg MarkReportsReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReportsRead, arg.TenantID, pq.Array(arg.Ids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveReport = `-- name: SaveReport :one
INSERT INTO skipper.skipper_reports (
    id, tenant_id, trigger, summary, metrics_reviewed,
    root_cause, recommendations, created_at
)
VALUES (
    $1, $2, $3::text,
    $4::text, $5::text::jsonb,
    $6::text, $7::text::jsonb, NOW()
)
RETURNING created_at
`

type SaveReportParams struct {
	ID              string `db:"id" json:"id"`
	TenantID        string `db:"tenant_id" json:"tenant_id"`
	Trigger         string `db:"trigger" json:"trigger"`
	Summary         string `db:"summary" json:"summary"`
	MetricsReviewed string `db:"metrics_reviewed" json:"metrics_reviewed"`
	RootCause       string `db:"root_cause" json:"root_cause"`
	Recommendations string `db:"recommendations" json:"recommendations"`
}

func (q *Queries) SaveReport(ctx context.Context, arg SaveReportParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, saveReport,
		arg.ID,
		arg.TenantID,
		arg.Trigger,
		arg.Summary,
		arg.MetricsReviewed,
		arg.RootCause,
		arg.Recommendations,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}
