from ..._forward import OpenEnum


class IngestMode(OpenEnum):
    PUSH = "PUSH"
    PULL = "PULL"
    MANAGED = "MANAGED"


class SourceLocationMode(OpenEnum):
    ANY = "ANY"
    RESTRICTED = "RESTRICTED"
    CUSTOM = "CUSTOM"


class ClipCreationMode(OpenEnum):
    ABSOLUTE = "ABSOLUTE"
    RELATIVE = "RELATIVE"
    DURATION = "DURATION"
    CLIP_NOW = "CLIP_NOW"


class DVRChapterMode(OpenEnum):
    WINDOW_SIZED = "WINDOW_SIZED"
    FIXED_INTERVAL = "FIXED_INTERVAL"
    NONE = "NONE"


class MonitoringToggle(OpenEnum):
    INHERIT = "INHERIT"
    ON = "ON"
    OFF = "OFF"


class DVRChapterState(OpenEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    FINALIZING = "FINALIZING"
    FINALIZED = "FINALIZED"
    FROZEN = "FROZEN"
    RECLAIMED = "RECLAIMED"
    FAILED_SOURCE_MISSING = "FAILED_SOURCE_MISSING"
    FAILED_PERMANENT = "FAILED_PERMANENT"


class VodAssetStatus(OpenEnum):
    UPLOADING = "UPLOADING"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"
    DELETED = "DELETED"
    EXPIRED = "EXPIRED"


class StorageArtifactKind(OpenEnum):
    VOD = "VOD"
    DVR = "DVR"
    CHAPTER = "CHAPTER"
    CLIP = "CLIP"


class StorageArtifactSortField(OpenEnum):
    CREATED_AT = "CREATED_AT"
    TITLE = "TITLE"
    KIND = "KIND"
    SIZE_BYTES = "SIZE_BYTES"
    EXPIRES_AT = "EXPIRES_AT"


class SortDirection(OpenEnum):
    ASC = "ASC"
    DESC = "DESC"


class StreamStatus(OpenEnum):
    OFFLINE = "OFFLINE"
    LIVE = "LIVE"
    RECORDING = "RECORDING"
    ENDED = "ENDED"


class MediaViewerProtocol(OpenEnum):
    WEBRTC = "WEBRTC"
    WHEP = "WHEP"
    HLS = "HLS"
    DASH = "DASH"
    HLS_CMAF = "HLS_CMAF"
    MEWS = "MEWS"
    MEWS_WEBM = "MEWS_WEBM"
    MP4 = "MP4"
    WEBM = "WEBM"
    MKV = "MKV"
    TS = "TS"
    AAC = "AAC"
    H264 = "H264"
    H264_WS = "H264_WS"
    RAW_WS = "RAW_WS"
    JSON_WS = "JSON_WS"
    FLV = "FLV"
    HDS = "HDS"
    SMOOTHSTREAMING = "SMOOTHSTREAMING"
    SDP = "SDP"
    MIST_HTML = "MIST_HTML"
    RTMP = "RTMP"
    RTSP = "RTSP"
    SRT = "SRT"
    DTSC = "DTSC"


class MediaIngestProtocol(OpenEnum):
    WHIP = "WHIP"
    RTMP = "RTMP"
    SRT = "SRT"


class IngestEndpointKind(OpenEnum):
    INGEST_ENDPOINT_KIND_UNSPECIFIED = "INGEST_ENDPOINT_KIND_UNSPECIFIED"
    INGEST_ENDPOINT_KIND_TENANT_ALIAS = "INGEST_ENDPOINT_KIND_TENANT_ALIAS"
    INGEST_ENDPOINT_KIND_ROOT_POOL = "INGEST_ENDPOINT_KIND_ROOT_POOL"
    INGEST_ENDPOINT_KIND_CLUSTER_POOL = "INGEST_ENDPOINT_KIND_CLUSTER_POOL"
    INGEST_ENDPOINT_KIND_NODE_SPECIFIC = "INGEST_ENDPOINT_KIND_NODE_SPECIFIC"


class SigningKeyAlgorithm(OpenEnum):
    ES256 = "ES256"


class SigningKeyStatus(OpenEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class PlaybackPolicyType(OpenEnum):
    PUBLIC = "PUBLIC"
    JWT = "JWT"
    WEBHOOK = "WEBHOOK"


class RetentionSource(OpenEnum):
    TENANT_DEFAULT = "TENANT_DEFAULT"
    PER_STREAM_OVERRIDE = "PER_STREAM_OVERRIDE"
    PER_ASSET_OVERRIDE = "PER_ASSET_OVERRIDE"
    TIER_ENTITLEMENT = "TIER_ENTITLEMENT"


class EventArtifactKind(OpenEnum):
    ARTIFACT_KIND_UNSPECIFIED = "ARTIFACT_KIND_UNSPECIFIED"
    ARTIFACT_KIND_CLIP = "ARTIFACT_KIND_CLIP"
    ARTIFACT_KIND_RECORDING = "ARTIFACT_KIND_RECORDING"
    ARTIFACT_KIND_UPLOAD = "ARTIFACT_KIND_UPLOAD"


class EventCustomDomainFailureReason(OpenEnum):
    CUSTOM_DOMAIN_FAILURE_REASON_UNSPECIFIED = (
        "CUSTOM_DOMAIN_FAILURE_REASON_UNSPECIFIED"
    )
    CUSTOM_DOMAIN_FAILURE_REASON_VERIFICATION_EXPIRED = (
        "CUSTOM_DOMAIN_FAILURE_REASON_VERIFICATION_EXPIRED"
    )
    CUSTOM_DOMAIN_FAILURE_REASON_CERTIFICATE_FAILED = (
        "CUSTOM_DOMAIN_FAILURE_REASON_CERTIFICATE_FAILED"
    )


class EventIngestProtocol(OpenEnum):
    INGEST_PROTOCOL_UNSPECIFIED = "INGEST_PROTOCOL_UNSPECIFIED"
    INGEST_PROTOCOL_RTMP = "INGEST_PROTOCOL_RTMP"
    INGEST_PROTOCOL_SRT = "INGEST_PROTOCOL_SRT"
    INGEST_PROTOCOL_WHIP = "INGEST_PROTOCOL_WHIP"
    INGEST_PROTOCOL_PULL = "INGEST_PROTOCOL_PULL"


class EventMediaFailureReason(OpenEnum):
    MEDIA_FAILURE_REASON_UNSPECIFIED = "MEDIA_FAILURE_REASON_UNSPECIFIED"
    MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE = "MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE"
    MEDIA_FAILURE_REASON_PROCESSING_FAILED = "MEDIA_FAILURE_REASON_PROCESSING_FAILED"
    MEDIA_FAILURE_REASON_STORAGE_FAILED = "MEDIA_FAILURE_REASON_STORAGE_FAILED"
    MEDIA_FAILURE_REASON_INVALID_INPUT = "MEDIA_FAILURE_REASON_INVALID_INPUT"
    MEDIA_FAILURE_REASON_QUOTA_EXCEEDED = "MEDIA_FAILURE_REASON_QUOTA_EXCEEDED"
    MEDIA_FAILURE_REASON_TIMED_OUT = "MEDIA_FAILURE_REASON_TIMED_OUT"


class EventMultistreamStatus(OpenEnum):
    MULTISTREAM_STATUS_UNSPECIFIED = "MULTISTREAM_STATUS_UNSPECIFIED"
    MULTISTREAM_STATUS_IDLE = "MULTISTREAM_STATUS_IDLE"
    MULTISTREAM_STATUS_PENDING = "MULTISTREAM_STATUS_PENDING"
    MULTISTREAM_STATUS_PUSHING = "MULTISTREAM_STATUS_PUSHING"
    MULTISTREAM_STATUS_RETRYING = "MULTISTREAM_STATUS_RETRYING"
    MULTISTREAM_STATUS_STOPPING = "MULTISTREAM_STATUS_STOPPING"
    MULTISTREAM_STATUS_FAILED = "MULTISTREAM_STATUS_FAILED"


class EventPaymentFailureReason(OpenEnum):
    PAYMENT_FAILURE_REASON_UNSPECIFIED = "PAYMENT_FAILURE_REASON_UNSPECIFIED"
    PAYMENT_FAILURE_REASON_DECLINED = "PAYMENT_FAILURE_REASON_DECLINED"
    PAYMENT_FAILURE_REASON_INSUFFICIENT_FUNDS = (
        "PAYMENT_FAILURE_REASON_INSUFFICIENT_FUNDS"
    )
    PAYMENT_FAILURE_REASON_EXPIRED_METHOD = "PAYMENT_FAILURE_REASON_EXPIRED_METHOD"
    PAYMENT_FAILURE_REASON_AUTHENTICATION_REQUIRED = (
        "PAYMENT_FAILURE_REASON_AUTHENTICATION_REQUIRED"
    )
    PAYMENT_FAILURE_REASON_PROCESSING_ERROR = "PAYMENT_FAILURE_REASON_PROCESSING_ERROR"


class EventSuspensionReason(OpenEnum):
    SUSPENSION_REASON_UNSPECIFIED = "SUSPENSION_REASON_UNSPECIFIED"
    SUSPENSION_REASON_BALANCE_EXHAUSTED = "SUSPENSION_REASON_BALANCE_EXHAUSTED"
    SUSPENSION_REASON_PAYMENT_OVERDUE = "SUSPENSION_REASON_PAYMENT_OVERDUE"
    SUSPENSION_REASON_POLICY = "SUSPENSION_REASON_POLICY"
