from ..._forward import OpenEnum


class BufferState(OpenEnum):
    FULL = "FULL"
    EMPTY = "EMPTY"
    DRY = "DRY"
    RECOVER = "RECOVER"


class CardPaymentProvider(OpenEnum):
    STRIPE = "STRIPE"
    MOLLIE = "MOLLIE"


class ClipCreationMode(OpenEnum):
    ABSOLUTE = "ABSOLUTE"
    RELATIVE = "RELATIVE"
    DURATION = "DURATION"
    CLIP_NOW = "CLIP_NOW"


class ClusterPricingModel(OpenEnum):
    FREE_UNMETERED = "FREE_UNMETERED"
    METERED = "METERED"
    MONTHLY = "MONTHLY"
    TIER_INHERIT = "TIER_INHERIT"
    CUSTOM = "CUSTOM"


class ClusterSubscriptionStatus(OpenEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REJECTED = "REJECTED"


class ClusterVisibility(OpenEnum):
    PUBLIC = "PUBLIC"
    UNLISTED = "UNLISTED"
    PRIVATE = "PRIVATE"


class ConversationStatus(OpenEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    PENDING = "PENDING"


class CryptoAsset(OpenEnum):
    ETH = "ETH"
    USDC = "USDC"
    LPT = "LPT"


class DVRChapterMode(OpenEnum):
    WINDOW_SIZED = "WINDOW_SIZED"
    FIXED_INTERVAL = "FIXED_INTERVAL"
    NONE = "NONE"


class DVRChapterState(OpenEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    FINALIZING = "FINALIZING"
    FINALIZED = "FINALIZED"
    FROZEN = "FROZEN"
    RECLAIMED = "RECLAIMED"
    FAILED_SOURCE_MISSING = "FAILED_SOURCE_MISSING"
    FAILED_PERMANENT = "FAILED_PERMANENT"


class EventArtifactKind(OpenEnum):
    ARTIFACT_KIND_UNSPECIFIED = "ARTIFACT_KIND_UNSPECIFIED"
    ARTIFACT_KIND_CLIP = "ARTIFACT_KIND_CLIP"
    ARTIFACT_KIND_RECORDING = "ARTIFACT_KIND_RECORDING"
    ARTIFACT_KIND_UPLOAD = "ARTIFACT_KIND_UPLOAD"


class EventCustomDomainFailureReason(OpenEnum):
    CUSTOM_DOMAIN_FAILURE_REASON_UNSPECIFIED = (
        "CUSTOM_DOMAIN_FAILURE_REASON_UNSPECIFIED"
    )
    CUSTOM_DOMAIN_FAILURE_REASON_VERIFICATION_EXPIRED = (
        "CUSTOM_DOMAIN_FAILURE_REASON_VERIFICATION_EXPIRED"
    )
    CUSTOM_DOMAIN_FAILURE_REASON_CERTIFICATE_FAILED = (
        "CUSTOM_DOMAIN_FAILURE_REASON_CERTIFICATE_FAILED"
    )


class EventIngestProtocol(OpenEnum):
    INGEST_PROTOCOL_UNSPECIFIED = "INGEST_PROTOCOL_UNSPECIFIED"
    INGEST_PROTOCOL_RTMP = "INGEST_PROTOCOL_RTMP"
    INGEST_PROTOCOL_SRT = "INGEST_PROTOCOL_SRT"
    INGEST_PROTOCOL_WHIP = "INGEST_PROTOCOL_WHIP"
    INGEST_PROTOCOL_PULL = "INGEST_PROTOCOL_PULL"


class EventMediaFailureReason(OpenEnum):
    MEDIA_FAILURE_REASON_UNSPECIFIED = "MEDIA_FAILURE_REASON_UNSPECIFIED"
    MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE = "MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE"
    MEDIA_FAILURE_REASON_PROCESSING_FAILED = "MEDIA_FAILURE_REASON_PROCESSING_FAILED"
    MEDIA_FAILURE_REASON_STORAGE_FAILED = "MEDIA_FAILURE_REASON_STORAGE_FAILED"
    MEDIA_FAILURE_REASON_INVALID_INPUT = "MEDIA_FAILURE_REASON_INVALID_INPUT"
    MEDIA_FAILURE_REASON_QUOTA_EXCEEDED = "MEDIA_FAILURE_REASON_QUOTA_EXCEEDED"
    MEDIA_FAILURE_REASON_TIMED_OUT = "MEDIA_FAILURE_REASON_TIMED_OUT"


class EventMultistreamStatus(OpenEnum):
    MULTISTREAM_STATUS_UNSPECIFIED = "MULTISTREAM_STATUS_UNSPECIFIED"
    MULTISTREAM_STATUS_IDLE = "MULTISTREAM_STATUS_IDLE"
    MULTISTREAM_STATUS_PENDING = "MULTISTREAM_STATUS_PENDING"
    MULTISTREAM_STATUS_PUSHING = "MULTISTREAM_STATUS_PUSHING"
    MULTISTREAM_STATUS_RETRYING = "MULTISTREAM_STATUS_RETRYING"
    MULTISTREAM_STATUS_STOPPING = "MULTISTREAM_STATUS_STOPPING"
    MULTISTREAM_STATUS_FAILED = "MULTISTREAM_STATUS_FAILED"


class EventPaymentFailureReason(OpenEnum):
    PAYMENT_FAILURE_REASON_UNSPECIFIED = "PAYMENT_FAILURE_REASON_UNSPECIFIED"
    PAYMENT_FAILURE_REASON_DECLINED = "PAYMENT_FAILURE_REASON_DECLINED"
    PAYMENT_FAILURE_REASON_INSUFFICIENT_FUNDS = (
        "PAYMENT_FAILURE_REASON_INSUFFICIENT_FUNDS"
    )
    PAYMENT_FAILURE_REASON_EXPIRED_METHOD = "PAYMENT_FAILURE_REASON_EXPIRED_METHOD"
    PAYMENT_FAILURE_REASON_AUTHENTICATION_REQUIRED = (
        "PAYMENT_FAILURE_REASON_AUTHENTICATION_REQUIRED"
    )
    PAYMENT_FAILURE_REASON_PROCESSING_ERROR = "PAYMENT_FAILURE_REASON_PROCESSING_ERROR"


class EventSuspensionReason(OpenEnum):
    SUSPENSION_REASON_UNSPECIFIED = "SUSPENSION_REASON_UNSPECIFIED"
    SUSPENSION_REASON_BALANCE_EXHAUSTED = "SUSPENSION_REASON_BALANCE_EXHAUSTED"
    SUSPENSION_REASON_PAYMENT_OVERDUE = "SUSPENSION_REASON_PAYMENT_OVERDUE"
    SUSPENSION_REASON_POLICY = "SUSPENSION_REASON_POLICY"


class IncidentEventKind(OpenEnum):
    ALERT_FIRING = "ALERT_FIRING"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ASSIGNED = "ASSIGNED"
    NOTE = "NOTE"
    RESOLVED = "RESOLVED"
    INVESTIGATION_ATTACHED = "INVESTIGATION_ATTACHED"
    NOTIFIED = "NOTIFIED"
    SCOPE_CHANGED = "SCOPE_CHANGED"


class IncidentResolution(OpenEnum):
    AUTO = "AUTO"
    MANUAL = "MANUAL"


class IncidentScope(OpenEnum):
    PLATFORM = "PLATFORM"
    TENANT = "TENANT"


class IncidentStatus(OpenEnum):
    FIRING = "FIRING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class IngestEndpointKind(OpenEnum):
    INGEST_ENDPOINT_KIND_UNSPECIFIED = "INGEST_ENDPOINT_KIND_UNSPECIFIED"
    INGEST_ENDPOINT_KIND_TENANT_ALIAS = "INGEST_ENDPOINT_KIND_TENANT_ALIAS"
    INGEST_ENDPOINT_KIND_ROOT_POOL = "INGEST_ENDPOINT_KIND_ROOT_POOL"
    INGEST_ENDPOINT_KIND_CLUSTER_POOL = "INGEST_ENDPOINT_KIND_CLUSTER_POOL"
    INGEST_ENDPOINT_KIND_NODE_SPECIFIC = "INGEST_ENDPOINT_KIND_NODE_SPECIFIC"


class IngestMode(OpenEnum):
    PUSH = "PUSH"
    PULL = "PULL"
    MANAGED = "MANAGED"


class InstanceStatus(OpenEnum):
    RUNNING = "RUNNING"
    STARTING = "STARTING"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"


class InvoiceStatus(OpenEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    FAILED = "FAILED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    CANCELLED = "CANCELLED"


class MediaIngestProtocol(OpenEnum):
    WHIP = "WHIP"
    RTMP = "RTMP"
    SRT = "SRT"


class MediaPlacementCharging(OpenEnum):
    RATED = "RATED"
    PERMANENTLY_FREE = "PERMANENTLY_FREE"


class MediaPlacementClass(OpenEnum):
    PLATFORM_OFFICIAL = "PLATFORM_OFFICIAL"
    TENANT_PRIVATE = "TENANT_PRIVATE"
    THIRD_PARTY_MARKETPLACE = "THIRD_PARTY_MARKETPLACE"


class MediaPlacementErrorCode(OpenEnum):
    INVALID_INPUT = "INVALID_INPUT"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    STALE_REVIEW = "STALE_REVIEW"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    UNSUPPORTED = "UNSUPPORTED"
    UNAVAILABLE = "UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"


class MediaPlacementOptionKind(OpenEnum):
    CLUSTER = "CLUSTER"
    OPERATOR = "OPERATOR"
    REGION = "REGION"
    NODE = "NODE"


class MediaPlacementOrder(OpenEnum):
    DISTANCE = "DISTANCE"
    PRICE = "PRICE"


class MediaPlacementRolloutStatus(OpenEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    PENDING = "PENDING"
    EFFECTIVE = "EFFECTIVE"
    BLOCKED = "BLOCKED"
    SUPERSEDED = "SUPERSEDED"


class MediaPlacementScopeKind(OpenEnum):
    TENANT = "TENANT"
    STREAM = "STREAM"


class MediaPlacementSpillover(OpenEnum):
    NEVER = "NEVER"
    CAPACITY_ONLY = "CAPACITY_ONLY"
    GEO_HOLE = "GEO_HOLE"
    CAPACITY_OR_GEO_HOLE = "CAPACITY_OR_GEO_HOLE"


class MediaPlacementUpdateKind(OpenEnum):
    SET = "SET"
    CLEAR = "CLEAR"


class MediaPlacementVerb(OpenEnum):
    INGEST = "INGEST"
    SERVE = "SERVE"


class MediaPlacementWarningSeverity(OpenEnum):
    INFO = "INFO"
    WARNING = "WARNING"


class MediaRetentionTarget(OpenEnum):
    DVR = "DVR"
    CLIP = "CLIP"
    VOD = "VOD"


class MediaViewerProtocol(OpenEnum):
    WEBRTC = "WEBRTC"
    WHEP = "WHEP"
    HLS = "HLS"
    DASH = "DASH"
    HLS_CMAF = "HLS_CMAF"
    MEWS = "MEWS"
    MEWS_WEBM = "MEWS_WEBM"
    MP4 = "MP4"
    WEBM = "WEBM"
    MKV = "MKV"
    TS = "TS"
    AAC = "AAC"
    H264 = "H264"
    H264_WS = "H264_WS"
    RAW_WS = "RAW_WS"
    JSON_WS = "JSON_WS"
    FLV = "FLV"
    HDS = "HDS"
    SMOOTHSTREAMING = "SMOOTHSTREAMING"
    SDP = "SDP"
    MIST_HTML = "MIST_HTML"
    RTMP = "RTMP"
    RTSP = "RTSP"
    SRT = "SRT"
    DTSC = "DTSC"


class MessageSender(OpenEnum):
    USER = "USER"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class MonitoringToggle(OpenEnum):
    INHERIT = "INHERIT"
    ON = "ON"
    OFF = "OFF"


class NodeOperationalMode(OpenEnum):
    NORMAL = "NORMAL"
    DRAINING = "DRAINING"
    MAINTENANCE = "MAINTENANCE"


class NodeStatus(OpenEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"


class PaymentMethod(OpenEnum):
    CARD = "CARD"
    CRYPTO_ETH = "CRYPTO_ETH"
    CRYPTO_USDC = "CRYPTO_USDC"


class PaymentStatus(OpenEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"


class PlaybackPolicyType(OpenEnum):
    PUBLIC = "PUBLIC"
    JWT = "JWT"
    WEBHOOK = "WEBHOOK"


class RetentionSource(OpenEnum):
    TENANT_DEFAULT = "TENANT_DEFAULT"
    PER_STREAM_OVERRIDE = "PER_STREAM_OVERRIDE"
    PER_ASSET_OVERRIDE = "PER_ASSET_OVERRIDE"
    TIER_ENTITLEMENT = "TIER_ENTITLEMENT"


class SigningKeyAlgorithm(OpenEnum):
    ES256 = "ES256"


class SigningKeyStatus(OpenEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class SkipperMode(OpenEnum):
    DEFAULT = "DEFAULT"
    DOCS = "DOCS"


class SortDirection(OpenEnum):
    ASC = "ASC"
    DESC = "DESC"


class SortOrder(OpenEnum):
    ASC = "ASC"
    DESC = "DESC"


class SourceLocationMode(OpenEnum):
    ANY = "ANY"
    RESTRICTED = "RESTRICTED"
    CUSTOM = "CUSTOM"


class StorageArtifactKind(OpenEnum):
    VOD = "VOD"
    DVR = "DVR"
    CHAPTER = "CHAPTER"
    CLIP = "CLIP"


class StorageArtifactSortField(OpenEnum):
    CREATED_AT = "CREATED_AT"
    TITLE = "TITLE"
    KIND = "KIND"
    SIZE_BYTES = "SIZE_BYTES"
    EXPIRES_AT = "EXPIRES_AT"


class StreamEventSource(OpenEnum):
    HISTORICAL = "HISTORICAL"
    LIVE = "LIVE"


class StreamEventType(OpenEnum):
    STREAM_LIFECYCLE_UPDATE = "STREAM_LIFECYCLE_UPDATE"
    STREAM_START = "STREAM_START"
    STREAM_END = "STREAM_END"
    BUFFER_UPDATE = "BUFFER_UPDATE"
    TRACK_LIST_UPDATE = "TRACK_LIST_UPDATE"
    PLAY_REWRITE = "PLAY_REWRITE"
    STREAM_SOURCE = "STREAM_SOURCE"


class StreamStatus(OpenEnum):
    OFFLINE = "OFFLINE"
    LIVE = "LIVE"
    RECORDING = "RECORDING"
    ENDED = "ENDED"


class StreamSummarySortField(OpenEnum):
    EGRESS_GB = "EGRESS_GB"
    UNIQUE_VIEWERS = "UNIQUE_VIEWERS"
    TOTAL_VIEWS = "TOTAL_VIEWS"
    VIEWER_HOURS = "VIEWER_HOURS"


class ValidationStatus(OpenEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    ERROR = "ERROR"


class VodAssetStatus(OpenEnum):
    UPLOADING = "UPLOADING"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"
    DELETED = "DELETED"
    EXPIRED = "EXPIRED"


class WebhookDeliveryKind(OpenEnum):
    EVENT = "EVENT"
    TEST = "TEST"


class WebhookDeliveryStatus(OpenEnum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class WebhookEndpointDisabledReason(OpenEnum):
    USER = "USER"
    FAILING = "FAILING"


class WebhookEndpointStatus(OpenEnum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
