---
- name: Restart redis
  listen: redis restart
  ansible.builtin.systemd:
    name: "{{ redis_service_name }}"
    state: restarted
  register: redis_restarted

- name: Reload redis
  listen: redis reload
  ansible.builtin.systemd:
    name: "{{ redis_service_name }}"
    state: reloaded
  when: redis_restarted is not defined
