// Code generated by scripts/registry from docs/platform-features.yaml. DO NOT EDIT.

// Package platformfeatures lists the product features this build ships.
package platformfeatures

// shipped holds the sorted slugs of shipped product-audience features,
// subitems included.
var shipped = []string{
	"agents-mcp",
	"billing",
	"clips",
	"cluster-invites",
	"cluster-subscription-requests",
	"developer-tokens",
	"dvr-recordings",
	"edge-auto-update",
	"edge-clusters",
	"enrollment-tokens",
	"federation-network",
	"graphql-playground",
	"incidents-and-alerts",
	"media-retention",
	"multistream-targets",
	"node-mode",
	"nodes",
	"outbound-webhooks",
	"playback",
	"playback-access-control",
	"player-sdks",
	"signing-keys",
	"stream-keys",
	"streamcrafter",
	"streams",
	"tenant-events",
	"viewer-protocol-selection",
	"viewer-routing",
	"vod",
}

// Shipped returns a copy of the sorted shipped product feature slugs.
func Shipped() []string {
	return append([]string(nil), shipped...)
}
