// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: events/public/v1/common.proto

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactKind int32

const (
	ArtifactKind_ARTIFACT_KIND_UNSPECIFIED ArtifactKind = 0
	ArtifactKind_ARTIFACT_KIND_CLIP        ArtifactKind = 1
	ArtifactKind_ARTIFACT_KIND_RECORDING   ArtifactKind = 2
	ArtifactKind_ARTIFACT_KIND_UPLOAD      ArtifactKind = 3
)

// Enum value maps for ArtifactKind.
var (
	ArtifactKind_name = map[int32]string{
		0: "ARTIFACT_KIND_UNSPECIFIED",
		1: "ARTIFACT_KIND_CLIP",
		2: "ARTIFACT_KIND_RECORDING",
		3: "ARTIFACT_KIND_UPLOAD",
	}
	ArtifactKind_value = map[string]int32{
		"ARTIFACT_KIND_UNSPECIFIED": 0,
		"ARTIFACT_KIND_CLIP":        1,
		"ARTIFACT_KIND_RECORDING":   2,
		"ARTIFACT_KIND_UPLOAD":      3,
	}
)

func (x ArtifactKind) Enum() *ArtifactKind {
	p := new(ArtifactKind)
	*p = x
	return p
}

func (x ArtifactKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactKind) Descriptor() protoreflect.EnumDescriptor {
	return file_events_public_v1_common_proto_enumTypes[0].Descriptor()
}

func (ArtifactKind) Type() protoreflect.EnumType {
	return &file_events_public_v1_common_proto_enumTypes[0]
}

func (x ArtifactKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactKind.Descriptor instead.
func (ArtifactKind) EnumDescriptor() ([]byte, []int) {
	return file_events_public_v1_common_proto_rawDescGZIP(), []int{0}
}

// MediaFailureReason is the coarse failure class shown to tenants. Detailed
// causes stay in internal logs and events.
type MediaFailureReason int32

const (
	MediaFailureReason_MEDIA_FAILURE_REASON_UNSPECIFIED        MediaFailureReason = 0
	MediaFailureReason_MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE MediaFailureReason = 1
	MediaFailureReason_MEDIA_FAILURE_REASON_PROCESSING_FAILED  MediaFailureReason = 2
	MediaFailureReason_MEDIA_FAILURE_REASON_STORAGE_FAILED     MediaFailureReason = 3
	MediaFailureReason_MEDIA_FAILURE_REASON_INVALID_INPUT      MediaFailureReason = 4
	MediaFailureReason_MEDIA_FAILURE_REASON_QUOTA_EXCEEDED     MediaFailureReason = 5
	MediaFailureReason_MEDIA_FAILURE_REASON_TIMED_OUT          MediaFailureReason = 6
)

// Enum value maps for MediaFailureReason.
var (
	MediaFailureReason_name = map[int32]string{
		0: "MEDIA_FAILURE_REASON_UNSPECIFIED",
		1: "MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE",
		2: "MEDIA_FAILURE_REASON_PROCESSING_FAILED",
		3: "MEDIA_FAILURE_REASON_STORAGE_FAILED",
		4: "MEDIA_FAILURE_REASON_INVALID_INPUT",
		5: "MEDIA_FAILURE_REASON_QUOTA_EXCEEDED",
		6: "MEDIA_FAILURE_REASON_TIMED_OUT",
	}
	MediaFailureReason_value = map[string]int32{
		"MEDIA_FAILURE_REASON_UNSPECIFIED":        0,
		"MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE": 1,
		"MEDIA_FAILURE_REASON_PROCESSING_FAILED":  2,
		"MEDIA_FAILURE_REASON_STORAGE_FAILED":     3,
		"MEDIA_FAILURE_REASON_INVALID_INPUT":      4,
		"MEDIA_FAILURE_REASON_QUOTA_EXCEEDED":     5,
		"MEDIA_FAILURE_REASON_TIMED_OUT":          6,
	}
)

func (x MediaFailureReason) Enum() *MediaFailureReason {
	p := new(MediaFailureReason)
	*p = x
	return p
}

func (x MediaFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_events_public_v1_common_proto_enumTypes[1].Descriptor()
}

func (MediaFailureReason) Type() protoreflect.EnumType {
	return &file_events_public_v1_common_proto_enumTypes[1]
}

func (x MediaFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaFailureReason.Descriptor instead.
func (MediaFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_events_public_v1_common_proto_rawDescGZIP(), []int{1}
}

// Artifact identifies a clip, recording, or upload by its public identifiers.
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// artifact_id is the public artifact hash used by the API.
	ArtifactId string       `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Kind       ArtifactKind `protobuf:"varint,2,opt,name=kind,proto3,enum=frameworks.events.public.v1.ArtifactKind" json:"kind,omitempty"`
	// stream_id is the public stream UUID; empty for uploads.
	StreamId      string `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	PlaybackId    string `protobuf:"bytes,4,opt,name=playback_id,json=playbackId,proto3" json:"playback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_events_public_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_events_public_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_events_public_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetKind() ArtifactKind {
	if x != nil {
		return x.Kind
	}
	return ArtifactKind_ARTIFACT_KIND_UNSPECIFIED
}

func (x *Artifact) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Artifact) GetPlaybackId() string {
	if x != nil {
		return x.PlaybackId
	}
	return ""
}

// Money is an amount in the minor unit of an ISO 4217 currency.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_events_public_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_events_public_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_events_public_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_events_public_v1_common_proto protoreflect.FileDescriptor

const file_events_public_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1devents/public/v1/common.proto\x12\x1bframeworks.events.public.v1\"\xa8\x01\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12=\n" +
	"\x04kind\x18\x02 \x01(\x0e2).frameworks.events.public.v1.ArtifactKindR\x04kind\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\x12\x1f\n" +
	"\vplayback_id\x18\x04 \x01(\tR\n" +
	"playbackId\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency*|\n" +
	"\fArtifactKind\x12\x1d\n" +
	"\x19ARTIFACT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ARTIFACT_KIND_CLIP\x10\x01\x12\x1b\n" +
	"\x17ARTIFACT_KIND_RECORDING\x10\x02\x12\x18\n" +
	"\x14ARTIFACT_KIND_UPLOAD\x10\x03*\xb1\x02\n" +
	"\x12MediaFailureReason\x12$\n" +
	" MEDIA_FAILURE_REASON_UNSPECIFIED\x10\x00\x12+\n" +
	"'MEDIA_FAILURE_REASON_SOURCE_UNAVAILABLE\x10\x01\x12*\n" +
	"&MEDIA_FAILURE_REASON_PROCESSING_FAILED\x10\x02\x12'\n" +
	"#MEDIA_FAILURE_REASON_STORAGE_FAILED\x10\x03\x12&\n" +
	"\"MEDIA_FAILURE_REASON_INVALID_INPUT\x10\x04\x12'\n" +
	"#MEDIA_FAILURE_REASON_QUOTA_EXCEEDED\x10\x05\x12\"\n" +
	"\x1eMEDIA_FAILURE_REASON_TIMED_OUT\x10\x06BMZKgithub.com/Livepeer-FrameWorks/monorepo/pkg/proto/events/public/v1;publicv1b\x06proto3"

var (
	file_events_public_v1_common_proto_rawDescOnce sync.Once
	file_events_public_v1_common_proto_rawDescData []byte
)

func file_events_public_v1_common_proto_rawDescGZIP() []byte {
	file_events_public_v1_common_proto_rawDescOnce.Do(func() {
		file_events_public_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_public_v1_common_proto_rawDesc), len(file_events_public_v1_common_proto_rawDesc)))
	})
	return file_events_public_v1_common_proto_rawDescData
}

var file_events_public_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_public_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_public_v1_common_proto_goTypes = []any{
	(ArtifactKind)(0),       // 0: frameworks.events.public.v1.ArtifactKind
	(MediaFailureReason)(0), // 1: frameworks.events.public.v1.MediaFailureReason
	(*Artifact)(nil),        // 2: frameworks.events.public.v1.Artifact
	(*Money)(nil),           // 3: frameworks.events.public.v1.Money
}
var file_events_public_v1_common_proto_depIdxs = []int32{
	0, // 0: frameworks.events.public.v1.Artifact.kind:type_name -> frameworks.events.public.v1.ArtifactKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_public_v1_common_proto_init() }
func file_events_public_v1_common_proto_init() {
	if File_events_public_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_public_v1_common_proto_rawDesc), len(file_events_public_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_public_v1_common_proto_goTypes,
		DependencyIndexes: file_events_public_v1_common_proto_depIdxs,
		EnumInfos:         file_events_public_v1_common_proto_enumTypes,
		MessageInfos:      file_events_public_v1_common_proto_msgTypes,
	}.Build()
	File_events_public_v1_common_proto = out.File
	file_events_public_v1_common_proto_goTypes = nil
	file_events_public_v1_common_proto_depIdxs = nil
}
