query GetArtifactStatesConnection(
  $internalName: String
  $contentType: String
  $stage: String
  $first: Int = 100
  $after: String
) {
  artifactStatesConnection(
    internalName: $internalName
    contentType: $contentType
    stage: $stage
    first: $first
    after: $after
  ) @paginate {
    edges {
      cursor
      node {
        requestId
        internalName
        contentType
        stage
        progressPercent
        errorMessage
        requestedAt
        startedAt
        completedAt
        clipStartUnix
        clipStopUnix
        segmentCount
        manifestPath
        filePath
        s3Url
        sizeBytes
        processingNodeId
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
