query GetAPITokensConnection(
  $first: Int = 50
  $after: String
) {
  developerTokensConnection(first: $first, after: $after) @paginate {
    edges {
      cursor
      node {
        id
        tokenName
        permissions
        status
        lastUsedAt
        expiresAt
        createdAt
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
