query GetClipEventsConnection(
  $internalName: String
  $stage: String
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
  $noCache: Boolean = false
) {
  clipEventsConnection(
    internalName: $internalName
    stage: $stage
    timeRange: $timeRange
    first: $first
    after: $after
    noCache: $noCache
  ) @paginate {
    edges {
      cursor
      node {
        timestamp
        internalName
        requestId
        stage
        contentType
        startUnix
        stopUnix
        ingestNodeId
        percent
        message
        filePath
        s3Url
        sizeBytes
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
