query GetClusters {
  clusters @list(name: "AllClusters") {
    id
    clusterId
    clusterName
    healthStatus
    createdAt
    isDefaultCluster
    isSubscribed
    nodes {
      id
      nodeName
      clusterId
      nodeType
      status
      region
      externalIp
      internalIp
      lastHeartbeat
      createdAt
      latitude
      longitude
    }
  }
}
