query GetLoadBalancingMetrics($timeRange: TimeRangeInput) {
  loadBalancingMetrics(timeRange: $timeRange) {
    timestamp
    stream
    selectedNode
    nodeId
    clientCountry
    clientLatitude
    clientLongitude
    clientBucket { h3Index resolution }
    nodeLatitude
    nodeLongitude
    nodeBucket { h3Index resolution }
    nodeName
    score
    status
    details
    routingDistance
    eventType
    source
  }
}
