query GetNode($id: ID!) {
  node(id: $id) {
    id
    nodeName
    clusterId
    nodeType
    status
    region
    externalIp
    internalIp
    wireguardIp
    availabilityZone
    cpuCores
    memoryGb
    diskGb
    lastHeartbeat
    createdAt
    latitude
    longitude
  }
}
