query GetNodes {
  nodes @list(name: "AllNodes") {
    id
    nodeName
    clusterId
    nodeType
    status
    region
    externalIp
    internalIp
    wireguardIp
    availabilityZone
    cpuCores
    memoryGb
    diskGb
    lastHeartbeat
    createdAt
    latitude
    longitude
  }
}
