query GetQualityTierDaily(
  $stream: String
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
) {
  qualityTierDailyConnection(
    stream: $stream
    timeRange: $timeRange
    first: $first
    after: $after
  ) {
    edges {
      cursor
      node {
        id
        day
        internalName
        tier1080pMinutes
        tier720pMinutes
        tier480pMinutes
        tierSdMinutes
        primaryTier
        codecH264Minutes
        codecH265Minutes
        avgBitrate
        avgFps
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
