query GetQualityChangesHourly(
  $stream: String
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
) {
  qualityChangesHourlyConnection(
    stream: $stream
    timeRange: $timeRange
    first: $first
    after: $after
  ) {
    edges {
      cursor
      node {
        id
        hour
        internalName
        totalChanges
        resolutionChanges
        codecChanges
        latestQuality
        latestCodec
        latestResolution
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
