query GetRebufferingEvents($stream: String!, $timeRange: TimeRangeInput) {
  rebufferingEvents(stream: $stream, timeRange: $timeRange) {
    timestamp
    stream
    nodeId
    bufferState
    previousState
    rebufferStart
    rebufferEnd
  }
}
