query GetStreamHealthMetrics(
  $stream: String!
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
  $noCache: Boolean = false
) {
  streamHealthMetricsConnection(
    stream: $stream
    timeRange: $timeRange
    first: $first
    after: $after
    noCache: $noCache
  ) @paginate {
    edges {
      cursor
      node {
        timestamp
        stream
        nodeId
        issuesDescription
        hasIssues
        bitrate
        fps
        width
        height
        codec
        qualityTier
        gopSize
        bufferState
        bufferHealth
        bufferSize
        audioChannels
        audioSampleRate
        audioCodec
        audioBitrate
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
