query GetStreamAnalytics($stream: String!, $timeRange: TimeRangeInput) {
  streamAnalytics(stream: $stream, timeRange: $timeRange) {
    id
    streamId
    internalName
    sessionStartTime
    sessionEndTime
    totalSessionDuration
    currentViewers
    peakViewers
    totalConnections
    bandwidthIn
    bandwidthOut
    totalBandwidthGb
    upbytes
    downbytes
    bitrateKbps
    resolution
    packetsSent
    packetsLost
    packetsRetrans
    firstMs
    lastMs
    trackCount
    inputs
    outputs
    nodeId
    nodeName
    latitude
    longitude
    location
    status
    lastUpdated
    createdAt
    currentBufferState
    currentIssues
    currentCodec
    currentFps
    currentResolution
    mistStatus
    qualityTier
    avgViewers
    uniqueCountries
    uniqueCities
    avgBufferHealth
    avgBitrate
    avgConnectionQuality
    packetLossRate
    totalViews
    uniqueViewers
  }
}
