query GetStreamConnectionHourly(
  $stream: String
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
) {
  streamConnectionHourlyConnection(
    stream: $stream
    timeRange: $timeRange
    first: $first
    after: $after
  ) {
    edges {
      cursor
      node {
        id
        hour
        internalName
        totalBytes
        uniqueViewers
        totalSessions
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
