query GetTenantAnalyticsDailyConnection(
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
  $last: Int
  $before: String
  $noCache: Boolean = false
) {
  tenantAnalyticsDailyConnection(
    timeRange: $timeRange
    first: $first
    after: $after
    last: $last
    before: $before
    noCache: $noCache
  ) {
    edges {
      cursor
      node {
        id
        day
        totalStreams
        totalViews
        uniqueViewers
        egressBytes
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
