query GetTrackListEvents(
  $stream: String!
  $timeRange: TimeRangeInput
  $first: Int = 100
  $after: String
  $noCache: Boolean = false
) {
  trackListEventsConnection(
    stream: $stream
    timeRange: $timeRange
    first: $first
    after: $after
    noCache: $noCache
  ) @paginate {
    edges {
      cursor
      node {
        timestamp
        stream
        nodeId
        trackList
        trackCount
        tracks {
          trackName
          trackType
          codec
          bitrateKbps
          bitrateBps
          buffer
          jitter
          width
          height
          fps
          resolution
          hasBFrames
          channels
          sampleRate
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
