---
- name: Tear down compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ compose_stack_project_dir }}"
    state: absent
    remove_volumes: false
    remove_images: never
  failed_when: false
