---
- name: Install Prometheus via prometheus.prometheus.prometheus
  ansible.builtin.include_role:
    name: prometheus.prometheus.prometheus
    apply:
      tags: [install, configure, service]
  vars:
    prometheus_web_listen_address: "0.0.0.0:{{ prometheus_port }}"
  when: "'prometheus' in prometheus_stack_components"

- name: Install node_exporter via prometheus.prometheus.node_exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
    apply:
      tags: [install, configure, service]
  vars:
    node_exporter_web_listen_address: "0.0.0.0:{{ node_exporter_port }}"
  when: "'node_exporter' in prometheus_stack_components"
