---
- name: Restart clickhouse
  listen: clickhouse restart
  ansible.builtin.systemd:
    name: "{{ clickhouse_service_name }}"
    state: restarted
  register: clickhouse_restarted

- name: Reload clickhouse
  listen: clickhouse reload
  ansible.builtin.systemd:
    name: "{{ clickhouse_service_name }}"
    state: reloaded
  when: clickhouse_restarted is not defined
