---
- name: Render zoo.cfg
  ansible.builtin.template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_conf_dir }}/zoo.cfg"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: "0644"
  notify: zookeeper restart

- name: Render myid file
  ansible.builtin.copy:
    dest: "{{ zookeeper_data_dir }}/myid"
    content: "{{ zookeeper_node_id }}\n"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: "0644"

- name: Render systemd unit
  ansible.builtin.template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - zookeeper restart
