---
- name: privateer | install
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: privateer | configure
  ansible.builtin.import_tasks: configure.yml
  tags: [configure]

- name: privateer | flush handlers before service
  ansible.builtin.meta: flush_handlers
  tags: [configure, service]

- name: privateer | service
  ansible.builtin.import_tasks: service.yml
  tags: [service]

- name: privateer | flush handlers before validate
  ansible.builtin.meta: flush_handlers
  tags: [service, validate]

- name: privateer | validate
  ansible.builtin.import_tasks: validate.yml
  tags: [validate]

- name: privateer | restart
  ansible.builtin.import_tasks: restart.yml
  tags: [restart, never]

- name: privateer | cleanup
  ansible.builtin.import_tasks: cleanup.yml
  tags: [cleanup, never]
