// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package navigatordb

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	DeletePlatformCertificate(ctx context.Context, domain string) error
	DeleteTenantAlias(ctx context.Context, tenantID string) error
	DeleteTenantAliasRetirement(ctx context.Context, arg DeleteTenantAliasRetirementParams) error
	DeleteTenantCertificate(ctx context.Context, arg DeleteTenantCertificateParams) error
	DeleteTenantCustomDomain(ctx context.Context, arg DeleteTenantCustomDomainParams) error
	DeleteTenantEdgeApplyState(ctx context.Context, tenantID string) error
	DeleteTenantEdgeApplyStateForCluster(ctx context.Context, arg DeleteTenantEdgeApplyStateForClusterParams) error
	EnsureTenantAlias(ctx context.Context, arg EnsureTenantAliasParams) (NavigatorTenantAlias, error)
	EnsureTenantCustomDomain(ctx context.Context, arg EnsureTenantCustomDomainParams) (NavigatorTenantCustomDomain, error)
	GetInternalCA(ctx context.Context, role string) (NavigatorInternalCa, error)
	GetInternalCertificate(ctx context.Context, arg GetInternalCertificateParams) (NavigatorInternalCertificate, error)
	GetPlatformACMEAccount(ctx context.Context, arg GetPlatformACMEAccountParams) (NavigatorAcmeAccount, error)
	GetPlatformCertificate(ctx context.Context, domain string) (NavigatorCertificate, error)
	GetTLSBundle(ctx context.Context, bundleID string) (NavigatorTlsBundle, error)
	GetTenantACMEAccount(ctx context.Context, arg GetTenantACMEAccountParams) (NavigatorAcmeAccount, error)
	GetTenantAlias(ctx context.Context, tenantID string) (NavigatorTenantAlias, error)
	GetTenantCertificate(ctx context.Context, arg GetTenantCertificateParams) (NavigatorCertificate, error)
	GetTenantCustomDomain(ctx context.Context, arg GetTenantCustomDomainParams) (NavigatorTenantCustomDomain, error)
	InsertTenantAliasRetirement(ctx context.Context, arg InsertTenantAliasRetirementParams) error
	ListExpiringCertificates(ctx context.Context, expiresAt time.Time) ([]NavigatorCertificate, error)
	ListExpiringTLSBundles(ctx context.Context, expiresAt time.Time) ([]NavigatorTlsBundle, error)
	ListPendingTenantAliases(ctx context.Context) ([]NavigatorTenantAlias, error)
	ListPlatformCertificates(ctx context.Context) ([]NavigatorCertificate, error)
	ListTenantAliasRetirementLabels(ctx context.Context, tenantID string) ([]string, error)
	ListTenantAliasRetirements(ctx context.Context) ([]NavigatorTenantAliasRetirement, error)
	ListTenantAliasesByStatus(ctx context.Context, statuses []string) ([]NavigatorTenantAlias, error)
	ListTenantCertificates(ctx context.Context, tenantID sql.NullString) ([]NavigatorCertificate, error)
	ListTenantCustomDomains(ctx context.Context, tenantID string) ([]NavigatorTenantCustomDomain, error)
	ListTenantCustomDomainsByStatus(ctx context.Context, statuses []string) ([]NavigatorTenantCustomDomain, error)
	ListTenantEdgeApplyState(ctx context.Context, tenantID string) ([]NavigatorTenantEdgeApplyState, error)
	ListTenantEdgeApplyStateByState(ctx context.Context, arg ListTenantEdgeApplyStateByStateParams) ([]NavigatorTenantEdgeApplyState, error)
	RecordTenantAliasRetirementFailure(ctx context.Context, arg RecordTenantAliasRetirementFailureParams) error
	SaveInternalCA(ctx context.Context, arg SaveInternalCAParams) (time.Time, error)
	SaveInternalCertificate(ctx context.Context, arg SaveInternalCertificateParams) (SaveInternalCertificateRow, error)
	SavePlatformACMEAccount(ctx context.Context, arg SavePlatformACMEAccountParams) (SavePlatformACMEAccountRow, error)
	SavePlatformCertificate(ctx context.Context, arg SavePlatformCertificateParams) (SavePlatformCertificateRow, error)
	SaveTLSBundle(ctx context.Context, arg SaveTLSBundleParams) (SaveTLSBundleRow, error)
	SaveTenantACMEAccount(ctx context.Context, arg SaveTenantACMEAccountParams) (SaveTenantACMEAccountRow, error)
	SaveTenantCertificate(ctx context.Context, arg SaveTenantCertificateParams) (SaveTenantCertificateRow, error)
	SetTenantAliasStatus(ctx context.Context, arg SetTenantAliasStatusParams) error
	SetTenantCustomDomainCertMetadata(ctx context.Context, arg SetTenantCustomDomainCertMetadataParams) (int64, error)
	SetTenantCustomDomainStatus(ctx context.Context, arg SetTenantCustomDomainStatusParams) (int64, error)
	TenantAliasHasDNS(ctx context.Context, tenantID string) (bool, error)
	UpsertTenantEdgeApplyState(ctx context.Context, arg UpsertTenantEdgeApplyStateParams) error
}

var _ Querier = (*Queries)(nil)
