// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_custom_domains.sql

package navigatordb

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const completeTenantCustomDomainIssuance = `-- name: CompleteTenantCustomDomainIssuance :execrows
UPDATE navigator.tenant_custom_domains
SET status = 'cert_issued',
    cert_issued_at = NOW(),
    issuer_id = NULLIF($1::text, ''),
    cert_expires_at = $2,
    last_error = NULL,
    next_attempt_at = NULL,
    last_renewal_error = NULL,
    last_renewal_error_at = NULL,
    failure_reported_at = NULL,
    updated_at = NOW()
WHERE tenant_id = $3::uuid
  AND domain = $4
  AND status = 'cert_issuing'
`

type CompleteTenantCustomDomainIssuanceParams struct {
	IssuerID      string       `db:"issuer_id" json:"issuer_id"`
	CertExpiresAt sql.NullTime `db:"cert_expires_at" json:"cert_expires_at"`
	TenantID      string       `db:"tenant_id" json:"tenant_id"`
	Domain        string       `db:"domain" json:"domain"`
}

func (q *Queries) CompleteTenantCustomDomainIssuance(ctx context.Context, arg CompleteTenantCustomDomainIssuanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeTenantCustomDomainIssuance,
		arg.IssuerID,
		arg.CertExpiresAt,
		arg.TenantID,
		arg.Domain,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTenantCustomDomain = `-- name: DeleteTenantCustomDomain :exec
DELETE FROM navigator.tenant_custom_domains
WHERE tenant_id = $1::uuid AND domain = $2
`

type DeleteTenantCustomDomainParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	Domain   string `db:"domain" json:"domain"`
}

func (q *Queries) DeleteTenantCustomDomain(ctx context.Context, arg DeleteTenantCustomDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteTenantCustomDomain, arg.TenantID, arg.Domain)
	return err
}

const ensureTenantCustomDomain = `-- name: EnsureTenantCustomDomain :one
INSERT INTO navigator.tenant_custom_domains
    (tenant_id, domain, status, acme_dns_subdomain, created_at, updated_at, verification_started_at)
VALUES ($1::uuid, $2, 'pending_verification', $3, NOW(), NOW(), NOW())
ON CONFLICT (tenant_id, domain) DO UPDATE SET
    status = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                  THEN 'pending_verification' ELSE navigator.tenant_custom_domains.status END,
    issuer_id = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                     THEN NULL ELSE navigator.tenant_custom_domains.issuer_id END,
    cert_issued_at = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                          THEN NULL ELSE navigator.tenant_custom_domains.cert_issued_at END,
    cert_expires_at = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                           THEN NULL ELSE navigator.tenant_custom_domains.cert_expires_at END,
    last_error = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                      THEN NULL ELSE navigator.tenant_custom_domains.last_error END,
    last_renewal_error = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                              THEN NULL ELSE navigator.tenant_custom_domains.last_renewal_error END,
    last_renewal_error_at = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                                 THEN NULL ELSE navigator.tenant_custom_domains.last_renewal_error_at END,
    next_attempt_at = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                           THEN NULL ELSE navigator.tenant_custom_domains.next_attempt_at END,
    verification_started_at = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                                   THEN NOW() ELSE navigator.tenant_custom_domains.verification_started_at END,
    failure_reported_at = CASE WHEN navigator.tenant_custom_domains.status IN ('tearing_down', 'verification_failed')
                               THEN NULL ELSE navigator.tenant_custom_domains.failure_reported_at END,
    updated_at = NOW()
RETURNING tenant_id, domain, status, acme_dns_subdomain, issuer_id,
          last_verified_at, cert_issued_at, cert_expires_at, last_error,
          created_at, updated_at, last_renewal_error, last_renewal_error_at,
          next_attempt_at, verification_started_at, failure_reported_at
`

type EnsureTenantCustomDomainParams struct {
	TenantID         string `db:"tenant_id" json:"tenant_id"`
	Domain           string `db:"domain" json:"domain"`
	AcmeDnsSubdomain string `db:"acme_dns_subdomain" json:"acme_dns_subdomain"`
}

// A tearing_down or verification_failed row is reactivated: verification
// restarts with a fresh period and the stale certificate, error, retry, and
// failure-report state is cleared. Any other row keeps its worker-driven state.
func (q *Queries) EnsureTenantCustomDomain(ctx context.Context, arg EnsureTenantCustomDomainParams) (NavigatorTenantCustomDomain, error) {
	row := q.db.QueryRowContext(ctx, ensureTenantCustomDomain, arg.TenantID, arg.Domain, arg.AcmeDnsSubdomain)
	var i NavigatorTenantCustomDomain
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.Status,
		&i.AcmeDnsSubdomain,
		&i.IssuerID,
		&i.LastVerifiedAt,
		&i.CertIssuedAt,
		&i.CertExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRenewalError,
		&i.LastRenewalErrorAt,
		&i.NextAttemptAt,
		&i.VerificationStartedAt,
		&i.FailureReportedAt,
	)
	return i, err
}

const expireTenantCustomDomainVerifications = `-- name: ExpireTenantCustomDomainVerifications :many
UPDATE navigator.tenant_custom_domains
SET status = 'verification_failed',
    failure_reported_at = NOW(),
    updated_at = NOW()
WHERE status = 'pending_verification'
  AND verification_started_at < NOW() - $1::bigint * INTERVAL '1 second'
RETURNING tenant_id, domain
`

type ExpireTenantCustomDomainVerificationsRow struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	Domain   string `db:"domain" json:"domain"`
}

// Fails every pending domain whose verification period has passed and returns
// them for their custom_domain.failed events.
func (q *Queries) ExpireTenantCustomDomainVerifications(ctx context.Context, periodSeconds int64) ([]ExpireTenantCustomDomainVerificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, expireTenantCustomDomainVerifications, periodSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireTenantCustomDomainVerificationsRow{}
	for rows.Next() {
		var i ExpireTenantCustomDomainVerificationsRow
		if err := rows.Scan(&i.TenantID, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failTenantCustomDomainIssuance = `-- name: FailTenantCustomDomainIssuance :one
WITH prior AS MATERIALIZED (
    SELECT custom_domain.tenant_id, custom_domain.domain, custom_domain.failure_reported_at
    FROM navigator.tenant_custom_domains AS custom_domain
    WHERE custom_domain.tenant_id = $3::uuid
      AND custom_domain.domain = $4
      AND custom_domain.status = 'cert_issuing'
    FOR UPDATE
)
UPDATE navigator.tenant_custom_domains AS custom_domain
SET status = 'cert_failed',
    last_error = NULLIF($1::text, ''),
    next_attempt_at = NOW() + $2::bigint * INTERVAL '1 second',
    failure_reported_at = COALESCE(prior.failure_reported_at, NOW()),
    updated_at = NOW()
FROM prior
WHERE custom_domain.tenant_id = prior.tenant_id
  AND custom_domain.domain = prior.domain
RETURNING (prior.failure_reported_at IS NULL)::boolean AS first_failure
`

type FailTenantCustomDomainIssuanceParams struct {
	ErrMsg            string `db:"err_msg" json:"err_msg"`
	RetryAfterSeconds int64  `db:"retry_after_seconds" json:"retry_after_seconds"`
	TenantID          string `db:"tenant_id" json:"tenant_id"`
	Domain            string `db:"domain" json:"domain"`
}

// Moves a cert_issuing domain to cert_failed. first_failure is true only when
// no failure of this domain was reported since its last successful issuance
// or reactivation, so retry cycles through cert_failed report nothing new.
func (q *Queries) FailTenantCustomDomainIssuance(ctx context.Context, arg FailTenantCustomDomainIssuanceParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, failTenantCustomDomainIssuance,
		arg.ErrMsg,
		arg.RetryAfterSeconds,
		arg.TenantID,
		arg.Domain,
	)
	var first_failure bool
	err := row.Scan(&first_failure)
	return first_failure, err
}

const finalizeTenantCustomDomainRemoval = `-- name: FinalizeTenantCustomDomainRemoval :execrows
WITH teardown_authority AS MATERIALIZED (
    SELECT custom_domain.tenant_id, custom_domain.domain
    FROM navigator.tenant_custom_domains AS custom_domain
    WHERE custom_domain.tenant_id = $1::uuid
      AND custom_domain.domain = $2
      AND custom_domain.status = 'tearing_down'
    FOR UPDATE
), deleted_certificate AS (
    DELETE FROM navigator.certificates AS certificate
    USING teardown_authority
    WHERE certificate.tenant_id = teardown_authority.tenant_id
      AND certificate.domain = teardown_authority.domain
), deleted_accounts AS (
    DELETE FROM navigator.acme_accounts AS account
    USING teardown_authority
    WHERE account.tenant_id = teardown_authority.tenant_id
      AND NOT EXISTS (
          SELECT 1
          FROM navigator.tenant_custom_domains AS other_domain
          WHERE other_domain.tenant_id = teardown_authority.tenant_id
            AND other_domain.domain <> teardown_authority.domain
            AND other_domain.status IN ('verified', 'pending_alias', 'cert_issuing', 'cert_issued', 'cert_failed')
      )
)
DELETE FROM navigator.tenant_custom_domains AS custom_domain
USING teardown_authority
WHERE custom_domain.tenant_id = teardown_authority.tenant_id
  AND custom_domain.domain = teardown_authority.domain
  AND custom_domain.status = 'tearing_down'
`

type FinalizeTenantCustomDomainRemovalParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	Domain   string `db:"domain" json:"domain"`
}

func (q *Queries) FinalizeTenantCustomDomainRemoval(ctx context.Context, arg FinalizeTenantCustomDomainRemovalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeTenantCustomDomainRemoval, arg.TenantID, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTenantCustomDomain = `-- name: GetTenantCustomDomain :one
SELECT tenant_id, domain, status, acme_dns_subdomain, issuer_id,
       last_verified_at, cert_issued_at, cert_expires_at, last_error,
       created_at, updated_at, last_renewal_error, last_renewal_error_at,
       next_attempt_at, verification_started_at, failure_reported_at
FROM navigator.tenant_custom_domains
WHERE tenant_id = $1::uuid AND domain = $2
`

type GetTenantCustomDomainParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	Domain   string `db:"domain" json:"domain"`
}

func (q *Queries) GetTenantCustomDomain(ctx context.Context, arg GetTenantCustomDomainParams) (NavigatorTenantCustomDomain, error) {
	row := q.db.QueryRowContext(ctx, getTenantCustomDomain, arg.TenantID, arg.Domain)
	var i NavigatorTenantCustomDomain
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.Status,
		&i.AcmeDnsSubdomain,
		&i.IssuerID,
		&i.LastVerifiedAt,
		&i.CertIssuedAt,
		&i.CertExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastRenewalError,
		&i.LastRenewalErrorAt,
		&i.NextAttemptAt,
		&i.VerificationStartedAt,
		&i.FailureReportedAt,
	)
	return i, err
}

const listTenantCustomDomains = `-- name: ListTenantCustomDomains :many
SELECT tenant_id, domain, status, acme_dns_subdomain, issuer_id,
       last_verified_at, cert_issued_at, cert_expires_at, last_error,
       created_at, updated_at, last_renewal_error, last_renewal_error_at,
       next_attempt_at, verification_started_at, failure_reported_at
FROM navigator.tenant_custom_domains
WHERE tenant_id = $1::uuid
ORDER BY domain ASC
`

func (q *Queries) ListTenantCustomDomains(ctx context.Context, tenantID string) ([]NavigatorTenantCustomDomain, error) {
	rows, err := q.db.QueryContext(ctx, listTenantCustomDomains, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NavigatorTenantCustomDomain{}
	for rows.Next() {
		var i NavigatorTenantCustomDomain
		if err := rows.Scan(
			&i.TenantID,
			&i.Domain,
			&i.Status,
			&i.AcmeDnsSubdomain,
			&i.IssuerID,
			&i.LastVerifiedAt,
			&i.CertIssuedAt,
			&i.CertExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRenewalError,
			&i.LastRenewalErrorAt,
			&i.NextAttemptAt,
			&i.VerificationStartedAt,
			&i.FailureReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantCustomDomainsByStatus = `-- name: ListTenantCustomDomainsByStatus :many
SELECT tenant_id, domain, status, acme_dns_subdomain, issuer_id,
       last_verified_at, cert_issued_at, cert_expires_at, last_error,
       created_at, updated_at, last_renewal_error, last_renewal_error_at,
       next_attempt_at, verification_started_at, failure_reported_at
FROM navigator.tenant_custom_domains
WHERE status = ANY($1::text[])
ORDER BY updated_at ASC
`

func (q *Queries) ListTenantCustomDomainsByStatus(ctx context.Context, statuses []string) ([]NavigatorTenantCustomDomain, error) {
	rows, err := q.db.QueryContext(ctx, listTenantCustomDomainsByStatus, pq.Array(statuses))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NavigatorTenantCustomDomain{}
	for rows.Next() {
		var i NavigatorTenantCustomDomain
		if err := rows.Scan(
			&i.TenantID,
			&i.Domain,
			&i.Status,
			&i.AcmeDnsSubdomain,
			&i.IssuerID,
			&i.LastVerifiedAt,
			&i.CertIssuedAt,
			&i.CertExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastRenewalError,
			&i.LastRenewalErrorAt,
			&i.NextAttemptAt,
			&i.VerificationStartedAt,
			&i.FailureReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTenantCustomDomainRenewalFailure = `-- name: RecordTenantCustomDomainRenewalFailure :execrows
UPDATE navigator.tenant_custom_domains
SET last_renewal_error = NULLIF($1::text, ''),
    last_renewal_error_at = NOW(),
    updated_at = NOW()
WHERE tenant_id = $2::uuid
  AND status IN ('cert_issuing', 'cert_issued')
`

type RecordTenantCustomDomainRenewalFailureParams struct {
	ErrMsg   string `db:"err_msg" json:"err_msg"`
	TenantID string `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) RecordTenantCustomDomainRenewalFailure(ctx context.Context, arg RecordTenantCustomDomainRenewalFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordTenantCustomDomainRenewalFailure, arg.ErrMsg, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshTenantCustomDomainServedCertificate = `-- name: RefreshTenantCustomDomainServedCertificate :execrows
UPDATE navigator.tenant_custom_domains
SET issuer_id = NULLIF($1::text, ''),
    cert_expires_at = $2,
    last_renewal_error = NULL,
    last_renewal_error_at = NULL,
    updated_at = NOW()
WHERE tenant_id = $3::uuid
  AND status IN ('cert_issuing', 'cert_issued')
  AND domain = ANY($4::text[])
`

type RefreshTenantCustomDomainServedCertificateParams struct {
	IssuerID      string       `db:"issuer_id" json:"issuer_id"`
	CertExpiresAt sql.NullTime `db:"cert_expires_at" json:"cert_expires_at"`
	TenantID      string       `db:"tenant_id" json:"tenant_id"`
	Domains       []string     `db:"domains" json:"domains"`
}

func (q *Queries) RefreshTenantCustomDomainServedCertificate(ctx context.Context, arg RefreshTenantCustomDomainServedCertificateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refreshTenantCustomDomainServedCertificate,
		arg.IssuerID,
		arg.CertExpiresAt,
		arg.TenantID,
		pq.Array(arg.Domains),
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTenantCustomDomainStatus = `-- name: SetTenantCustomDomainStatus :execrows
UPDATE navigator.tenant_custom_domains
SET status = $1,
    last_verified_at = CASE WHEN $1 = 'verified' THEN NOW() ELSE last_verified_at END,
    cert_issued_at = CASE WHEN $1 = 'cert_issued' THEN NOW() ELSE cert_issued_at END,
    last_error = NULLIF($2::text, ''),
    next_attempt_at = CASE WHEN $1 = 'cert_failed' THEN next_attempt_at ELSE NULL END,
    updated_at = NOW()
WHERE tenant_id = $3::uuid
  AND domain = $4
  AND ($1 = 'tearing_down' OR status = $5)
`

type SetTenantCustomDomainStatusParams struct {
	Status         string `db:"status" json:"status"`
	ErrMsg         string `db:"err_msg" json:"err_msg"`
	TenantID       string `db:"tenant_id" json:"tenant_id"`
	Domain         string `db:"domain" json:"domain"`
	ExpectedStatus string `db:"expected_status" json:"expected_status"`
}

func (q *Queries) SetTenantCustomDomainStatus(ctx context.Context, arg SetTenantCustomDomainStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTenantCustomDomainStatus,
		arg.Status,
		arg.ErrMsg,
		arg.TenantID,
		arg.Domain,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
