---
- name: Reload caddy
  listen: caddy reload
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
  register: caddy_reloaded
  when: not ansible_check_mode

- name: Restart caddy
  listen: caddy restart
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  register: caddy_restarted
  when: not ansible_check_mode
