// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_and_relay.sql

package foghorndb

import (
	"context"
	"database/sql"
)

const getArtifactRelayDescriptor = `-- name: GetArtifactRelayDescriptor :one
SELECT format,
       artifact_type,
       stream_internal_name,
       COALESCE(storage_cluster_id, origin_cluster_id, '')::text AS authoritative_cluster
FROM foghorn.artifacts
WHERE artifact_hash = $1 AND status != 'deleted'
LIMIT 1
`

type GetArtifactRelayDescriptorRow struct {
	Format               sql.NullString `db:"format" json:"format"`
	ArtifactType         string         `db:"artifact_type" json:"artifact_type"`
	StreamInternalName   sql.NullString `db:"stream_internal_name" json:"stream_internal_name"`
	AuthoritativeCluster string         `db:"authoritative_cluster" json:"authoritative_cluster"`
}

func (q *Queries) GetArtifactRelayDescriptor(ctx context.Context, artifactHash string) (GetArtifactRelayDescriptorRow, error) {
	row := q.db.QueryRowContext(ctx, getArtifactRelayDescriptor, artifactHash)
	var i GetArtifactRelayDescriptorRow
	err := row.Scan(
		&i.Format,
		&i.ArtifactType,
		&i.StreamInternalName,
		&i.AuthoritativeCluster,
	)
	return i, err
}

const getDVRArtifactTenantID = `-- name: GetDVRArtifactTenantID :one
SELECT tenant_id::text
FROM foghorn.artifacts
WHERE artifact_hash = $1 AND artifact_type = 'dvr'
`

func (q *Queries) GetDVRArtifactTenantID(ctx context.Context, artifactHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDVRArtifactTenantID, artifactHash)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const getLiveTranscodeAuthContext = `-- name: GetLiveTranscodeAuthContext :one
SELECT s.id::text AS session_id,
       s.tenant_id::text AS tenant_id,
       s.node_id,
       COALESCE(s.ingest_cluster_id, '')::text AS ingest_cluster_id,
       s.stream_internal_name,
       s.processes_json
FROM foghorn.ingest_sessions s
WHERE s.id::text = $1::text
  AND s.stream_internal_name = $2::text
  AND s.ended_at IS NULL
  AND s.projection_state = 'active'
LIMIT 1
`

type GetLiveTranscodeAuthContextParams struct {
	SessionID          string `db:"session_id" json:"session_id"`
	StreamInternalName string `db:"stream_internal_name" json:"stream_internal_name"`
}

type GetLiveTranscodeAuthContextRow struct {
	SessionID          string `db:"session_id" json:"session_id"`
	TenantID           string `db:"tenant_id" json:"tenant_id"`
	NodeID             string `db:"node_id" json:"node_id"`
	IngestClusterID    string `db:"ingest_cluster_id" json:"ingest_cluster_id"`
	StreamInternalName string `db:"stream_internal_name" json:"stream_internal_name"`
	ProcessesJson      string `db:"processes_json" json:"processes_json"`
}

func (q *Queries) GetLiveTranscodeAuthContext(ctx context.Context, arg GetLiveTranscodeAuthContextParams) (GetLiveTranscodeAuthContextRow, error) {
	row := q.db.QueryRowContext(ctx, getLiveTranscodeAuthContext, arg.SessionID, arg.StreamInternalName)
	var i GetLiveTranscodeAuthContextRow
	err := row.Scan(
		&i.SessionID,
		&i.TenantID,
		&i.NodeID,
		&i.IngestClusterID,
		&i.StreamInternalName,
		&i.ProcessesJson,
	)
	return i, err
}

const getProcessingJobAuthContext = `-- name: GetProcessingJobAuthContext :one
SELECT pj.job_id::text AS job_id,
       pj.tenant_id::text AS tenant_id,
       COALESCE(a.stream_id::text, '')::text AS stream_id,
       pj.processes_json,
       pj.retry_count,
       COALESCE(pj.processing_node_id, '')::text AS processing_node_id,
       pj.status,
       vm.width,
       vm.height,
       vm.fps,
       COALESCE(NULLIF(pj.input_codec, ''), NULLIF(vm.video_codec, ''), '')::text AS input_codec
FROM foghorn.processing_jobs pj
LEFT JOIN foghorn.artifacts a ON a.artifact_hash = pj.artifact_hash
LEFT JOIN foghorn.vod_metadata vm ON vm.artifact_hash = pj.artifact_hash
WHERE pj.job_id::text = $1::text
  AND pj.artifact_hash = $2::text
  AND pj.status IN ('dispatched', 'processing')
ORDER BY pj.updated_at DESC
LIMIT 1
`

type GetProcessingJobAuthContextParams struct {
	JobID        string `db:"job_id" json:"job_id"`
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
}

type GetProcessingJobAuthContextRow struct {
	JobID            string          `db:"job_id" json:"job_id"`
	TenantID         string          `db:"tenant_id" json:"tenant_id"`
	StreamID         string          `db:"stream_id" json:"stream_id"`
	ProcessesJson    sql.NullString  `db:"processes_json" json:"processes_json"`
	RetryCount       sql.NullInt32   `db:"retry_count" json:"retry_count"`
	ProcessingNodeID string          `db:"processing_node_id" json:"processing_node_id"`
	Status           sql.NullString  `db:"status" json:"status"`
	Width            sql.NullInt32   `db:"width" json:"width"`
	Height           sql.NullInt32   `db:"height" json:"height"`
	Fps              sql.NullFloat64 `db:"fps" json:"fps"`
	InputCodec       string          `db:"input_codec" json:"input_codec"`
}

func (q *Queries) GetProcessingJobAuthContext(ctx context.Context, arg GetProcessingJobAuthContextParams) (GetProcessingJobAuthContextRow, error) {
	row := q.db.QueryRowContext(ctx, getProcessingJobAuthContext, arg.JobID, arg.ArtifactHash)
	var i GetProcessingJobAuthContextRow
	err := row.Scan(
		&i.JobID,
		&i.TenantID,
		&i.StreamID,
		&i.ProcessesJson,
		&i.RetryCount,
		&i.ProcessingNodeID,
		&i.Status,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.InputCodec,
	)
	return i, err
}
