// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clip_source_dispatch.sql

package foghorndb

import (
	"context"
	"database/sql"
)

const findBestDVRChapterOverlap = `-- name: FindBestDVRChapterOverlap :one
SELECT COALESCE(c.playback_artifact_hash, '')::text AS playback_artifact_hash,
       GREATEST(COALESCE(c.actual_media_start_ms, c.start_ms), $1::bigint)::bigint AS overlap_start,
       LEAST(COALESCE(c.actual_media_end_ms, c.end_ms), $2::bigint)::bigint AS overlap_end
FROM foghorn.dvr_chapters c
JOIN foghorn.artifacts a ON a.artifact_hash = c.artifact_hash
WHERE a.artifact_type = 'dvr'
  AND a.stream_internal_name = $3
  AND a.tenant_id = $4::uuid
  AND c.state IN ('finalized', 'frozen', 'reclaimed')
  AND c.playback_artifact_hash IS NOT NULL
  AND COALESCE(c.actual_media_end_ms, c.end_ms) > $1::bigint
  AND COALESCE(c.actual_media_start_ms, c.start_ms) < $2::bigint
ORDER BY (LEAST(COALESCE(c.actual_media_end_ms, c.end_ms), $2::bigint)
        - GREATEST(COALESCE(c.actual_media_start_ms, c.start_ms), $1::bigint)) DESC
LIMIT 1
`

type FindBestDVRChapterOverlapParams struct {
	ClipStartMs        int64          `db:"clip_start_ms" json:"clip_start_ms"`
	ClipEndMs          int64          `db:"clip_end_ms" json:"clip_end_ms"`
	StreamInternalName sql.NullString `db:"stream_internal_name" json:"stream_internal_name"`
	TenantID           string         `db:"tenant_id" json:"tenant_id"`
}

type FindBestDVRChapterOverlapRow struct {
	PlaybackArtifactHash string `db:"playback_artifact_hash" json:"playback_artifact_hash"`
	OverlapStart         int64  `db:"overlap_start" json:"overlap_start"`
	OverlapEnd           int64  `db:"overlap_end" json:"overlap_end"`
}

func (q *Queries) FindBestDVRChapterOverlap(ctx context.Context, arg FindBestDVRChapterOverlapParams) (FindBestDVRChapterOverlapRow, error) {
	row := q.db.QueryRowContext(ctx, findBestDVRChapterOverlap,
		arg.ClipStartMs,
		arg.ClipEndMs,
		arg.StreamInternalName,
		arg.TenantID,
	)
	var i FindBestDVRChapterOverlapRow
	err := row.Scan(&i.PlaybackArtifactHash, &i.OverlapStart, &i.OverlapEnd)
	return i, err
}

const findLatestDVRForStream = `-- name: FindLatestDVRForStream :one
SELECT artifact_hash,
       COALESCE(internal_name, '')::text AS internal_name,
       COALESCE(EXTRACT(EPOCH FROM started_at) * 1000, 0)::bigint AS started_at_ms,
       status
FROM foghorn.artifacts
WHERE artifact_type = 'dvr'
  AND stream_internal_name = $1
  AND tenant_id = $2::uuid
ORDER BY started_at DESC NULLS LAST
LIMIT 1
`

type FindLatestDVRForStreamParams struct {
	StreamInternalName sql.NullString `db:"stream_internal_name" json:"stream_internal_name"`
	TenantID           string         `db:"tenant_id" json:"tenant_id"`
}

type FindLatestDVRForStreamRow struct {
	ArtifactHash string         `db:"artifact_hash" json:"artifact_hash"`
	InternalName string         `db:"internal_name" json:"internal_name"`
	StartedAtMs  int64          `db:"started_at_ms" json:"started_at_ms"`
	Status       sql.NullString `db:"status" json:"status"`
}

func (q *Queries) FindLatestDVRForStream(ctx context.Context, arg FindLatestDVRForStreamParams) (FindLatestDVRForStreamRow, error) {
	row := q.db.QueryRowContext(ctx, findLatestDVRForStream, arg.StreamInternalName, arg.TenantID)
	var i FindLatestDVRForStreamRow
	err := row.Scan(
		&i.ArtifactHash,
		&i.InternalName,
		&i.StartedAtMs,
		&i.Status,
	)
	return i, err
}

const getDVRWindowSeconds = `-- name: GetDVRWindowSeconds :one
SELECT dvr_window_seconds
FROM foghorn.artifacts
WHERE artifact_hash = $1
`

func (q *Queries) GetDVRWindowSeconds(ctx context.Context, artifactHash string) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getDVRWindowSeconds, artifactHash)
	var dvr_window_seconds sql.NullInt32
	err := row.Scan(&dvr_window_seconds)
	return dvr_window_seconds, err
}

const listActiveDVRRecordingNodes = `-- name: ListActiveDVRRecordingNodes :many
SELECT node_id
FROM foghorn.artifact_nodes
WHERE artifact_hash = $1
  AND is_orphaned = false
`

func (q *Queries) ListActiveDVRRecordingNodes(ctx context.Context, artifactHash string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDVRRecordingNodes, artifactHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDVRCoverageSegments = `-- name: ListDVRCoverageSegments :many
SELECT GREATEST(media_start_ms, $1::bigint)::bigint AS seg_start,
       LEAST(media_end_ms, $2::bigint)::bigint AS seg_end
FROM foghorn.dvr_segments
WHERE artifact_hash = $3
  AND status NOT IN ('reclaimed', 'deleted_local', 'lost_local')
  AND media_end_ms > $1::bigint
  AND media_start_ms < $2::bigint
ORDER BY media_start_ms, media_end_ms
`

type ListDVRCoverageSegmentsParams struct {
	LowerBound   int64  `db:"lower_bound" json:"lower_bound"`
	EndMs        int64  `db:"end_ms" json:"end_ms"`
	ArtifactHash string `db:"artifact_hash" json:"artifact_hash"`
}

type ListDVRCoverageSegmentsRow struct {
	SegStart int64 `db:"seg_start" json:"seg_start"`
	SegEnd   int64 `db:"seg_end" json:"seg_end"`
}

func (q *Queries) ListDVRCoverageSegments(ctx context.Context, arg ListDVRCoverageSegmentsParams) ([]ListDVRCoverageSegmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDVRCoverageSegments, arg.LowerBound, arg.EndMs, arg.ArtifactHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDVRCoverageSegmentsRow{}
	for rows.Next() {
		var i ListDVRCoverageSegmentsRow
		if err := rows.Scan(&i.SegStart, &i.SegEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
