// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_relay.sql

package foghorndb

import (
	"context"
	"database/sql"
)

const getFreshRelayOriginNode = `-- name: GetFreshRelayOriginNode :one
SELECT an.node_id, COALESCE(NULLIF(an.base_url, ''), no.base_url, '')::text AS base_url
FROM foghorn.artifact_nodes an
LEFT JOIN foghorn.node_outputs no ON no.node_id = an.node_id
WHERE an.artifact_hash = $1
  AND an.role = 'origin'
  AND an.is_complete = true
  AND an.is_orphaned = false
  AND an.last_seen_at > NOW() - INTERVAL '90 seconds'
ORDER BY an.last_seen_at DESC
LIMIT 1
`

type GetFreshRelayOriginNodeRow struct {
	NodeID  string `db:"node_id" json:"node_id"`
	BaseUrl string `db:"base_url" json:"base_url"`
}

func (q *Queries) GetFreshRelayOriginNode(ctx context.Context, artifactHash string) (GetFreshRelayOriginNodeRow, error) {
	row := q.db.QueryRowContext(ctx, getFreshRelayOriginNode, artifactHash)
	var i GetFreshRelayOriginNodeRow
	err := row.Scan(&i.NodeID, &i.BaseUrl)
	return i, err
}

const getRelayArtifact = `-- name: GetRelayArtifact :one
SELECT COALESCE(s3_url, '')::text AS s3_url, size_bytes, format, dtsh_synced,
       stream_internal_name, sync_status, origin_cluster_id, storage_cluster_id,
       tenant_id, artifact_type, COALESCE(active_dtsh_key, '')::text AS active_dtsh_key,
       COALESCE(durable_backend_local, false)::boolean AS durable_backend_local
FROM foghorn.artifacts
WHERE artifact_hash = $1
  AND status != 'deleted'
LIMIT 1
`

type GetRelayArtifactRow struct {
	S3Url               string         `db:"s3_url" json:"s3_url"`
	SizeBytes           sql.NullInt64  `db:"size_bytes" json:"size_bytes"`
	Format              sql.NullString `db:"format" json:"format"`
	DtshSynced          sql.NullBool   `db:"dtsh_synced" json:"dtsh_synced"`
	StreamInternalName  sql.NullString `db:"stream_internal_name" json:"stream_internal_name"`
	SyncStatus          sql.NullString `db:"sync_status" json:"sync_status"`
	OriginClusterID     sql.NullString `db:"origin_cluster_id" json:"origin_cluster_id"`
	StorageClusterID    sql.NullString `db:"storage_cluster_id" json:"storage_cluster_id"`
	TenantID            string         `db:"tenant_id" json:"tenant_id"`
	ArtifactType        string         `db:"artifact_type" json:"artifact_type"`
	ActiveDtshKey       string         `db:"active_dtsh_key" json:"active_dtsh_key"`
	DurableBackendLocal bool           `db:"durable_backend_local" json:"durable_backend_local"`
}

func (q *Queries) GetRelayArtifact(ctx context.Context, artifactHash string) (GetRelayArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, getRelayArtifact, artifactHash)
	var i GetRelayArtifactRow
	err := row.Scan(
		&i.S3Url,
		&i.SizeBytes,
		&i.Format,
		&i.DtshSynced,
		&i.StreamInternalName,
		&i.SyncStatus,
		&i.OriginClusterID,
		&i.StorageClusterID,
		&i.TenantID,
		&i.ArtifactType,
		&i.ActiveDtshKey,
		&i.DurableBackendLocal,
	)
	return i, err
}

const getRelayVodMetadata = `-- name: GetRelayVodMetadata :one
SELECT vm.s3_key, a.size_bytes, a.tenant_id
FROM foghorn.vod_metadata vm
LEFT JOIN foghorn.artifacts a ON a.artifact_hash = vm.artifact_hash
WHERE vm.artifact_hash = $1
LIMIT 1
`

type GetRelayVodMetadataRow struct {
	S3Key     sql.NullString `db:"s3_key" json:"s3_key"`
	SizeBytes sql.NullInt64  `db:"size_bytes" json:"size_bytes"`
	TenantID  sql.NullString `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetRelayVodMetadata(ctx context.Context, artifactHash string) (GetRelayVodMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getRelayVodMetadata, artifactHash)
	var i GetRelayVodMetadataRow
	err := row.Scan(&i.S3Key, &i.SizeBytes, &i.TenantID)
	return i, err
}
