// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_authority.sql

package foghorndb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deleteTenantAuthorityGrants = `-- name: DeleteTenantAuthorityGrants :exec
DELETE FROM foghorn.tenant_authority_grants
WHERE tenant_id = $1::uuid
`

func (q *Queries) DeleteTenantAuthorityGrants(ctx context.Context, tenantID string) error {
	_, err := q.db.ExecContext(ctx, deleteTenantAuthorityGrants, tenantID)
	return err
}

const getLocalMediaObjectAuthorityByInternalName = `-- name: GetLocalMediaObjectAuthorityByInternalName :one
SELECT authority.payload, authority.payload_sha256, authority.refresh_after, authority.valid_until,
       projection.authority_id, projection.authority_version, projection.local_read_ready
FROM foghorn.media_object_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'media_object'
 AND authority.authority_id = projection.authority_id
 AND authority.authority_version = projection.authority_version
WHERE projection.internal_name = $1
ORDER BY (projection.lifecycle = 'active') DESC, projection.authority_version DESC
LIMIT 1
`

type GetLocalMediaObjectAuthorityByInternalNameRow struct {
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	AuthorityID      string    `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	LocalReadReady   bool      `db:"local_read_ready" json:"local_read_ready"`
}

func (q *Queries) GetLocalMediaObjectAuthorityByInternalName(ctx context.Context, internalName string) (GetLocalMediaObjectAuthorityByInternalNameRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalMediaObjectAuthorityByInternalName, internalName)
	var i GetLocalMediaObjectAuthorityByInternalNameRow
	err := row.Scan(
		&i.Payload,
		&i.PayloadSha256,
		&i.RefreshAfter,
		&i.ValidUntil,
		&i.AuthorityID,
		&i.AuthorityVersion,
		&i.LocalReadReady,
	)
	return i, err
}

const getLocalMediaObjectAuthorityByPlaybackID = `-- name: GetLocalMediaObjectAuthorityByPlaybackID :one
SELECT authority.payload, authority.payload_sha256, authority.refresh_after, authority.valid_until,
       projection.authority_id, projection.authority_version, projection.local_read_ready
FROM foghorn.media_object_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'media_object'
 AND authority.authority_id = projection.authority_id
 AND authority.authority_version = projection.authority_version
WHERE lower(projection.playback_id) = lower($1)
ORDER BY (projection.lifecycle = 'active') DESC, projection.authority_version DESC
LIMIT 1
`

type GetLocalMediaObjectAuthorityByPlaybackIDRow struct {
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	AuthorityID      string    `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	LocalReadReady   bool      `db:"local_read_ready" json:"local_read_ready"`
}

func (q *Queries) GetLocalMediaObjectAuthorityByPlaybackID(ctx context.Context, playbackID string) (GetLocalMediaObjectAuthorityByPlaybackIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalMediaObjectAuthorityByPlaybackID, playbackID)
	var i GetLocalMediaObjectAuthorityByPlaybackIDRow
	err := row.Scan(
		&i.Payload,
		&i.PayloadSha256,
		&i.RefreshAfter,
		&i.ValidUntil,
		&i.AuthorityID,
		&i.AuthorityVersion,
		&i.LocalReadReady,
	)
	return i, err
}

const getLocalMediaObjectAuthorityByPublishingCredential = `-- name: GetLocalMediaObjectAuthorityByPublishingCredential :one
SELECT authority.payload, authority.payload_sha256, authority.refresh_after, authority.valid_until,
       projection.authority_id, projection.authority_version,
       projection.local_ingest_ready
FROM foghorn.media_object_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'media_object'
 AND authority.authority_id = projection.authority_id
 AND authority.authority_version = projection.authority_version
WHERE projection.publishing_credential_sha256 = $1
  AND projection.lifecycle = 'active'
`

type GetLocalMediaObjectAuthorityByPublishingCredentialRow struct {
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	AuthorityID      string    `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	LocalIngestReady bool      `db:"local_ingest_ready" json:"local_ingest_ready"`
}

func (q *Queries) GetLocalMediaObjectAuthorityByPublishingCredential(ctx context.Context, publishingCredentialSha256 []byte) (GetLocalMediaObjectAuthorityByPublishingCredentialRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalMediaObjectAuthorityByPublishingCredential, publishingCredentialSha256)
	var i GetLocalMediaObjectAuthorityByPublishingCredentialRow
	err := row.Scan(
		&i.Payload,
		&i.PayloadSha256,
		&i.RefreshAfter,
		&i.ValidUntil,
		&i.AuthorityID,
		&i.AuthorityVersion,
		&i.LocalIngestReady,
	)
	return i, err
}

const getLocalMediaObjectSourceAuthorityByInternalName = `-- name: GetLocalMediaObjectSourceAuthorityByInternalName :one
SELECT authority.payload, authority.payload_sha256, authority.refresh_after, authority.valid_until,
       projection.authority_id, projection.authority_version,
       projection.local_source_ready
FROM foghorn.media_object_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'media_object'
 AND authority.authority_id = projection.authority_id
 AND authority.authority_version = projection.authority_version
WHERE projection.internal_name = $1
ORDER BY (projection.lifecycle = 'active') DESC, projection.authority_version DESC
LIMIT 1
`

type GetLocalMediaObjectSourceAuthorityByInternalNameRow struct {
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	AuthorityID      string    `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	LocalSourceReady bool      `db:"local_source_ready" json:"local_source_ready"`
}

func (q *Queries) GetLocalMediaObjectSourceAuthorityByInternalName(ctx context.Context, internalName string) (GetLocalMediaObjectSourceAuthorityByInternalNameRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalMediaObjectSourceAuthorityByInternalName, internalName)
	var i GetLocalMediaObjectSourceAuthorityByInternalNameRow
	err := row.Scan(
		&i.Payload,
		&i.PayloadSha256,
		&i.RefreshAfter,
		&i.ValidUntil,
		&i.AuthorityID,
		&i.AuthorityVersion,
		&i.LocalSourceReady,
	)
	return i, err
}

const getLocalTenantAuthority = `-- name: GetLocalTenantAuthority :one
SELECT authority.payload, authority.payload_sha256, authority.refresh_after, authority.valid_until,
       projection.authority_version, projection.local_read_ready,
       projection.local_ingest_ready, projection.local_source_ready
FROM foghorn.tenant_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'tenant'
 AND authority.authority_id = projection.tenant_id::text
 AND authority.authority_version = projection.authority_version
WHERE projection.tenant_id = $1::uuid
`

type GetLocalTenantAuthorityRow struct {
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	LocalReadReady   bool      `db:"local_read_ready" json:"local_read_ready"`
	LocalIngestReady bool      `db:"local_ingest_ready" json:"local_ingest_ready"`
	LocalSourceReady bool      `db:"local_source_ready" json:"local_source_ready"`
}

func (q *Queries) GetLocalTenantAuthority(ctx context.Context, tenantID string) (GetLocalTenantAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalTenantAuthority, tenantID)
	var i GetLocalTenantAuthorityRow
	err := row.Scan(
		&i.Payload,
		&i.PayloadSha256,
		&i.RefreshAfter,
		&i.ValidUntil,
		&i.AuthorityVersion,
		&i.LocalReadReady,
		&i.LocalIngestReady,
		&i.LocalSourceReady,
	)
	return i, err
}

const getLocalTenantSourceAuthority = `-- name: GetLocalTenantSourceAuthority :one
SELECT authority.payload, authority.payload_sha256, authority.refresh_after, authority.valid_until,
       projection.authority_version, projection.local_source_ready
FROM foghorn.tenant_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'tenant'
 AND authority.authority_id = projection.tenant_id::text
 AND authority.authority_version = projection.authority_version
WHERE projection.tenant_id = $1::uuid
`

type GetLocalTenantSourceAuthorityRow struct {
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	LocalSourceReady bool      `db:"local_source_ready" json:"local_source_ready"`
}

func (q *Queries) GetLocalTenantSourceAuthority(ctx context.Context, tenantID string) (GetLocalTenantSourceAuthorityRow, error) {
	row := q.db.QueryRowContext(ctx, getLocalTenantSourceAuthority, tenantID)
	var i GetLocalTenantSourceAuthorityRow
	err := row.Scan(
		&i.Payload,
		&i.PayloadSha256,
		&i.RefreshAfter,
		&i.ValidUntil,
		&i.AuthorityVersion,
		&i.LocalSourceReady,
	)
	return i, err
}

const getMediaAuthorityForUpdate = `-- name: GetMediaAuthorityForUpdate :one
SELECT authority_version, payload_sha256, payload
FROM foghorn.media_authorities
WHERE authority_kind = $1
  AND authority_id = $2
FOR UPDATE
`

type GetMediaAuthorityForUpdateParams struct {
	AuthorityKind string `db:"authority_kind" json:"authority_kind"`
	AuthorityID   string `db:"authority_id" json:"authority_id"`
}

type GetMediaAuthorityForUpdateRow struct {
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
	PayloadSha256    []byte `db:"payload_sha256" json:"payload_sha256"`
	Payload          []byte `db:"payload" json:"payload"`
}

func (q *Queries) GetMediaAuthorityForUpdate(ctx context.Context, arg GetMediaAuthorityForUpdateParams) (GetMediaAuthorityForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaAuthorityForUpdate, arg.AuthorityKind, arg.AuthorityID)
	var i GetMediaAuthorityForUpdateRow
	err := row.Scan(&i.AuthorityVersion, &i.PayloadSha256, &i.Payload)
	return i, err
}

const getMediaObjectAuthorityByInternalName = `-- name: GetMediaObjectAuthorityByInternalName :one
SELECT authority_id, authority_version, object_kind, tenant_id, user_id, internal_name, playback_id, lifecycle, origin_cluster_id, playback_policy_kind, playback_policy, stream_id, ingest_mode, artifact_id, artifact_hash, artifact_kind, local_read_ready, local_ingest_ready, local_source_ready, publishing_credential_sha256, valid_until, updated_at
FROM foghorn.media_object_authority_projection
WHERE internal_name = $1
`

func (q *Queries) GetMediaObjectAuthorityByInternalName(ctx context.Context, internalName string) (FoghornMediaObjectAuthorityProjection, error) {
	row := q.db.QueryRowContext(ctx, getMediaObjectAuthorityByInternalName, internalName)
	var i FoghornMediaObjectAuthorityProjection
	err := row.Scan(
		&i.AuthorityID,
		&i.AuthorityVersion,
		&i.ObjectKind,
		&i.TenantID,
		&i.UserID,
		&i.InternalName,
		&i.PlaybackID,
		&i.Lifecycle,
		&i.OriginClusterID,
		&i.PlaybackPolicyKind,
		&i.PlaybackPolicy,
		&i.StreamID,
		&i.IngestMode,
		&i.ArtifactID,
		&i.ArtifactHash,
		&i.ArtifactKind,
		&i.LocalReadReady,
		&i.LocalIngestReady,
		&i.LocalSourceReady,
		&i.PublishingCredentialSha256,
		&i.ValidUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaObjectAuthorityByPlaybackID = `-- name: GetMediaObjectAuthorityByPlaybackID :one
SELECT authority_id, authority_version, object_kind, tenant_id, user_id, internal_name, playback_id, lifecycle, origin_cluster_id, playback_policy_kind, playback_policy, stream_id, ingest_mode, artifact_id, artifact_hash, artifact_kind, local_read_ready, local_ingest_ready, local_source_ready, publishing_credential_sha256, valid_until, updated_at
FROM foghorn.media_object_authority_projection
WHERE lower(playback_id) = lower($1)
`

func (q *Queries) GetMediaObjectAuthorityByPlaybackID(ctx context.Context, playbackID string) (FoghornMediaObjectAuthorityProjection, error) {
	row := q.db.QueryRowContext(ctx, getMediaObjectAuthorityByPlaybackID, playbackID)
	var i FoghornMediaObjectAuthorityProjection
	err := row.Scan(
		&i.AuthorityID,
		&i.AuthorityVersion,
		&i.ObjectKind,
		&i.TenantID,
		&i.UserID,
		&i.InternalName,
		&i.PlaybackID,
		&i.Lifecycle,
		&i.OriginClusterID,
		&i.PlaybackPolicyKind,
		&i.PlaybackPolicy,
		&i.StreamID,
		&i.IngestMode,
		&i.ArtifactID,
		&i.ArtifactHash,
		&i.ArtifactKind,
		&i.LocalReadReady,
		&i.LocalIngestReady,
		&i.LocalSourceReady,
		&i.PublishingCredentialSha256,
		&i.ValidUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantAuthorityProjection = `-- name: GetTenantAuthorityProjection :one
SELECT tenant_id::text AS tenant_id, authority_version, lifecycle, billing_decision,
       billing_model, COALESCE(official_cluster_id, '')::text AS official_cluster_id,
       allow_platform_shared_playback, max_streams, max_viewers, allowances,
       decision_reason, valid_until
FROM foghorn.tenant_authority_projection
WHERE tenant_id = $1::uuid
`

type GetTenantAuthorityProjectionRow struct {
	TenantID                    string          `db:"tenant_id" json:"tenant_id"`
	AuthorityVersion            int64           `db:"authority_version" json:"authority_version"`
	Lifecycle                   string          `db:"lifecycle" json:"lifecycle"`
	BillingDecision             string          `db:"billing_decision" json:"billing_decision"`
	BillingModel                string          `db:"billing_model" json:"billing_model"`
	OfficialClusterID           string          `db:"official_cluster_id" json:"official_cluster_id"`
	AllowPlatformSharedPlayback bool            `db:"allow_platform_shared_playback" json:"allow_platform_shared_playback"`
	MaxStreams                  int32           `db:"max_streams" json:"max_streams"`
	MaxViewers                  int32           `db:"max_viewers" json:"max_viewers"`
	Allowances                  json.RawMessage `db:"allowances" json:"allowances"`
	DecisionReason              string          `db:"decision_reason" json:"decision_reason"`
	ValidUntil                  time.Time       `db:"valid_until" json:"valid_until"`
}

func (q *Queries) GetTenantAuthorityProjection(ctx context.Context, tenantID string) (GetTenantAuthorityProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantAuthorityProjection, tenantID)
	var i GetTenantAuthorityProjectionRow
	err := row.Scan(
		&i.TenantID,
		&i.AuthorityVersion,
		&i.Lifecycle,
		&i.BillingDecision,
		&i.BillingModel,
		&i.OfficialClusterID,
		&i.AllowPlatformSharedPlayback,
		&i.MaxStreams,
		&i.MaxViewers,
		&i.Allowances,
		&i.DecisionReason,
		&i.ValidUntil,
	)
	return i, err
}

const insertMediaAuthorityApplyAudit = `-- name: InsertMediaAuthorityApplyAudit :exec
INSERT INTO foghorn.media_authority_apply_audit (
    authority_kind, authority_id, authority_version, signer_key_id,
    payload_sha256, outcome, reason
) VALUES (
    NULLIF($1::text, ''), NULLIF($2::text, ''),
    $3, NULLIF($4::text, ''),
    $5, $6, $7
)
`

type InsertMediaAuthorityApplyAuditParams struct {
	AuthorityKind    string        `db:"authority_kind" json:"authority_kind"`
	AuthorityID      string        `db:"authority_id" json:"authority_id"`
	AuthorityVersion sql.NullInt64 `db:"authority_version" json:"authority_version"`
	SignerKeyID      string        `db:"signer_key_id" json:"signer_key_id"`
	PayloadSha256    []byte        `db:"payload_sha256" json:"payload_sha256"`
	Outcome          string        `db:"outcome" json:"outcome"`
	Reason           string        `db:"reason" json:"reason"`
}

func (q *Queries) InsertMediaAuthorityApplyAudit(ctx context.Context, arg InsertMediaAuthorityApplyAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertMediaAuthorityApplyAudit,
		arg.AuthorityKind,
		arg.AuthorityID,
		arg.AuthorityVersion,
		arg.SignerKeyID,
		arg.PayloadSha256,
		arg.Outcome,
		arg.Reason,
	)
	return err
}

const insertTenantAuthorityGrant = `-- name: InsertTenantAuthorityGrant :exec
INSERT INTO foghorn.tenant_authority_grants (
    tenant_id, cluster_id, authority_version, access_source, access_level,
    subscription_status, cluster_class, cluster_type, deployment_model, owner_tenant_id, expires_at
) VALUES (
    $1::uuid, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    NULLIF($10::text, '')::uuid, $11
)
`

type InsertTenantAuthorityGrantParams struct {
	TenantID           string       `db:"tenant_id" json:"tenant_id"`
	ClusterID          string       `db:"cluster_id" json:"cluster_id"`
	AuthorityVersion   int64        `db:"authority_version" json:"authority_version"`
	AccessSource       string       `db:"access_source" json:"access_source"`
	AccessLevel        string       `db:"access_level" json:"access_level"`
	SubscriptionStatus string       `db:"subscription_status" json:"subscription_status"`
	ClusterClass       string       `db:"cluster_class" json:"cluster_class"`
	ClusterType        string       `db:"cluster_type" json:"cluster_type"`
	DeploymentModel    string       `db:"deployment_model" json:"deployment_model"`
	OwnerTenantID      string       `db:"owner_tenant_id" json:"owner_tenant_id"`
	ExpiresAt          sql.NullTime `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertTenantAuthorityGrant(ctx context.Context, arg InsertTenantAuthorityGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertTenantAuthorityGrant,
		arg.TenantID,
		arg.ClusterID,
		arg.AuthorityVersion,
		arg.AccessSource,
		arg.AccessLevel,
		arg.SubscriptionStatus,
		arg.ClusterClass,
		arg.ClusterType,
		arg.DeploymentModel,
		arg.OwnerTenantID,
		arg.ExpiresAt,
	)
	return err
}

const listLocalManagedStreamAuthorities = `-- name: ListLocalManagedStreamAuthorities :many
SELECT authority.authority_id, authority.authority_version, authority.payload, authority.payload_sha256,
       authority.refresh_after, authority.valid_until,
       projection.local_source_ready
FROM foghorn.media_object_authority_projection AS projection
JOIN foghorn.media_authorities AS authority
  ON authority.authority_kind = 'media_object'
 AND authority.authority_id = projection.authority_id
 AND authority.authority_version = projection.authority_version
WHERE projection.object_kind = 'live_stream'
  AND projection.ingest_mode = 'mist_native'
ORDER BY authority.authority_id
`

type ListLocalManagedStreamAuthoritiesRow struct {
	AuthorityID      string    `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64     `db:"authority_version" json:"authority_version"`
	Payload          []byte    `db:"payload" json:"payload"`
	PayloadSha256    []byte    `db:"payload_sha256" json:"payload_sha256"`
	RefreshAfter     time.Time `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time `db:"valid_until" json:"valid_until"`
	LocalSourceReady bool      `db:"local_source_ready" json:"local_source_ready"`
}

func (q *Queries) ListLocalManagedStreamAuthorities(ctx context.Context) ([]ListLocalManagedStreamAuthoritiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLocalManagedStreamAuthorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalManagedStreamAuthoritiesRow{}
	for rows.Next() {
		var i ListLocalManagedStreamAuthoritiesRow
		if err := rows.Scan(
			&i.AuthorityID,
			&i.AuthorityVersion,
			&i.Payload,
			&i.PayloadSha256,
			&i.RefreshAfter,
			&i.ValidUntil,
			&i.LocalSourceReady,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAuthorityGrants = `-- name: ListTenantAuthorityGrants :many
SELECT tenant_id::text AS tenant_id, cluster_id, authority_version, access_source,
       access_level, subscription_status, cluster_class, deployment_model,
       cluster_type,
       COALESCE(owner_tenant_id::text, '')::text AS owner_tenant_id, expires_at
FROM foghorn.tenant_authority_grants
WHERE tenant_id = $1::uuid
ORDER BY cluster_id
`

type ListTenantAuthorityGrantsRow struct {
	TenantID           string       `db:"tenant_id" json:"tenant_id"`
	ClusterID          string       `db:"cluster_id" json:"cluster_id"`
	AuthorityVersion   int64        `db:"authority_version" json:"authority_version"`
	AccessSource       string       `db:"access_source" json:"access_source"`
	AccessLevel        string       `db:"access_level" json:"access_level"`
	SubscriptionStatus string       `db:"subscription_status" json:"subscription_status"`
	ClusterClass       string       `db:"cluster_class" json:"cluster_class"`
	DeploymentModel    string       `db:"deployment_model" json:"deployment_model"`
	ClusterType        string       `db:"cluster_type" json:"cluster_type"`
	OwnerTenantID      string       `db:"owner_tenant_id" json:"owner_tenant_id"`
	ExpiresAt          sql.NullTime `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ListTenantAuthorityGrants(ctx context.Context, tenantID string) ([]ListTenantAuthorityGrantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantAuthorityGrants, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantAuthorityGrantsRow{}
	for rows.Next() {
		var i ListTenantAuthorityGrantsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ClusterID,
			&i.AuthorityVersion,
			&i.AccessSource,
			&i.AccessLevel,
			&i.SubscriptionStatus,
			&i.ClusterClass,
			&i.DeploymentModel,
			&i.ClusterType,
			&i.OwnerTenantID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMediaAuthority = `-- name: LockMediaAuthority :exec
SELECT pg_advisory_xact_lock(
    $1::integer,
    hashtext($2::text || ':' || $3::text)
)
`

type LockMediaAuthorityParams struct {
	LockNamespace int32  `db:"lock_namespace" json:"lock_namespace"`
	AuthorityKind string `db:"authority_kind" json:"authority_kind"`
	AuthorityID   string `db:"authority_id" json:"authority_id"`
}

func (q *Queries) LockMediaAuthority(ctx context.Context, arg LockMediaAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, lockMediaAuthority, arg.LockNamespace, arg.AuthorityKind, arg.AuthorityID)
	return err
}

const markMediaObjectAuthorityLocalIngestReady = `-- name: MarkMediaObjectAuthorityLocalIngestReady :execrows
UPDATE foghorn.media_object_authority_projection
SET local_ingest_ready = TRUE, updated_at = NOW()
WHERE authority_id = $1
  AND authority_version = $2
`

type MarkMediaObjectAuthorityLocalIngestReadyParams struct {
	AuthorityID      string `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
}

func (q *Queries) MarkMediaObjectAuthorityLocalIngestReady(ctx context.Context, arg MarkMediaObjectAuthorityLocalIngestReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMediaObjectAuthorityLocalIngestReady, arg.AuthorityID, arg.AuthorityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMediaObjectAuthorityLocalReadReady = `-- name: MarkMediaObjectAuthorityLocalReadReady :execrows
UPDATE foghorn.media_object_authority_projection
SET local_read_ready = TRUE, updated_at = NOW()
WHERE authority_id = $1
  AND authority_version = $2
`

type MarkMediaObjectAuthorityLocalReadReadyParams struct {
	AuthorityID      string `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
}

func (q *Queries) MarkMediaObjectAuthorityLocalReadReady(ctx context.Context, arg MarkMediaObjectAuthorityLocalReadReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMediaObjectAuthorityLocalReadReady, arg.AuthorityID, arg.AuthorityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMediaObjectAuthorityLocalSourceReady = `-- name: MarkMediaObjectAuthorityLocalSourceReady :execrows
UPDATE foghorn.media_object_authority_projection
SET local_source_ready = TRUE, updated_at = NOW()
WHERE authority_id = $1
  AND authority_version = $2
`

type MarkMediaObjectAuthorityLocalSourceReadyParams struct {
	AuthorityID      string `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
}

func (q *Queries) MarkMediaObjectAuthorityLocalSourceReady(ctx context.Context, arg MarkMediaObjectAuthorityLocalSourceReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMediaObjectAuthorityLocalSourceReady, arg.AuthorityID, arg.AuthorityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markTenantAuthorityLocalIngestReady = `-- name: MarkTenantAuthorityLocalIngestReady :execrows
UPDATE foghorn.tenant_authority_projection
SET local_ingest_ready = TRUE, updated_at = NOW()
WHERE tenant_id = $1::uuid
  AND authority_version = $2
`

type MarkTenantAuthorityLocalIngestReadyParams struct {
	TenantID         string `db:"tenant_id" json:"tenant_id"`
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
}

func (q *Queries) MarkTenantAuthorityLocalIngestReady(ctx context.Context, arg MarkTenantAuthorityLocalIngestReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTenantAuthorityLocalIngestReady, arg.TenantID, arg.AuthorityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markTenantAuthorityLocalReadReady = `-- name: MarkTenantAuthorityLocalReadReady :execrows
UPDATE foghorn.tenant_authority_projection
SET local_read_ready = TRUE, updated_at = NOW()
WHERE tenant_id = $1::uuid
  AND authority_version = $2
`

type MarkTenantAuthorityLocalReadReadyParams struct {
	TenantID         string `db:"tenant_id" json:"tenant_id"`
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
}

func (q *Queries) MarkTenantAuthorityLocalReadReady(ctx context.Context, arg MarkTenantAuthorityLocalReadReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTenantAuthorityLocalReadReady, arg.TenantID, arg.AuthorityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markTenantAuthorityLocalSourceReady = `-- name: MarkTenantAuthorityLocalSourceReady :execrows
UPDATE foghorn.tenant_authority_projection
SET local_source_ready = TRUE, updated_at = NOW()
WHERE tenant_id = $1::uuid
  AND authority_version = $2
`

type MarkTenantAuthorityLocalSourceReadyParams struct {
	TenantID         string `db:"tenant_id" json:"tenant_id"`
	AuthorityVersion int64  `db:"authority_version" json:"authority_version"`
}

func (q *Queries) MarkTenantAuthorityLocalSourceReady(ctx context.Context, arg MarkTenantAuthorityLocalSourceReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTenantAuthorityLocalSourceReady, arg.TenantID, arg.AuthorityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneMediaAuthorityApplyAudit = `-- name: PruneMediaAuthorityApplyAudit :execrows
WITH expired AS (
    SELECT id
    FROM foghorn.media_authority_apply_audit
    WHERE observed_at < NOW() - $1::bigint * INTERVAL '1 second'
    ORDER BY observed_at
    LIMIT $2
)
DELETE FROM foghorn.media_authority_apply_audit AS audit
USING expired
WHERE audit.id = expired.id
`

type PruneMediaAuthorityApplyAuditParams struct {
	RetentionSeconds int64 `db:"retention_seconds" json:"retention_seconds"`
	BatchSize        int32 `db:"batch_size" json:"batch_size"`
}

func (q *Queries) PruneMediaAuthorityApplyAudit(ctx context.Context, arg PruneMediaAuthorityApplyAuditParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneMediaAuthorityApplyAudit, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setLocalMediaAuthorityLockTimeout = `-- name: SetLocalMediaAuthorityLockTimeout :exec
SELECT set_config('lock_timeout', $1, true)
`

func (q *Queries) SetLocalMediaAuthorityLockTimeout(ctx context.Context, lockTimeout string) error {
	_, err := q.db.ExecContext(ctx, setLocalMediaAuthorityLockTimeout, lockTimeout)
	return err
}

const upsertMediaAuthority = `-- name: UpsertMediaAuthority :exec
INSERT INTO foghorn.media_authorities (
    authority_kind, authority_id, authority_version, signer_key_id,
    audience_cell_id, issued_at, refresh_after, valid_until, payload_sha256,
    signed_envelope, payload, source_revisions, applied_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, NOW()
)
ON CONFLICT (authority_kind, authority_id) DO UPDATE
SET authority_version = EXCLUDED.authority_version,
    signer_key_id = EXCLUDED.signer_key_id,
    audience_cell_id = EXCLUDED.audience_cell_id,
    issued_at = EXCLUDED.issued_at,
    refresh_after = EXCLUDED.refresh_after,
    valid_until = EXCLUDED.valid_until,
    payload_sha256 = EXCLUDED.payload_sha256,
    signed_envelope = EXCLUDED.signed_envelope,
    payload = EXCLUDED.payload,
    source_revisions = EXCLUDED.source_revisions,
    applied_at = NOW()
`

type UpsertMediaAuthorityParams struct {
	AuthorityKind    string          `db:"authority_kind" json:"authority_kind"`
	AuthorityID      string          `db:"authority_id" json:"authority_id"`
	AuthorityVersion int64           `db:"authority_version" json:"authority_version"`
	SignerKeyID      string          `db:"signer_key_id" json:"signer_key_id"`
	AudienceCellID   string          `db:"audience_cell_id" json:"audience_cell_id"`
	IssuedAt         time.Time       `db:"issued_at" json:"issued_at"`
	RefreshAfter     time.Time       `db:"refresh_after" json:"refresh_after"`
	ValidUntil       time.Time       `db:"valid_until" json:"valid_until"`
	PayloadSha256    []byte          `db:"payload_sha256" json:"payload_sha256"`
	SignedEnvelope   []byte          `db:"signed_envelope" json:"signed_envelope"`
	Payload          []byte          `db:"payload" json:"payload"`
	SourceRevisions  json.RawMessage `db:"source_revisions" json:"source_revisions"`
}

func (q *Queries) UpsertMediaAuthority(ctx context.Context, arg UpsertMediaAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, upsertMediaAuthority,
		arg.AuthorityKind,
		arg.AuthorityID,
		arg.AuthorityVersion,
		arg.SignerKeyID,
		arg.AudienceCellID,
		arg.IssuedAt,
		arg.RefreshAfter,
		arg.ValidUntil,
		arg.PayloadSha256,
		arg.SignedEnvelope,
		arg.Payload,
		arg.SourceRevisions,
	)
	return err
}

const upsertMediaObjectAuthorityProjection = `-- name: UpsertMediaObjectAuthorityProjection :exec
WITH upserted AS (
INSERT INTO foghorn.media_object_authority_projection (
    authority_id, authority_version, object_kind, tenant_id, user_id, internal_name,
    playback_id, lifecycle, origin_cluster_id, playback_policy_kind, playback_policy,
    stream_id, ingest_mode, artifact_id, artifact_hash, artifact_kind,
    local_read_ready, local_ingest_ready, local_source_ready, publishing_credential_sha256,
    valid_until, updated_at
) VALUES (
    $1, $2, $3,
    $4::uuid, NULLIF($5::text, '')::uuid,
    $6, $7, $8,
    NULLIF($9::text, ''), $10,
    $11, NULLIF($12::text, '')::uuid,
    NULLIF($13::text, ''), NULLIF($14::text, ''),
    NULLIF($15::text, ''), NULLIF($16::text, ''),
    FALSE, FALSE, FALSE, $17, $18, NOW()
)
ON CONFLICT (authority_id) DO UPDATE
SET authority_version = EXCLUDED.authority_version,
    object_kind = EXCLUDED.object_kind,
    tenant_id = EXCLUDED.tenant_id,
    user_id = EXCLUDED.user_id,
    internal_name = EXCLUDED.internal_name,
    playback_id = EXCLUDED.playback_id,
    lifecycle = EXCLUDED.lifecycle,
    origin_cluster_id = EXCLUDED.origin_cluster_id,
    playback_policy_kind = EXCLUDED.playback_policy_kind,
    playback_policy = EXCLUDED.playback_policy,
    stream_id = EXCLUDED.stream_id,
    ingest_mode = EXCLUDED.ingest_mode,
    artifact_id = EXCLUDED.artifact_id,
    artifact_hash = EXCLUDED.artifact_hash,
    artifact_kind = EXCLUDED.artifact_kind,
    local_read_ready = CASE
        WHEN $19::boolean
        THEN foghorn.media_object_authority_projection.local_read_ready
        ELSE FALSE
    END,
    local_ingest_ready = CASE
        WHEN $20::boolean
        THEN foghorn.media_object_authority_projection.local_ingest_ready
        ELSE FALSE
    END,
    local_source_ready = CASE
        WHEN $21::boolean
        THEN foghorn.media_object_authority_projection.local_source_ready
        ELSE FALSE
    END,
    publishing_credential_sha256 = EXCLUDED.publishing_credential_sha256,
    valid_until = EXCLUDED.valid_until,
    updated_at = NOW()
RETURNING authority_id, tenant_id, artifact_hash, lifecycle, valid_until
)
UPDATE foghorn.artifacts AS artifact
SET status = 'ready'
FROM upserted
WHERE upserted.lifecycle = 'active'
  AND upserted.valid_until > NOW()
  AND upserted.artifact_hash IS NOT NULL
  AND artifact.artifact_hash = upserted.artifact_hash
  AND artifact.tenant_id = upserted.tenant_id
  AND artifact.federated_pointer = true
  AND artifact.status = 'deleted'
  -- A non-NULL token means a purge worker may already be deleting bytes
  -- outside this transaction. Settlement, not authority apply, owns restore.
  AND artifact.federated_purge_token IS NULL
  -- A newly delivered active authority cancels an interrupted expiry-only
  -- purge fence. A signed tombstone under any other authority identity stays
  -- terminal; the row being replaced is read through the CTE's RETURNING data.
  AND NOT EXISTS (
      SELECT 1
      FROM foghorn.media_object_authority_projection AS tombstone
      WHERE tombstone.tenant_id = upserted.tenant_id
        AND tombstone.artifact_hash = upserted.artifact_hash
        AND tombstone.lifecycle = 'tombstone'
        AND tombstone.authority_id <> upserted.authority_id
  )
`

type UpsertMediaObjectAuthorityProjectionParams struct {
	AuthorityID                string    `db:"authority_id" json:"authority_id"`
	AuthorityVersion           int64     `db:"authority_version" json:"authority_version"`
	ObjectKind                 string    `db:"object_kind" json:"object_kind"`
	TenantID                   string    `db:"tenant_id" json:"tenant_id"`
	UserID                     string    `db:"user_id" json:"user_id"`
	InternalName               string    `db:"internal_name" json:"internal_name"`
	PlaybackID                 string    `db:"playback_id" json:"playback_id"`
	Lifecycle                  string    `db:"lifecycle" json:"lifecycle"`
	OriginClusterID            string    `db:"origin_cluster_id" json:"origin_cluster_id"`
	PlaybackPolicyKind         string    `db:"playback_policy_kind" json:"playback_policy_kind"`
	PlaybackPolicy             []byte    `db:"playback_policy" json:"playback_policy"`
	StreamID                   string    `db:"stream_id" json:"stream_id"`
	IngestMode                 string    `db:"ingest_mode" json:"ingest_mode"`
	ArtifactID                 string    `db:"artifact_id" json:"artifact_id"`
	ArtifactHash               string    `db:"artifact_hash" json:"artifact_hash"`
	ArtifactKind               string    `db:"artifact_kind" json:"artifact_kind"`
	PublishingCredentialSha256 []byte    `db:"publishing_credential_sha256" json:"publishing_credential_sha256"`
	ValidUntil                 time.Time `db:"valid_until" json:"valid_until"`
	PreserveLocalReadReady     bool      `db:"preserve_local_read_ready" json:"preserve_local_read_ready"`
	PreserveLocalIngestReady   bool      `db:"preserve_local_ingest_ready" json:"preserve_local_ingest_ready"`
	PreserveLocalSourceReady   bool      `db:"preserve_local_source_ready" json:"preserve_local_source_ready"`
}

func (q *Queries) UpsertMediaObjectAuthorityProjection(ctx context.Context, arg UpsertMediaObjectAuthorityProjectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertMediaObjectAuthorityProjection,
		arg.AuthorityID,
		arg.AuthorityVersion,
		arg.ObjectKind,
		arg.TenantID,
		arg.UserID,
		arg.InternalName,
		arg.PlaybackID,
		arg.Lifecycle,
		arg.OriginClusterID,
		arg.PlaybackPolicyKind,
		arg.PlaybackPolicy,
		arg.StreamID,
		arg.IngestMode,
		arg.ArtifactID,
		arg.ArtifactHash,
		arg.ArtifactKind,
		arg.PublishingCredentialSha256,
		arg.ValidUntil,
		arg.PreserveLocalReadReady,
		arg.PreserveLocalIngestReady,
		arg.PreserveLocalSourceReady,
	)
	return err
}

const upsertTenantAuthorityProjection = `-- name: UpsertTenantAuthorityProjection :exec
INSERT INTO foghorn.tenant_authority_projection (
    tenant_id, authority_version, lifecycle, billing_decision, billing_model,
    official_cluster_id, allow_platform_shared_playback, max_streams, max_viewers,
    allowances, decision_reason, local_read_ready, local_ingest_ready, local_source_ready,
    valid_until, updated_at
) VALUES (
    $1::uuid, $2, $3,
    $4, $5, NULLIF($6::text, ''),
    $7, $8, $9,
    $10, $11, FALSE, FALSE, FALSE,
    $12, NOW()
)
ON CONFLICT (tenant_id) DO UPDATE
SET authority_version = EXCLUDED.authority_version,
    lifecycle = EXCLUDED.lifecycle,
    billing_decision = EXCLUDED.billing_decision,
    billing_model = EXCLUDED.billing_model,
    official_cluster_id = EXCLUDED.official_cluster_id,
    allow_platform_shared_playback = EXCLUDED.allow_platform_shared_playback,
    max_streams = EXCLUDED.max_streams,
    max_viewers = EXCLUDED.max_viewers,
    allowances = EXCLUDED.allowances,
    decision_reason = EXCLUDED.decision_reason,
    local_read_ready = CASE
        WHEN $13::boolean
        THEN foghorn.tenant_authority_projection.local_read_ready
        ELSE FALSE
    END,
    local_ingest_ready = CASE
        WHEN $14::boolean
        THEN foghorn.tenant_authority_projection.local_ingest_ready
        ELSE FALSE
    END,
    local_source_ready = CASE
        WHEN $15::boolean
        THEN foghorn.tenant_authority_projection.local_source_ready
        ELSE FALSE
    END,
    valid_until = EXCLUDED.valid_until,
    updated_at = NOW()
`

type UpsertTenantAuthorityProjectionParams struct {
	TenantID                    string          `db:"tenant_id" json:"tenant_id"`
	AuthorityVersion            int64           `db:"authority_version" json:"authority_version"`
	Lifecycle                   string          `db:"lifecycle" json:"lifecycle"`
	BillingDecision             string          `db:"billing_decision" json:"billing_decision"`
	BillingModel                string          `db:"billing_model" json:"billing_model"`
	OfficialClusterID           string          `db:"official_cluster_id" json:"official_cluster_id"`
	AllowPlatformSharedPlayback bool            `db:"allow_platform_shared_playback" json:"allow_platform_shared_playback"`
	MaxStreams                  int32           `db:"max_streams" json:"max_streams"`
	MaxViewers                  int32           `db:"max_viewers" json:"max_viewers"`
	Allowances                  json.RawMessage `db:"allowances" json:"allowances"`
	DecisionReason              string          `db:"decision_reason" json:"decision_reason"`
	ValidUntil                  time.Time       `db:"valid_until" json:"valid_until"`
	PreserveLocalReadReady      bool            `db:"preserve_local_read_ready" json:"preserve_local_read_ready"`
	PreserveLocalIngestReady    bool            `db:"preserve_local_ingest_ready" json:"preserve_local_ingest_ready"`
	PreserveLocalSourceReady    bool            `db:"preserve_local_source_ready" json:"preserve_local_source_ready"`
}

func (q *Queries) UpsertTenantAuthorityProjection(ctx context.Context, arg UpsertTenantAuthorityProjectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenantAuthorityProjection,
		arg.TenantID,
		arg.AuthorityVersion,
		arg.Lifecycle,
		arg.BillingDecision,
		arg.BillingModel,
		arg.OfficialClusterID,
		arg.AllowPlatformSharedPlayback,
		arg.MaxStreams,
		arg.MaxViewers,
		arg.Allowances,
		arg.DecisionReason,
		arg.ValidUntil,
		arg.PreserveLocalReadReady,
		arg.PreserveLocalIngestReady,
		arg.PreserveLocalSourceReady,
	)
	return err
}
