// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package foghorndb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

type Querier interface {
	AbortPendingSourceProjection(ctx context.Context, arg AbortPendingSourceProjectionParams) (string, error)
	AcquireDVRStartLock(ctx context.Context, lockKey string) error
	AcquireThumbnailPublishLease(ctx context.Context, arg AcquireThumbnailPublishLeaseParams) (sql.NullString, error)
	ActivateThumbnailPointer(ctx context.Context, arg ActivateThumbnailPointerParams) (int64, error)
	AdmissionGenerationActive(ctx context.Context, arg AdmissionGenerationActiveParams) (bool, error)
	AdoptRemoteArtifact(ctx context.Context, arg AdoptRemoteArtifactParams) error
	AdvanceCatalogWatermark(ctx context.Context, arg AdvanceCatalogWatermarkParams) error
	AdvanceNodeArtifactReportWatermark(ctx context.Context, arg AdvanceNodeArtifactReportWatermarkParams) (int64, error)
	AdvanceVodToProcessing(ctx context.Context, arg AdvanceVodToProcessingParams) (int64, error)
	AllocateArtifactNodeCopyVersion(ctx context.Context) (int64, error)
	AllocateNodeControlFence(ctx context.Context) (int64, error)
	ArmStreamCleanupSecondSweep(ctx context.Context, arg ArmStreamCleanupSecondSweepParams) error
	ArtifactHasActiveNodes(ctx context.Context, artifactHash string) (bool, error)
	ArtifactLifecycleStatus(ctx context.Context, artifactHash string) (sql.NullString, error)
	AssetTombstoned(ctx context.Context, assetKey string) (bool, error)
	AssignProcessingJobNode(ctx context.Context, arg AssignProcessingJobNodeParams) (int64, error)
	BackfillArtifactOriginCluster(ctx context.Context, arg BackfillArtifactOriginClusterParams) error
	BackfillCatalogRevisions(ctx context.Context, arg BackfillCatalogRevisionsParams) (int64, error)
	BackfillOriginCluster(ctx context.Context, arg BackfillOriginClusterParams) (int64, error)
	BackoffCatalogProjection(ctx context.Context, arg BackoffCatalogProjectionParams) error
	BackoffThumbnailRecovery(ctx context.Context, arg BackoffThumbnailRecoveryParams) error
	BindDVRDispatchOwner(ctx context.Context, arg BindDVRDispatchOwnerParams) (int64, error)
	CancelClipProcessingJobs(ctx context.Context, artifactHash sql.NullString) error
	CellStorageIdentityCommitted(ctx context.Context) (bool, error)
	ClaimAdmissionEffects(ctx context.Context, arg ClaimAdmissionEffectsParams) ([]ClaimAdmissionEffectsRow, error)
	ClaimArtifactEvents(ctx context.Context, arg ClaimArtifactEventsParams) ([]ClaimArtifactEventsRow, error)
	ClaimDVRChapterFinalization(ctx context.Context, arg ClaimDVRChapterFinalizationParams) (int64, error)
	ClaimDVRFinalization(ctx context.Context, arg ClaimDVRFinalizationParams) (ClaimDVRFinalizationRow, error)
	ClaimDVRStopByArtifact(ctx context.Context, arg ClaimDVRStopByArtifactParams) ([]ClaimDVRStopByArtifactRow, error)
	ClaimDVRStopsForEndedSource(ctx context.Context, arg ClaimDVRStopsForEndedSourceParams) ([]ClaimDVRStopsForEndedSourceRow, error)
	ClaimDVRStopsForGeneration(ctx context.Context, arg ClaimDVRStopsForGenerationParams) ([]ClaimDVRStopsForGenerationRow, error)
	ClaimDtshAttempt(ctx context.Context, arg ClaimDtshAttemptParams) (ClaimDtshAttemptRow, error)
	ClaimDueReassertThumbnailAttempts(ctx context.Context, arg ClaimDueReassertThumbnailAttemptsParams) ([]ClaimDueReassertThumbnailAttemptsRow, error)
	ClaimFreezeAttempt(ctx context.Context, arg ClaimFreezeAttemptParams) (int64, error)
	ClaimOfflineEffects(ctx context.Context, arg ClaimOfflineEffectsParams) ([]ClaimOfflineEffectsRow, error)
	ClaimQueuedProcessingJobs(ctx context.Context) ([]ClaimQueuedProcessingJobsRow, error)
	ClaimStagingCleanupItems(ctx context.Context, arg ClaimStagingCleanupItemsParams) ([]ClaimStagingCleanupItemsRow, error)
	ClaimStaleUploadingVOD(ctx context.Context, arg ClaimStaleUploadingVODParams) (int64, error)
	ClaimStreamCleanupObligations(ctx context.Context, arg ClaimStreamCleanupObligationsParams) ([]ClaimStreamCleanupObligationsRow, error)
	ClaimStuckIncompleteThumbnailAttempts(ctx context.Context, arg ClaimStuckIncompleteThumbnailAttemptsParams) ([]ClaimStuckIncompleteThumbnailAttemptsRow, error)
	ClaimUnprojectedPublishedThumbnailAttempts(ctx context.Context, arg ClaimUnprojectedPublishedThumbnailAttemptsParams) ([]ClaimUnprojectedPublishedThumbnailAttemptsRow, error)
	ClaimUnstartedDVRIntents(ctx context.Context, arg ClaimUnstartedDVRIntentsParams) ([]ClaimUnstartedDVRIntentsRow, error)
	ClaimVodAbort(ctx context.Context, arg ClaimVodAbortParams) (int64, error)
	ClaimVodCompletion(ctx context.Context, arg ClaimVodCompletionParams) (int64, error)
	ClearCurrentChaptersForInactiveDVRs(ctx context.Context) (int64, error)
	ClearDVRStopObligation(ctx context.Context, arg ClearDVRStopObligationParams) error
	ClearDtshAttempt(ctx context.Context, arg ClearDtshAttemptParams) (string, error)
	ClearThumbnailReassert(ctx context.Context, attemptID string) error
	ClipNeedsDtshSync(ctx context.Context, artifactHash string) (bool, error)
	CloseCurrentDVRChapterForArtifact(ctx context.Context, artifactHash string) (int64, error)
	CloseDVRChapter(ctx context.Context, chapterID string) (int64, error)
	CloseIngestSession(ctx context.Context, arg CloseIngestSessionParams) (CloseIngestSessionRow, error)
	ClosePreviousCurrentDVRChapters(ctx context.Context, arg ClosePreviousCurrentDVRChaptersParams) (int64, error)
	CommitArtifactCreationCommand(ctx context.Context, arg CommitArtifactCreationCommandParams) (int64, error)
	CommitDispatchedProcessingJob(ctx context.Context, arg CommitDispatchedProcessingJobParams) (int64, error)
	CompleteDVRFinalization(ctx context.Context, arg CompleteDVRFinalizationParams) (int64, error)
	CompleteIncrementalDtshSync(ctx context.Context, arg CompleteIncrementalDtshSyncParams) (int64, error)
	CompleteMainArtifactSync(ctx context.Context, arg CompleteMainArtifactSyncParams) (int64, error)
	CompleteOfflineEffect(ctx context.Context, arg CompleteOfflineEffectParams) (int64, error)
	CompleteProcessingJob(ctx context.Context, arg CompleteProcessingJobParams) error
	ConfirmSourceProjection(ctx context.Context, arg ConfirmSourceProjectionParams) (int64, error)
	ConsumeTerminalArtifactCreationCommand(ctx context.Context, arg ConsumeTerminalArtifactCreationCommandParams) error
	CountDVRFinalSegments(ctx context.Context, artifactHash string) (CountDVRFinalSegmentsRow, error)
	CountOtherCompleteArtifactCopies(ctx context.Context, arg CountOtherCompleteArtifactCopiesParams) (int64, error)
	CountStaleUnconsumedCreationCommands(ctx context.Context, retentionSeconds int64) (int64, error)
	CountUnreclaimedDVRSegments(ctx context.Context, arg CountUnreclaimedDVRSegmentsParams) (int64, error)
	CountUnverifiedThumbnailObjects(ctx context.Context, attemptID string) (int64, error)
	DVRNeedsDtshSync(ctx context.Context, artifactHash string) (bool, error)
	DVRRecordingTenant(ctx context.Context, internalName sql.NullString) (string, error)
	DeleteArtifactNode(ctx context.Context, arg DeleteArtifactNodeParams) error
	DeleteClipCatalog(ctx context.Context, arg DeleteClipCatalogParams) (int64, error)
	DeleteConsumedCreationCommands(ctx context.Context, arg DeleteConsumedCreationCommandsParams) (int64, error)
	DeleteDVRChapter(ctx context.Context, chapterID string) error
	DeleteDVRChapterRowsForTenant(ctx context.Context, arg DeleteDVRChapterRowsForTenantParams) error
	DeleteFreezePublicationLedgerKeys(ctx context.Context, objectKeys []string) error
	DeleteFreezePublicationLedgerRow(ctx context.Context, objectKey string) error
	DeleteOpenDVRChapters(ctx context.Context, artifactHash string) error
	DeletePurgedArtifact(ctx context.Context, arg DeletePurgedArtifactParams) error
	DeleteStagingCleanupItem(ctx context.Context, arg DeleteStagingCleanupItemParams) (int64, error)
	DeleteStaleOrphanedArtifactNodes(ctx context.Context) (int64, error)
	DeleteSupersededThumbnailAttempt(ctx context.Context, arg DeleteSupersededThumbnailAttemptParams) (int64, error)
	DeleteThumbnailActivePointer(ctx context.Context, arg DeleteThumbnailActivePointerParams) error
	DeleteThumbnailAssignments(ctx context.Context, arg DeleteThumbnailAssignmentsParams) error
	DeleteVODMetadata(ctx context.Context, artifactHash string) error
	DeleteVodMetadata(ctx context.Context, artifactHash string) error
	DequeueThumbnailCleanup(ctx context.Context, objectKey string) error
	DtshSyncedForArtifact(ctx context.Context, artifactHash string) (bool, error)
	EndSupersededPIDIngestSession(ctx context.Context, arg EndSupersededPIDIngestSessionParams) error
	EnqueueAdmissionEffect(ctx context.Context, arg EnqueueAdmissionEffectParams) error
	EnqueueArtifactEvent(ctx context.Context, arg EnqueueArtifactEventParams) error
	EnqueueOfflineEffect(ctx context.Context, arg EnqueueOfflineEffectParams) error
	EnqueueOwnedStagingCleanup(ctx context.Context, arg EnqueueOwnedStagingCleanupParams) error
	EnqueueStagingCleanup(ctx context.Context, arg EnqueueStagingCleanupParams) error
	EnqueueThumbnailCleanup(ctx context.Context, arg EnqueueThumbnailCleanupParams) error
	EnqueueThumbnailCleanupDeferred(ctx context.Context, arg EnqueueThumbnailCleanupDeferredParams) error
	EnsureChapterPlaybackArtifact(ctx context.Context, arg EnsureChapterPlaybackArtifactParams) error
	EnterThumbnailPublishing(ctx context.Context, arg EnterThumbnailPublishingParams) (int64, error)
	EstablishCellStorageIdentity(ctx context.Context, arg EstablishCellStorageIdentityParams) error
	ExistingArtifactHashes(ctx context.Context, dollar_1 []string) ([]string, error)
	ExpireArtifactIfStillEligible(ctx context.Context, arg ExpireArtifactIfStillEligibleParams) (string, error)
	ExpireStrandedCreationCommands(ctx context.Context, arg ExpireStrandedCreationCommandsParams) (int64, error)
	FailAdmissionEffect(ctx context.Context, arg FailAdmissionEffectParams) error
	FailDVRChapter(ctx context.Context, arg FailDVRChapterParams) (sql.NullString, error)
	FailDVRChapterArtifact(ctx context.Context, arg FailDVRChapterArtifactParams) (string, error)
	FailDVRFinalization(ctx context.Context, arg FailDVRFinalizationParams) (int64, error)
	FailDVRIntent(ctx context.Context, arg FailDVRIntentParams) error
	FailDtshAttempt(ctx context.Context, arg FailDtshAttemptParams) (string, error)
	FailExhaustedProcessingJob(ctx context.Context, arg FailExhaustedProcessingJobParams) (FailExhaustedProcessingJobRow, error)
	FailExpiredThumbnailAttempt(ctx context.Context, attemptID string) (int64, error)
	FailMainArtifactSync(ctx context.Context, arg FailMainArtifactSyncParams) error
	FailOfflineEffect(ctx context.Context, arg FailOfflineEffectParams) error
	FailStagingCleanupItem(ctx context.Context, arg FailStagingCleanupItemParams) error
	FailStreamCleanupObligation(ctx context.Context, arg FailStreamCleanupObligationParams) error
	FailThumbnailAttempt(ctx context.Context, attemptID string) error
	FailVodCompletion(ctx context.Context, arg FailVodCompletionParams) (int64, error)
	FederatedArtifactStreamID(ctx context.Context, arg FederatedArtifactStreamIDParams) (string, error)
	FillMigratedArtifactMetadata(ctx context.Context, arg FillMigratedArtifactMetadataParams) error
	FinalizeChapterPlaybackArtifact(ctx context.Context, arg FinalizeChapterPlaybackArtifactParams) (int64, error)
	FinalizeStreamCleanupObligation(ctx context.Context, arg FinalizeStreamCleanupObligationParams) (int64, error)
	FinalizeVodAbort(ctx context.Context, arg FinalizeVodAbortParams) (int64, error)
	FindActiveDVRForStream(ctx context.Context, arg FindActiveDVRForStreamParams) (FindActiveDVRForStreamRow, error)
	FindActiveProcessingJob(ctx context.Context, arg FindActiveProcessingJobParams) (string, error)
	FindArtifactHashForSession(ctx context.Context, arg FindArtifactHashForSessionParams) (string, error)
	FindBestDVRChapterOverlap(ctx context.Context, arg FindBestDVRChapterOverlapParams) (FindBestDVRChapterOverlapRow, error)
	FindDVRStartRaceWinner(ctx context.Context, arg FindDVRStartRaceWinnerParams) (FindDVRStartRaceWinnerRow, error)
	FindLatestDVRForStream(ctx context.Context, arg FindLatestDVRForStreamParams) (FindLatestDVRForStreamRow, error)
	GetAbortableVodUpload(ctx context.Context, arg GetAbortableVodUploadParams) (GetAbortableVodUploadRow, error)
	GetActiveObjectKeyBackfillCursor(ctx context.Context) (string, error)
	GetArtifactCachedAt(ctx context.Context, artifactHash string) (time.Time, error)
	GetArtifactCreationCommandAckState(ctx context.Context, arg GetArtifactCreationCommandAckStateParams) (GetArtifactCreationCommandAckStateRow, error)
	GetArtifactCreationCommandStatus(ctx context.Context, arg GetArtifactCreationCommandStatusParams) (GetArtifactCreationCommandStatusRow, error)
	GetArtifactOrigin(ctx context.Context, artifactHash string) (GetArtifactOriginRow, error)
	GetArtifactPlacementTenant(ctx context.Context, artifactHash string) (string, error)
	GetArtifactPublicationPointers(ctx context.Context, arg GetArtifactPublicationPointersParams) (GetArtifactPublicationPointersRow, error)
	GetArtifactRelayDescriptor(ctx context.Context, artifactHash string) (GetArtifactRelayDescriptorRow, error)
	GetArtifactStatusForTenant(ctx context.Context, arg GetArtifactStatusForTenantParams) (sql.NullString, error)
	GetArtifactSyncInfo(ctx context.Context, artifactHash string) (GetArtifactSyncInfoRow, error)
	GetArtifactSyncObjectKey(ctx context.Context, arg GetArtifactSyncObjectKeyParams) (sql.NullString, error)
	GetArtifactTenantText(ctx context.Context, artifactHash string) (string, error)
	GetArtifactThumbnailMarkContext(ctx context.Context, artifactHash string) (GetArtifactThumbnailMarkContextRow, error)
	GetAssetTombstone(ctx context.Context, assetKey string) (int32, error)
	GetBillingAttributionCursor(ctx context.Context) (GetBillingAttributionCursorRow, error)
	GetCellStorageIdentity(ctx context.Context) (GetCellStorageIdentityRow, error)
	GetChapterArtifactLifecycleIdentity(ctx context.Context, chapterID string) (GetChapterArtifactLifecycleIdentityRow, error)
	GetChapterArtifactResolution(ctx context.Context, artifactHash string) (GetChapterArtifactResolutionRow, error)
	GetChapterArtifactRouting(ctx context.Context, artifactHash string) (GetChapterArtifactRoutingRow, error)
	GetChapterParentDVR(ctx context.Context, artifactHash string) (GetChapterParentDVRRow, error)
	GetClipForDeletion(ctx context.Context, arg GetClipForDeletionParams) (GetClipForDeletionRow, error)
	GetClipFulfilledSourceParams(ctx context.Context, arg GetClipFulfilledSourceParamsParams) (sql.NullString, error)
	GetCompletableVodUpload(ctx context.Context, arg GetCompletableVodUploadParams) (GetCompletableVodUploadRow, error)
	GetCurrentDVRChapter(ctx context.Context, artifactHash string) (GetCurrentDVRChapterRow, error)
	GetDVRArtifactStatus(ctx context.Context, artifactHash string) (sql.NullString, error)
	GetDVRArtifactTenantID(ctx context.Context, artifactHash string) (string, error)
	GetDVRChapter(ctx context.Context, chapterID string) (GetDVRChapterRow, error)
	GetDVRChapterMaxRange(ctx context.Context, artifactHash string) (sql.NullInt32, error)
	GetDVRChapterPolicy(ctx context.Context, artifactHash string) (GetDVRChapterPolicyRow, error)
	GetDVRChaptersByID(ctx context.Context, dollar_1 []string) ([]GetDVRChaptersByIDRow, error)
	GetDVRDispatchOwner(ctx context.Context, arg GetDVRDispatchOwnerParams) (string, error)
	GetDVRDispatchStatus(ctx context.Context, artifactHash string) (sql.NullString, error)
	GetDVREffectiveWindowSeconds(ctx context.Context, artifactHash string) (sql.NullInt32, error)
	GetDVRForDeletion(ctx context.Context, arg GetDVRForDeletionParams) (GetDVRForDeletionRow, error)
	GetDVRForStop(ctx context.Context, arg GetDVRForStopParams) (GetDVRForStopRow, error)
	GetDVRLifecycleContext(ctx context.Context, artifactHash string) (GetDVRLifecycleContextRow, error)
	GetDVROwnerTenant(ctx context.Context, artifactHash string) (string, error)
	GetDVRParentArtifactStatus(ctx context.Context, artifactHash string) (sql.NullString, error)
	GetDVRReportAuthorization(ctx context.Context, arg GetDVRReportAuthorizationParams) (GetDVRReportAuthorizationRow, error)
	GetDVRRetentionDays(ctx context.Context, artifactHash string) (sql.NullInt32, error)
	GetDVRRetentionUntil(ctx context.Context, artifactHash string) (sql.NullTime, error)
	GetDVRSegmentProgress(ctx context.Context, arg GetDVRSegmentProgressParams) (GetDVRSegmentProgressRow, error)
	GetDVRStartDispatch(ctx context.Context, arg GetDVRStartDispatchParams) (string, error)
	GetDVRStatus(ctx context.Context, arg GetDVRStatusParams) (sql.NullString, error)
	GetDVRTenantAndStream(ctx context.Context, artifactHash string) (GetDVRTenantAndStreamRow, error)
	GetDVRThumbnailTargetByChapterID(ctx context.Context, chapterID string) (GetDVRThumbnailTargetByChapterIDRow, error)
	GetDVRThumbnailTargetByInternalName(ctx context.Context, internalName sql.NullString) (GetDVRThumbnailTargetByInternalNameRow, error)
	GetDVRWindowSeconds(ctx context.Context, artifactHash string) (sql.NullInt32, error)
	GetExistingClipStatus(ctx context.Context, arg GetExistingClipStatusParams) (sql.NullString, error)
	GetExistingDVRSegment(ctx context.Context, arg GetExistingDVRSegmentParams) (GetExistingDVRSegmentRow, error)
	GetExistingVodUpload(ctx context.Context, arg GetExistingVodUploadParams) (GetExistingVodUploadRow, error)
	GetFederatedArtifactDescriptor(ctx context.Context, arg GetFederatedArtifactDescriptorParams) (GetFederatedArtifactDescriptorRow, error)
	GetFinalizedArtifactEndedAt(ctx context.Context, arg GetFinalizedArtifactEndedAtParams) (sql.NullTime, error)
	GetFreezeArtifactMetadata(ctx context.Context, arg GetFreezeArtifactMetadataParams) (GetFreezeArtifactMetadataRow, error)
	GetFreezePublicationLedgerCursor(ctx context.Context) (string, error)
	GetFreshRelayOriginNode(ctx context.Context, artifactHash string) (GetFreshRelayOriginNodeRow, error)
	GetLatestDVRChapterBefore(ctx context.Context, arg GetLatestDVRChapterBeforeParams) (GetLatestDVRChapterBeforeRow, error)
	GetNextDVRSegmentSequence(ctx context.Context, artifactHash string) (int64, error)
	GetNodeComponentVersion(ctx context.Context, arg GetNodeComponentVersionParams) (string, error)
	GetNodeUpdatePhase(ctx context.Context, nodeID string) (string, error)
	GetNodeUpdatePhaseForRelease(ctx context.Context, arg GetNodeUpdatePhaseForReleaseParams) (string, error)
	GetNodeUpdateProgress(ctx context.Context, nodeID string) (GetNodeUpdateProgressRow, error)
	GetOpenIngestSessionCluster(ctx context.Context, arg GetOpenIngestSessionClusterParams) (string, error)
	GetPersistedNodeOutputs(ctx context.Context, nodeID string) (GetPersistedNodeOutputsRow, error)
	GetPlayableChapterArtifactResolution(ctx context.Context, artifactHash string) (GetPlayableChapterArtifactResolutionRow, error)
	GetPlaybackArtifact(ctx context.Context, arg GetPlaybackArtifactParams) (GetPlaybackArtifactRow, error)
	GetProcessingArtifactLifecycle(ctx context.Context, artifactHash string) (GetProcessingArtifactLifecycleRow, error)
	GetProcessingJobAuthContext(ctx context.Context, artifactHash string) (GetProcessingJobAuthContextRow, error)
	GetRegistryArtifactByHash(ctx context.Context, artifactHash string) (GetRegistryArtifactByHashRow, error)
	GetRegistryArtifactByInternalName(ctx context.Context, internalName sql.NullString) (GetRegistryArtifactByInternalNameRow, error)
	GetRegistryProcessingJob(ctx context.Context, artifactHash sql.NullString) (GetRegistryProcessingJobRow, error)
	GetRelayArtifact(ctx context.Context, artifactHash string) (GetRelayArtifactRow, error)
	GetRelayVodMetadata(ctx context.Context, artifactHash string) (GetRelayVodMetadataRow, error)
	GetSyncCompletionAttempt(ctx context.Context, arg GetSyncCompletionAttemptParams) (GetSyncCompletionAttemptRow, error)
	GetTenantDVRChapterMaxRange(ctx context.Context, arg GetTenantDVRChapterMaxRangeParams) (sql.NullInt32, error)
	GetThumbnailActiveVersion(ctx context.Context, assetKey string) (string, error)
	GetThumbnailAssetBackendSnapshot(ctx context.Context, arg GetThumbnailAssetBackendSnapshotParams) (GetThumbnailAssetBackendSnapshotRow, error)
	GetThumbnailAssignment(ctx context.Context, attemptID string) (GetThumbnailAssignmentRow, error)
	GetThumbnailPointerState(ctx context.Context, assetKey string) (GetThumbnailPointerStateRow, error)
	GetUniqueDVRRecordingOrigin(ctx context.Context, arg GetUniqueDVRRecordingOriginParams) (string, error)
	GetVodAsset(ctx context.Context, artifactHash string) (GetVodAssetRow, error)
	GetVodCompletionContract(ctx context.Context, artifactHash string) (GetVodCompletionContractRow, error)
	GetVodForDeletion(ctx context.Context, arg GetVodForDeletionParams) (GetVodForDeletionRow, error)
	GetVodUploadStatusRow(ctx context.Context, arg GetVodUploadStatusRowParams) (GetVodUploadStatusRowRow, error)
	HasActiveIngestSession(ctx context.Context, arg HasActiveIngestSessionParams) (bool, error)
	HasActiveStreamIngestSession(ctx context.Context, arg HasActiveStreamIngestSessionParams) (bool, error)
	HealLostDVRSegment(ctx context.Context, arg HealLostDVRSegmentParams) error
	IngestCloseTombstoneExists(ctx context.Context, arg IngestCloseTombstoneExistsParams) (bool, error)
	IngestGenerationEnded(ctx context.Context, arg IngestGenerationEndedParams) (bool, error)
	InsertAcceptedArtifactCreationCommand(ctx context.Context, arg InsertAcceptedArtifactCreationCommandParams) error
	InsertClosedDVRChapter(ctx context.Context, arg InsertClosedDVRChapterParams) error
	InsertDiscoveredArtifact(ctx context.Context, arg InsertDiscoveredArtifactParams) error
	InsertIngestCloseTombstone(ctx context.Context, arg InsertIngestCloseTombstoneParams) error
	InsertIngestSession(ctx context.Context, arg InsertIngestSessionParams) (string, error)
	InsertMigratedArtifactMetadata(ctx context.Context, arg InsertMigratedArtifactMetadataParams) (int64, error)
	InsertMintArtifactShell(ctx context.Context, arg InsertMintArtifactShellParams) error
	InsertPendingDVRSegment(ctx context.Context, arg InsertPendingDVRSegmentParams) error
	InsertProcessingJob(ctx context.Context, arg InsertProcessingJobParams) error
	InsertQueuedClipArtifact(ctx context.Context, arg InsertQueuedClipArtifactParams) error
	InsertRequestedDVRArtifact(ctx context.Context, arg InsertRequestedDVRArtifactParams) error
	InsertStreamCleanupObligation(ctx context.Context, arg InsertStreamCleanupObligationParams) (int64, error)
	InsertThumbnailAssignment(ctx context.Context, arg InsertThumbnailAssignmentParams) error
	InsertThumbnailTaskObject(ctx context.Context, arg InsertThumbnailTaskObjectParams) error
	InsertUploadingVodArtifact(ctx context.Context, arg InsertUploadingVodArtifactParams) error
	InsertVodMultipartMetadata(ctx context.Context, arg InsertVodMultipartMetadataParams) error
	IsArtifactSynced(ctx context.Context, artifactHash string) (bool, error)
	LatestActiveProcessingConfig(ctx context.Context, artifactHash sql.NullString) (sql.NullString, error)
	LatestActiveProcessingSourceURL(ctx context.Context, artifactHash sql.NullString) (sql.NullString, error)
	LatestArtifactNodeID(ctx context.Context, artifactHash string) (string, error)
	LatestArtifactNodeWithSize(ctx context.Context, artifactHash string) (LatestArtifactNodeWithSizeRow, error)
	LatestLiveOriginNode(ctx context.Context, artifactHash string) (LatestLiveOriginNodeRow, error)
	LatestPlayableDVRChapterID(ctx context.Context, artifactHash string) (sql.NullString, error)
	LatestRecordingNode(ctx context.Context, artifactHash string) (string, error)
	ListActiveArtifactNodes(ctx context.Context, artifactHash string) ([]string, error)
	ListActiveClips(ctx context.Context) ([]ListActiveClipsRow, error)
	ListActiveDVRChapterPolicies(ctx context.Context) ([]ListActiveDVRChapterPoliciesRow, error)
	ListActiveDVRRecordingNodes(ctx context.Context, artifactHash string) ([]string, error)
	ListActiveIngestSessionClaims(ctx context.Context) ([]ListActiveIngestSessionClaimsRow, error)
	ListActiveObjectKeyBackfillRows(ctx context.Context, arg ListActiveObjectKeyBackfillRowsParams) ([]ListActiveObjectKeyBackfillRowsRow, error)
	ListAdminArtifacts(ctx context.Context, limit int32) ([]ListAdminArtifactsRow, error)
	ListAllDVR(ctx context.Context) ([]ListAllDVRRow, error)
	ListAllDVRSegmentsForArtifact(ctx context.Context, artifactHash string) ([]FoghornDvrSegment, error)
	ListAllNodeArtifacts(ctx context.Context) ([]ListAllNodeArtifactsRow, error)
	ListAllNodes(ctx context.Context) ([]ListAllNodesRow, error)
	ListArtifactCachedNodes(ctx context.Context, artifactHash string) ([]ListArtifactCachedNodesRow, error)
	ListArtifactNodeIDs(ctx context.Context, artifactHash string) ([]string, error)
	ListArtifactsForCatalogProjection(ctx context.Context, arg ListArtifactsForCatalogProjectionParams) ([]ListArtifactsForCatalogProjectionRow, error)
	ListAssetThumbnailObjectKeys(ctx context.Context, arg ListAssetThumbnailObjectKeysParams) ([]ListAssetThumbnailObjectKeysRow, error)
	ListColdStorageUsage(ctx context.Context) ([]ListColdStorageUsageRow, error)
	ListDVRChaptersForArtifact(ctx context.Context, arg ListDVRChaptersForArtifactParams) ([]ListDVRChaptersForArtifactRow, error)
	ListDVRChaptersNeedingFinalization(ctx context.Context, arg ListDVRChaptersNeedingFinalizationParams) ([]ListDVRChaptersNeedingFinalizationRow, error)
	ListDVRChaptersNeedingReclaim(ctx context.Context, arg ListDVRChaptersNeedingReclaimParams) ([]ListDVRChaptersNeedingReclaimRow, error)
	ListDVRCoverageSegments(ctx context.Context, arg ListDVRCoverageSegmentsParams) ([]ListDVRCoverageSegmentsRow, error)
	ListDVRDispatchNodes(ctx context.Context, artifactHash string) ([]ListDVRDispatchNodesRow, error)
	ListDVRSegmentsForRange(ctx context.Context, arg ListDVRSegmentsForRangeParams) ([]FoghornDvrSegment, error)
	ListDVRSegmentsOwnedByChapter(ctx context.Context, arg ListDVRSegmentsOwnedByChapterParams) ([]FoghornDvrSegment, error)
	ListDeletedClipNodes(ctx context.Context, maxAge string) ([]ListDeletedClipNodesRow, error)
	ListDeletedDVRNodes(ctx context.Context, maxAge string) ([]ListDeletedDVRNodesRow, error)
	ListDeletedDVRParentsWithChapters(ctx context.Context, limit int32) ([]ListDeletedDVRParentsWithChaptersRow, error)
	ListDeletedVODNodes(ctx context.Context, maxAge string) ([]ListDeletedVODNodesRow, error)
	ListEvictableDVRSegments(ctx context.Context, arg ListEvictableDVRSegmentsParams) ([]string, error)
	ListExhaustedProcessingJobIDs(ctx context.Context, arg ListExhaustedProcessingJobIDsParams) ([]string, error)
	ListExpiredArtifacts(ctx context.Context, retentionDays int32) ([]ListExpiredArtifactsRow, error)
	ListExpiredThumbnailAttemptIDs(ctx context.Context, limit int32) ([]string, error)
	ListFailedArtifactsForFreezeRetry(ctx context.Context, limit int32) ([]ListFailedArtifactsForFreezeRetryRow, error)
	ListFederatedTenantArtifacts(ctx context.Context, tenantID string) ([]ListFederatedTenantArtifactsRow, error)
	ListFinalizedChaptersMissingDTSH(ctx context.Context) ([]ListFinalizedChaptersMissingDTSHRow, error)
	ListNeverProjectedIngestSessions(ctx context.Context, olderThanMs int64) ([]ListNeverProjectedIngestSessionsRow, error)
	ListNodeComponentVersions(ctx context.Context, nodeID string) ([]ListNodeComponentVersionsRow, error)
	ListNodeComponents(ctx context.Context, nodeID string) ([]ListNodeComponentsRow, error)
	ListNodeMaintenance(ctx context.Context) ([]ListNodeMaintenanceRow, error)
	ListOpenIngestSessions(ctx context.Context) ([]ListOpenIngestSessionsRow, error)
	ListOriginNodes(ctx context.Context, artifactHash string) ([]string, error)
	ListPendingArtifactsForFreeze(ctx context.Context, limit int32) ([]ListPendingArtifactsForFreezeRow, error)
	ListPendingDVRSegments(ctx context.Context, arg ListPendingDVRSegmentsParams) ([]FoghornDvrSegment, error)
	ListPublishingThumbnailAttempts(ctx context.Context, limit int32) ([]ListPublishingThumbnailAttemptsRow, error)
	ListPurgeableAdmissionEffectFences(ctx context.Context, fences json.RawMessage) ([]ListPurgeableAdmissionEffectFencesRow, error)
	ListPurgeableArtifacts(ctx context.Context, retentionInterval string) ([]ListPurgeableArtifactsRow, error)
	ListPurgeableLocalArtifacts(ctx context.Context, arg ListPurgeableLocalArtifactsParams) ([]ListPurgeableLocalArtifactsRow, error)
	ListRecentNodeLifecycles(ctx context.Context) ([]ListRecentNodeLifecyclesRow, error)
	ListRecentProcessingJobs(ctx context.Context, limit int32) ([]ListRecentProcessingJobsRow, error)
	ListReclaimableDVRSegments(ctx context.Context, arg ListReclaimableDVRSegmentsParams) ([]ListReclaimableDVRSegmentsRow, error)
	ListStaleAbortingVODs(ctx context.Context, arg ListStaleAbortingVODsParams) ([]ListStaleAbortingVODsRow, error)
	ListStaleCompletingVODs(ctx context.Context, arg ListStaleCompletingVODsParams) ([]ListStaleCompletingVODsRow, error)
	ListStaleDVRStartObligations(ctx context.Context, arg ListStaleDVRStartObligationsParams) ([]ListStaleDVRStartObligationsRow, error)
	ListStaleFreezePublicationLedgerRows(ctx context.Context, arg ListStaleFreezePublicationLedgerRowsParams) ([]ListStaleFreezePublicationLedgerRowsRow, error)
	ListStaleUploadingVODs(ctx context.Context) ([]ListStaleUploadingVODsRow, error)
	ListStuckIncompleteThumbnailAttemptIDs(ctx context.Context, arg ListStuckIncompleteThumbnailAttemptIDsParams) ([]string, error)
	ListSupersededThumbnailAttemptIDs(ctx context.Context, arg ListSupersededThumbnailAttemptIDsParams) ([]string, error)
	ListTenantArtifactNodes(ctx context.Context, arg ListTenantArtifactNodesParams) ([]string, error)
	ListTenantArtifactSessionNames(ctx context.Context, tenantID string) ([]sql.NullString, error)
	ListThumbnailDestinations(ctx context.Context, arg ListThumbnailDestinationsParams) ([]ListThumbnailDestinationsRow, error)
	ListThumbnailObjects(ctx context.Context, attemptID string) ([]ListThumbnailObjectsRow, error)
	ListThumbnailStagingKeys(ctx context.Context, attemptID string) ([]string, error)
	ListThumbnailVersionKeys(ctx context.Context, attemptID string) ([]string, error)
	ListUnattributedStoragePairs(ctx context.Context, arg ListUnattributedStoragePairsParams) ([]ListUnattributedStoragePairsRow, error)
	ListUnemittedArtifactNodeKeys(ctx context.Context, limit int32) ([]ListUnemittedArtifactNodeKeysRow, error)
	LocalArtifactTenant(ctx context.Context, artifactHash string) (string, error)
	LockActiveStreamIngestSession(ctx context.Context, arg LockActiveStreamIngestSessionParams) (LockActiveStreamIngestSessionRow, error)
	LockArtifactNodeRole(ctx context.Context, arg LockArtifactNodeRoleParams) (string, error)
	LockArtifactNodeState(ctx context.Context, arg LockArtifactNodeStateParams) (LockArtifactNodeStateRow, error)
	LockArtifactPlacementParent(ctx context.Context, artifactHash string) error
	LockChapterFinalizeArtifact(ctx context.Context, chapterID string) (LockChapterFinalizeArtifactRow, error)
	LockDVRChapterMutation(ctx context.Context, hashtext string) error
	LockDVRDispatchOwner(ctx context.Context, arg LockDVRDispatchOwnerParams) (string, error)
	LockDVRProgressArtifact(ctx context.Context, artifactHash string) (LockDVRProgressArtifactRow, error)
	LockDVRRecordingOrigin(ctx context.Context, arg LockDVRRecordingOriginParams) (LockDVRRecordingOriginRow, error)
	LockDVRSegmentParent(ctx context.Context, arg LockDVRSegmentParentParams) (sql.NullString, error)
	LockIngestSessionByTrigger(ctx context.Context, arg LockIngestSessionByTriggerParams) (LockIngestSessionByTriggerRow, error)
	LockIngestStream(ctx context.Context, hashtext string) error
	LockOfflineEffectLease(ctx context.Context, arg LockOfflineEffectLeaseParams) (bool, error)
	LockProcessingArtifactForCompletion(ctx context.Context, jobID string) (LockProcessingArtifactForCompletionRow, error)
	LockProcessingJobForCompletion(ctx context.Context, jobID string) (LockProcessingJobForCompletionRow, error)
	LockProcessingJobForFailure(ctx context.Context, jobID string) (LockProcessingJobForFailureRow, error)
	LockProcessingJobIdentity(ctx context.Context, arg LockProcessingJobIdentityParams) error
	LockPublishableThumbnailAttempt(ctx context.Context, arg LockPublishableThumbnailAttemptParams) (LockPublishableThumbnailAttemptRow, error)
	LockSyncFailureAttempt(ctx context.Context, arg LockSyncFailureAttemptParams) (LockSyncFailureAttemptRow, error)
	LockThumbnailAsset(ctx context.Context, arg LockThumbnailAssetParams) error
	LockThumbnailParentTerminal(ctx context.Context, artifactHash string) (bool, error)
	LockUnemittedArtifactNode(ctx context.Context, arg LockUnemittedArtifactNodeParams) (LockUnemittedArtifactNodeRow, error)
	LookupDVRSegmentsByName(ctx context.Context, arg LookupDVRSegmentsByNameParams) ([]FoghornDvrSegment, error)
	MarkAbortingVODDeleted(ctx context.Context, arg MarkAbortingVODDeletedParams) (int64, error)
	MarkAdmissionActivationDone(ctx context.Context, arg MarkAdmissionActivationDoneParams) error
	MarkAdmissionDrainDone(ctx context.Context, arg MarkAdmissionDrainDoneParams) error
	MarkArtifactEventCompleted(ctx context.Context, id string) error
	MarkArtifactEventsClaimed(ctx context.Context, ids []string) error
	MarkArtifactHasThumbnails(ctx context.Context, arg MarkArtifactHasThumbnailsParams) error
	MarkArtifactS3OnlyWhenUnhosted(ctx context.Context, artifactHash string) error
	MarkArtifactSynced(ctx context.Context, arg MarkArtifactSyncedParams) error
	MarkArtifactThumbnailPresent(ctx context.Context, artifactHash string) error
	MarkCompletingVODFailed(ctx context.Context, arg MarkCompletingVODFailedParams) (int64, error)
	MarkCompletingVODProcessing(ctx context.Context, arg MarkCompletingVODProcessingParams) (int64, error)
	MarkDVRChapterFinalized(ctx context.Context, arg MarkDVRChapterFinalizedParams) (int64, error)
	MarkDVRChapterFrozen(ctx context.Context, chapterID string) error
	MarkDVRChapterReclaimStarted(ctx context.Context, arg MarkDVRChapterReclaimStartedParams) (int64, error)
	MarkDVRChapterReclaimed(ctx context.Context, chapterID string) error
	MarkDVRSegmentDropped(ctx context.Context, arg MarkDVRSegmentDroppedParams) (int64, error)
	MarkDVRSegmentOrphanUnreachable(ctx context.Context, arg MarkDVRSegmentOrphanUnreachableParams) error
	MarkDVRSegmentReclaimed(ctx context.Context, arg MarkDVRSegmentReclaimedParams) error
	MarkDVRSegmentUploaded(ctx context.Context, arg MarkDVRSegmentUploadedParams) error
	MarkDVRStarting(ctx context.Context, arg MarkDVRStartingParams) (int64, error)
	MarkDVRStopPending(ctx context.Context, arg MarkDVRStopPendingParams) error
	MarkExhaustedArtifactFailed(ctx context.Context, arg MarkExhaustedArtifactFailedParams) (int64, error)
	MarkFailedArtifactsDeleted(ctx context.Context, retentionInterval string) (int64, error)
	MarkProcessingArtifactFailed(ctx context.Context, arg MarkProcessingArtifactFailedParams) (int64, error)
	MarkProcessingArtifactReady(ctx context.Context, arg MarkProcessingArtifactReadyParams) (int64, error)
	MarkProcessingArtifactStarted(ctx context.Context, arg MarkProcessingArtifactStartedParams) (int64, error)
	MarkProcessingJobFailed(ctx context.Context, arg MarkProcessingJobFailedParams) error
	MarkQueuedClipArtifact(ctx context.Context, arg MarkQueuedClipArtifactParams) error
	MarkRemainingDVRSegmentsLost(ctx context.Context, arg MarkRemainingDVRSegmentsLostParams) (int64, error)
	MarkStoragePairLocallyAttributed(ctx context.Context, arg MarkStoragePairLocallyAttributedParams) (int64, error)
	MarkThumbnailProjected(ctx context.Context, arg MarkThumbnailProjectedParams) (int64, error)
	MarkThumbnailPublished(ctx context.Context, attemptID string) (int64, error)
	MarkThumbnailSuperseded(ctx context.Context, attemptID string) error
	NextSourceProjectionRevision(ctx context.Context) (int64, error)
	NodeHoldsLiveArtifactCopy(ctx context.Context, arg NodeHoldsLiveArtifactCopyParams) (bool, error)
	OrphanGloballyStaleArtifactNodes(ctx context.Context) ([]OrphanGloballyStaleArtifactNodesRow, error)
	OrphanNodeArtifacts(ctx context.Context, nodeID string) ([]OrphanNodeArtifactsRow, error)
	OrphanStaleReportedArtifactNodes(ctx context.Context, nodeID string) ([]OrphanStaleReportedArtifactNodesRow, error)
	OverrideFinalizedArtifactRetention(ctx context.Context, arg OverrideFinalizedArtifactRetentionParams) (int64, error)
	PersistSourceProjectionRevision(ctx context.Context, arg PersistSourceProjectionRevisionParams) error
	PersistVodCompletionContract(ctx context.Context, arg PersistVodCompletionContractParams) error
	ProbeCurrentSourceProjection(ctx context.Context, arg ProbeCurrentSourceProjectionParams) (ProbeCurrentSourceProjectionRow, error)
	ProjectProcessingArtifactStatus(ctx context.Context, arg ProjectProcessingArtifactStatusParams) error
	PropagateDVRChapterRetention(ctx context.Context, arg PropagateDVRChapterRetentionParams) (int64, error)
	PurgeExpiredCloseTombstones(ctx context.Context, olderThanSeconds float64) (int64, error)
	PurgeStaleArtifactNodes(ctx context.Context) (int64, error)
	PurgeTerminalAdmissionEffects(ctx context.Context, olderThanMs int64) (int64, error)
	PurgeTerminalOfflineEffects(ctx context.Context, olderThanMs int64) (int64, error)
	QuarantineCatalogProjection(ctx context.Context, arg QuarantineCatalogProjectionParams) error
	ReadAdmissionLegsLocked(ctx context.Context, arg ReadAdmissionLegsLockedParams) (ReadAdmissionLegsLockedRow, error)
	ReadArtifactCreationCommandIdentity(ctx context.Context, arg ReadArtifactCreationCommandIdentityParams) (ReadArtifactCreationCommandIdentityRow, error)
	ReapStreamEndIngestSessions(ctx context.Context, arg ReapStreamEndIngestSessionsParams) ([]string, error)
	ReconstructThumbnailAttemptObjectKeys(ctx context.Context, attemptID string) ([]ReconstructThumbnailAttemptObjectKeysRow, error)
	RecordArtifactEventFailure(ctx context.Context, arg RecordArtifactEventFailureParams) error
	RecordDVRCompletion(ctx context.Context, arg RecordDVRCompletionParams) error
	RecordDVRProgress(ctx context.Context, arg RecordDVRProgressParams) error
	RecordFreezePublicationLedger(ctx context.Context, arg RecordFreezePublicationLedgerParams) error
	RecordPublicationPair(ctx context.Context, arg RecordPublicationPairParams) error
	RefreshDVRArtifactNodeProgress(ctx context.Context, arg RefreshDVRArtifactNodeProgressParams) error
	RejectArtifactCreationCommand(ctx context.Context, arg RejectArtifactCreationCommandParams) (int64, error)
	ReleaseAdmissionEffectNotOwner(ctx context.Context, arg ReleaseAdmissionEffectNotOwnerParams) error
	ReleaseOfflineEffectNotOwner(ctx context.Context, arg ReleaseOfflineEffectNotOwnerParams) error
	RequeueStaleProcessingJobs(ctx context.Context, arg RequeueStaleProcessingJobsParams) (int64, error)
	ResetStaleFreezeAttempts(ctx context.Context, staleSeconds int64) ([]ResetStaleFreezeAttemptsRow, error)
	ResolveActiveDVRNodes(ctx context.Context, dollar_1 []string) ([]ResolveActiveDVRNodesRow, error)
	ResolveArtifactTenants(ctx context.Context, dollar_1 []string) ([]ResolveArtifactTenantsRow, error)
	ResolveClipInternalNameByRequestID(ctx context.Context, requestID sql.NullString) (string, error)
	ResolveDVRInternalNameByHash(ctx context.Context, artifactHash string) (string, error)
	ResolveThumbnailProcessingArtifact(ctx context.Context, artifactHash string) (ResolveThumbnailProcessingArtifactRow, error)
	ResolveThumbnailVODArtifact(ctx context.Context, internalName sql.NullString) (ResolveThumbnailVODArtifactRow, error)
	RetireIngestSession(ctx context.Context, arg RetireIngestSessionParams) (string, error)
	RetireIngestSessionByClaim(ctx context.Context, arg RetireIngestSessionByClaimParams) (RetireIngestSessionByClaimRow, error)
	RetireNeverProjectedIngestSession(ctx context.Context, arg RetireNeverProjectedIngestSessionParams) (string, error)
	RetryDVRChapterFinalize(ctx context.Context, arg RetryDVRChapterFinalizeParams) error
	RevertFailedFreezeDispatch(ctx context.Context, arg RevertFailedFreezeDispatchParams) (int64, error)
	RevertProcessingJobToQueued(ctx context.Context, jobID string) error
	RollingDVRProcessConfig(ctx context.Context, internalName sql.NullString) (sql.NullString, error)
	SetActiveObjectKeyBackfillCursor(ctx context.Context, lastHash string) error
	SetArtifactNodeLastEmittedVersion(ctx context.Context, arg SetArtifactNodeLastEmittedVersionParams) error
	SetArtifactSyncStatus(ctx context.Context, arg SetArtifactSyncStatusParams) error
	SetBillingAttributionCursor(ctx context.Context, arg SetBillingAttributionCursorParams) error
	SetDVRChapterPlaybackID(ctx context.Context, arg SetDVRChapterPlaybackIDParams) error
	SetFreezePublicationLedgerCursor(ctx context.Context, lastKey string) error
	SetLegacyActiveObjectKey(ctx context.Context, arg SetLegacyActiveObjectKeyParams) (int64, error)
	SettleAdmissionLegs(ctx context.Context, arg SettleAdmissionLegsParams) (int64, error)
	SettlePublishingThumbnailFailed(ctx context.Context, attemptID string) error
	SettleThumbnailRecoveryDone(ctx context.Context, arg SettleThumbnailRecoveryDoneParams) error
	SoftDeleteDVRChapterArtifacts(ctx context.Context, arg SoftDeleteDVRChapterArtifactsParams) ([]string, error)
	SoftDeleteDVRParent(ctx context.Context, arg SoftDeleteDVRParentParams) (int64, error)
	SoftDeleteVodArtifact(ctx context.Context, arg SoftDeleteVodArtifactParams) (int64, error)
	SumTenantActiveArtifactBytes(ctx context.Context, tenantID string) (int64, error)
	SupersedeOfflineEffect(ctx context.Context, arg SupersedeOfflineEffectParams) (int64, error)
	ThumbnailAttemptFailed(ctx context.Context, attemptID string) (bool, error)
	ThumbnailParentTombstoned(ctx context.Context, artifactHash string) (sql.NullBool, error)
	ThumbnailProjectionEligible(ctx context.Context, attemptID string) (bool, error)
	ThumbnailRecoveryBacklog(ctx context.Context, updatedAt time.Time) (int32, error)
	ThumbnailResourceProducedByNode(ctx context.Context, arg ThumbnailResourceProducedByNodeParams) (sql.NullBool, error)
	TouchDVRRecordingNode(ctx context.Context, arg TouchDVRRecordingNodeParams) error
	TouchStartedDVR(ctx context.Context, arg TouchStartedDVRParams) (int64, error)
	TryArtifactBillingAttributionLock(ctx context.Context) (bool, error)
	TryArtifactReconcilerLock(ctx context.Context) (bool, error)
	TryFreezePublicationLedgerLock(ctx context.Context) (bool, error)
	UnlockArtifactBillingAttribution(ctx context.Context) error
	UnlockArtifactReconciler(ctx context.Context) error
	UnlockDVRChapterMutation(ctx context.Context, hashtext string) error
	UnlockFreezePublicationLedger(ctx context.Context) error
	UnprojectedThumbnailEligible(ctx context.Context, attemptID string) (bool, error)
	UnprojectedThumbnailRecoveryBacklog(ctx context.Context, updatedAt time.Time) (int32, error)
	UpdateArtifactReportMetadata(ctx context.Context, arg UpdateArtifactReportMetadataParams) error
	UpdateChapterFinalizeProgress(ctx context.Context, arg UpdateChapterFinalizeProgressParams) (UpdateChapterFinalizeProgressRow, error)
	UpdateCompletedVODMetadata(ctx context.Context, arg UpdateCompletedVODMetadataParams) error
	UpdateProcessingJobCache(ctx context.Context, arg UpdateProcessingJobCacheParams) (int64, error)
	UpdateProcessingJobProgress(ctx context.Context, arg UpdateProcessingJobProgressParams) (UpdateProcessingJobProgressRow, error)
	UploadedArtifactFormat(ctx context.Context, artifactHash string) (string, error)
	UpsertCachedArtifactNode(ctx context.Context, arg UpsertCachedArtifactNodeParams) (sql.NullInt64, error)
	UpsertChapterVodMetadata(ctx context.Context, arg UpsertChapterVodMetadataParams) error
	UpsertDVRRecordingOrigin(ctx context.Context, arg UpsertDVRRecordingOriginParams) (bool, error)
	UpsertDiscoveredArtifactNode(ctx context.Context, arg UpsertDiscoveredArtifactNodeParams) error
	UpsertLostDVRSegment(ctx context.Context, arg UpsertLostDVRSegmentParams) error
	UpsertNodeComponents(ctx context.Context, arg UpsertNodeComponentsParams) error
	UpsertNodeLifecycles(ctx context.Context, arg UpsertNodeLifecyclesParams) error
	UpsertNodeMaintenance(ctx context.Context, arg UpsertNodeMaintenanceParams) error
	UpsertNodeOutputs(ctx context.Context, arg UpsertNodeOutputsParams) error
	UpsertNodeUpdateProgress(ctx context.Context, arg UpsertNodeUpdateProgressParams) error
	UpsertOpenDVRChapter(ctx context.Context, arg UpsertOpenDVRChapterParams) error
	UpsertOriginArtifactNode(ctx context.Context, arg UpsertOriginArtifactNodeParams) (bool, error)
	UpsertReportedArtifactNode(ctx context.Context, arg UpsertReportedArtifactNodeParams) (UpsertReportedArtifactNodeRow, error)
	UpsertSyncedVODObjectKey(ctx context.Context, arg UpsertSyncedVODObjectKeyParams) error
	VODNeedsDtshSync(ctx context.Context, artifactHash string) (bool, error)
	VerifyThumbnailObject(ctx context.Context, arg VerifyThumbnailObjectParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
