---
kafka_mm_artifact_url: ""
kafka_mm_artifact_checksum: ""
kafka_mm_version: ""

kafka_mm_user: kafka
kafka_mm_group: kafka
kafka_mm_install_dir: /opt/kafka
kafka_mm_state_dir: /var/lib/kafka-mirrormaker
kafka_mm_log_dir: /var/log/kafka-mirrormaker
kafka_mm_tarball_path: /tmp/kafka-mirrormaker.tar.gz

kafka_mm_heap_opts: "-Xmx1G -Xms1G"
kafka_mm_rest_port: 8083
kafka_mm_validate_rest: false
kafka_mm_task_count: 2
kafka_mm_local_cluster_alias: ""

kafka_mm_target: {}
kafka_mm_sources: []
