package commodore

import (
	"context"
	commodorepb "github.com/Livepeer-FrameWorks/monorepo/pkg/proto/commodore"
	commonpb "github.com/Livepeer-FrameWorks/monorepo/pkg/proto/common"
	foghorncontrolpb "github.com/Livepeer-FrameWorks/monorepo/pkg/proto/foghorn_control"
	sharedpb "github.com/Livepeer-FrameWorks/monorepo/pkg/proto/shared"
	x402pb "github.com/Livepeer-FrameWorks/monorepo/pkg/proto/x402"
)

// Interface is the full method surface of the concrete client, extracted so
// that api_gateway can inject fakes for resolver real-path tests. The concrete
// client satisfies it (asserted below).
type Interface interface {
	Close() error
	InvalidateTenantCacheKeys(tenantID string)
	ValidateStreamKey(ctx context.Context, streamKey string, clusterID ...string) (*commodorepb.ValidateStreamKeyResponse, error)
	ListManagedStreams(ctx context.Context, clusterID string) (*commodorepb.ListManagedStreamsResponse, error)
	RecordStreamActiveCluster(ctx context.Context, streamID, clusterID string) (*commodorepb.RecordStreamActiveClusterResponse, error)
	ClearStreamActiveCluster(ctx context.Context, streamID, expectedClusterID string) (*commodorepb.ClearStreamActiveClusterResponse, error)
	ResolveStreamContext(ctx context.Context, streamID, playbackID, internalName, clusterID string) (*commodorepb.ResolveStreamContextResponse, error)
	ResolvePlaybackID(ctx context.Context, playbackID string) (*commodorepb.ResolvePlaybackIDResponse, error)
	ResolveInternalName(ctx context.Context, internalName string) (*commodorepb.ResolveInternalNameResponse, error)
	ResolveArtifactPlaybackID(ctx context.Context, playbackID string) (*commodorepb.ResolveArtifactPlaybackIDResponse, error)
	ResolveArtifactInternalName(ctx context.Context, internalName string) (*commodorepb.ResolveArtifactInternalNameResponse, error)
	ResolvePullSourceByInternalName(ctx context.Context, internalName string) (*commodorepb.ResolvePullSourceByInternalNameResponse, error)
	ValidateAPIToken(ctx context.Context, token string) (*commodorepb.ValidateAPITokenResponse, error)
	MintMistAdminSession(ctx context.Context, req *commodorepb.MintMistAdminSessionRequest) (*commodorepb.MintMistAdminSessionResponse, error)
	ValidateMistAdminSession(ctx context.Context, req *commodorepb.ValidateMistAdminSessionRequest) (*commodorepb.ValidateMistAdminSessionResponse, error)
	StartDVR(ctx context.Context, req *sharedpb.StartDVRRequest) (*sharedpb.StartDVRResponse, error)
	RegisterClip(ctx context.Context, req *commodorepb.RegisterClipRequest) (*commodorepb.RegisterClipResponse, error)
	RegisterDVR(ctx context.Context, req *commodorepb.RegisterDVRRequest) (*commodorepb.RegisterDVRResponse, error)
	MarkArtifactThumbnailsReady(ctx context.Context, tenantID string, assetType commodorepb.ArtifactAssetType, assetKey, storageClusterID string) (*commodorepb.MarkArtifactThumbnailsReadyResponse, error)
	UpdateArtifactStorageCluster(ctx context.Context, tenantID string, assetType commodorepb.ArtifactAssetType, assetKey, storageClusterID string) (*commodorepb.UpdateArtifactStorageClusterResponse, error)
	UpdateArtifactSize(ctx context.Context, tenantID string, assetType commodorepb.ArtifactAssetType, assetKey string, sizeBytes int64) (*commodorepb.UpdateArtifactSizeResponse, error)
	UpdateDVRRetention(ctx context.Context, req *commodorepb.UpdateDVRRetentionRequest) (*commodorepb.UpdateDVRRetentionResponse, error)
	GetMediaRetentionPolicy(ctx context.Context, req *commodorepb.GetMediaRetentionPolicyRequest) (*commodorepb.GetMediaRetentionPolicyResponse, error)
	SetMediaRetentionPolicy(ctx context.Context, req *commodorepb.SetMediaRetentionPolicyRequest) (*commodorepb.SetMediaRetentionPolicyResponse, error)
	UpdateAssetRetention(ctx context.Context, req *commodorepb.UpdateAssetRetentionRequest) (*commodorepb.UpdateAssetRetentionResponse, error)
	ResetAssetRetention(ctx context.Context, req *commodorepb.ResetAssetRetentionRequest) (*commodorepb.UpdateAssetRetentionResponse, error)
	SetStreamRetentionOverrides(ctx context.Context, req *commodorepb.SetStreamRetentionOverridesRequest) (*commodorepb.SetStreamRetentionOverridesResponse, error)
	TestPlaybackAccess(ctx context.Context, req *foghorncontrolpb.TestPlaybackAccessRequest) (*foghorncontrolpb.TestPlaybackAccessResponse, error)
	RecordPullSourceEvent(ctx context.Context, req *commodorepb.RecordPullSourceEventRequest) error
	ListPullSourceEvents(ctx context.Context, req *commodorepb.ListPullSourceEventsRequest) (*commodorepb.ListPullSourceEventsResponse, error)
	ResolveClipHash(ctx context.Context, clipHash string) (*commodorepb.ResolveClipHashResponse, error)
	ResolveDVRHash(ctx context.Context, dvrHash string) (*commodorepb.ResolveDVRHashResponse, error)
	ResolveIdentifier(ctx context.Context, identifier string) (*commodorepb.ResolveIdentifierResponse, error)
	RegisterVod(ctx context.Context, tenantID, userID, filename string, title, description, contentType *string, sizeBytes *int64) (*commodorepb.RegisterVodResponse, error)
	ResolveVodHash(ctx context.Context, vodHash string) (*commodorepb.ResolveVodHashResponse, error)
	ResolveVodID(ctx context.Context, vodID string) (*commodorepb.ResolveVodIDResponse, error)
	MintChapterPlaybackID(ctx context.Context, chapterID, tenantID, artifactHash, userID, filename, originClusterID, storageClusterID, streamID string) (*commodorepb.MintChapterPlaybackIDResponse, error)
	GetTenantProcessesJSON(ctx context.Context, tenantID, streamType, clusterID string) (*commodorepb.GetTenantProcessesJSONResponse, error)
	GetTenantProcessesJSONForStream(ctx context.Context, tenantID, streamType, clusterID, streamID string) (*commodorepb.GetTenantProcessesJSONResponse, error)
	GetTenantProcessesJSONForLifecycle(ctx context.Context, tenantID, lifecycle, clusterID, streamID string) (*commodorepb.GetTenantProcessesJSONResponse, error)
	ResolveChapterPlaybackID(ctx context.Context, playbackID string) (*commodorepb.ResolveChapterPlaybackIDResponse, error)
	GetOrCreateWalletUser(ctx context.Context, chainType, walletAddress string) (*commodorepb.GetOrCreateWalletUserResponse, error)
	CreateStream(ctx context.Context, req *commodorepb.CreateStreamRequest) (*commodorepb.CreateStreamResponse, error)
	GetStream(ctx context.Context, streamID string) (*commodorepb.Stream, error)
	GetStreamsBatch(ctx context.Context, streamIDs []string) (*commodorepb.GetStreamsBatchResponse, error)
	ListStreams(ctx context.Context, pagination *commonpb.CursorPaginationRequest) (*commodorepb.ListStreamsResponse, error)
	UpdateStream(ctx context.Context, req *commodorepb.UpdateStreamRequest) (*commodorepb.Stream, error)
	DeleteStream(ctx context.Context, streamID string) (*commodorepb.DeleteStreamResponse, error)
	RefreshStreamKey(ctx context.Context, streamID string) (*commodorepb.RefreshStreamKeyResponse, error)
	CreateStreamKey(ctx context.Context, streamID, keyName string) (*commodorepb.StreamKeyResponse, error)
	ListStreamKeys(ctx context.Context, streamID string, pagination *commonpb.CursorPaginationRequest) (*commodorepb.ListStreamKeysResponse, error)
	DeactivateStreamKey(ctx context.Context, streamID, keyID string) error
	Login(ctx context.Context, req *commodorepb.LoginRequest) (*commodorepb.AuthResponse, error)
	Register(ctx context.Context, req *commodorepb.RegisterRequest) (*commodorepb.RegisterResponse, error)
	GetMe(ctx context.Context) (*commodorepb.User, error)
	Logout(ctx context.Context, token string) (*commodorepb.LogoutResponse, error)
	RefreshToken(ctx context.Context, refreshToken string) (*commodorepb.AuthResponse, error)
	VerifyEmail(ctx context.Context, token string) (*commodorepb.VerifyEmailResponse, error)
	ResendVerification(ctx context.Context, email, turnstileToken string) (*commodorepb.ResendVerificationResponse, error)
	ForgotPassword(ctx context.Context, email string) (*commodorepb.ForgotPasswordResponse, error)
	ResetPassword(ctx context.Context, token, password string) (*commodorepb.ResetPasswordResponse, error)
	UpdateMe(ctx context.Context, req *commodorepb.UpdateMeRequest) (*commodorepb.User, error)
	UpdateNewsletter(ctx context.Context, subscribed bool) (*commodorepb.UpdateNewsletterResponse, error)
	GetNewsletterStatus(ctx context.Context) (bool, error)
	WalletLogin(ctx context.Context, address, message, signature string, attribution *commonpb.SignupAttribution) (*commodorepb.AuthResponse, error)
	WalletLoginWithX402(ctx context.Context, payment *x402pb.X402PaymentPayload, clientIP, targetTenantID string, attribution *commonpb.SignupAttribution) (*commodorepb.WalletLoginWithX402Response, error)
	LinkWallet(ctx context.Context, address, message, signature string) (*commodorepb.WalletIdentity, error)
	UnlinkWallet(ctx context.Context, walletID string) (*commodorepb.UnlinkWalletResponse, error)
	ListWallets(ctx context.Context) (*commodorepb.ListWalletsResponse, error)
	LinkEmail(ctx context.Context, email, password string) (*commodorepb.LinkEmailResponse, error)
	CompleteAuthorization(ctx context.Context, req *commodorepb.CompleteAuthorizationRequest) (*commodorepb.CompleteAuthorizationResponse, error)
	ExchangeAuthorizationCode(ctx context.Context, req *commodorepb.ExchangeAuthorizationCodeRequest) (*commodorepb.AuthResponse, error)
	StartDeviceAuthorization(ctx context.Context, req *commodorepb.StartDeviceAuthorizationRequest) (*commodorepb.StartDeviceAuthorizationResponse, error)
	PollDeviceAuthorization(ctx context.Context, req *commodorepb.PollDeviceAuthorizationRequest) (*commodorepb.AuthResponse, error)
	LookupDeviceAuthorization(ctx context.Context, req *commodorepb.LookupDeviceAuthorizationRequest) (*commodorepb.LookupDeviceAuthorizationResponse, error)
	ApproveDeviceAuthorization(ctx context.Context, req *commodorepb.ApproveDeviceAuthorizationRequest) (*commodorepb.ApproveDeviceAuthorizationResponse, error)
	CreateAPIToken(ctx context.Context, req *commodorepb.CreateAPITokenRequest) (*commodorepb.CreateAPITokenResponse, error)
	ListAPITokens(ctx context.Context, pagination *commonpb.CursorPaginationRequest) (*commodorepb.ListAPITokensResponse, error)
	RevokeAPIToken(ctx context.Context, tokenID string) (*commodorepb.RevokeAPITokenResponse, error)
	CreateClip(ctx context.Context, req *sharedpb.CreateClipRequest) (*sharedpb.CreateClipResponse, error)
	GetClips(ctx context.Context, tenantID string, streamID *string, pagination *commonpb.CursorPaginationRequest, opts ...MediaListOptions) (*sharedpb.GetClipsResponse, error)
	GetClip(ctx context.Context, clipHash string) (*sharedpb.ClipInfo, error)
	DeleteClip(ctx context.Context, clipHash string) error
	StopDVR(ctx context.Context, dvrHash string) error
	DeleteDVR(ctx context.Context, dvrHash string) error
	RetrieveDVRChapter(ctx context.Context, req *foghorncontrolpb.RetrieveDVRChapterRequest) (*foghorncontrolpb.RetrieveDVRChapterResponse, error)
	ListDVRChapters(ctx context.Context, req *foghorncontrolpb.ListDVRChaptersRequest) (*foghorncontrolpb.ListDVRChaptersResponse, error)
	ListStorageArtifacts(ctx context.Context, req *commodorepb.ListStorageArtifactsRequest) (*commodorepb.ListStorageArtifactsResponse, error)
	ListDVRRequests(ctx context.Context, tenantID string, streamID *string, pagination *commonpb.CursorPaginationRequest, opts ...MediaListOptions) (*sharedpb.ListDVRRecordingsResponse, error)
	ResolveViewerEndpoint(ctx context.Context, contentID, viewerIP, viewerToken string) (*sharedpb.ViewerEndpointResponse, error)
	ResolveIngestEndpoint(ctx context.Context, streamKey, viewerIP string) (*sharedpb.IngestEndpointResponse, error)
	CreateVodUpload(ctx context.Context, req *sharedpb.CreateVodUploadRequest) (*sharedpb.CreateVodUploadResponse, error)
	CompleteVodUpload(ctx context.Context, req *sharedpb.CompleteVodUploadRequest) (*sharedpb.CompleteVodUploadResponse, error)
	AbortVodUpload(ctx context.Context, tenantID, uploadID string) (*sharedpb.AbortVodUploadResponse, error)
	GetVodUploadStatus(ctx context.Context, tenantID, uploadID string) (*sharedpb.GetVodUploadStatusResponse, error)
	GetVodAsset(ctx context.Context, tenantID, artifactHash string) (*sharedpb.VodAssetInfo, error)
	ListVodAssets(ctx context.Context, tenantID string, pagination *commonpb.CursorPaginationRequest, streamID *string, opts ...MediaListOptions) (*sharedpb.ListVodAssetsResponse, error)
	DeleteVodAsset(ctx context.Context, tenantID, artifactHash string) (*sharedpb.DeleteVodAssetResponse, error)
	TerminateTenantStreams(ctx context.Context, tenantID, reason string) (*foghorncontrolpb.TerminateTenantStreamsResponse, error)
	InvalidateTenantCache(ctx context.Context, tenantID, reason string) (*foghorncontrolpb.InvalidateTenantCacheResponse, error)
	GetTenantUserCount(ctx context.Context, tenantID string) (*commodorepb.GetTenantUserCountResponse, error)
	GetTenantPrimaryUser(ctx context.Context, tenantID string) (*commodorepb.GetTenantPrimaryUserResponse, error)
	CreateUserInTenant(ctx context.Context, req *commodorepb.CreateUserInTenantRequest) (*commodorepb.CreateUserInTenantResponse, error)
	SetNodeMode(ctx context.Context, req *foghorncontrolpb.SetNodeModeRequest) (*foghorncontrolpb.SetNodeModeResponse, error)
	GetNodeHealth(ctx context.Context, req *foghorncontrolpb.GetNodeHealthRequest) (*foghorncontrolpb.GetNodeHealthResponse, error)
	GetStreamPushTargets(ctx context.Context, streamID, tenantID string) ([]*commodorepb.PushTargetInternal, error)
	UpdatePushTargetStatus(ctx context.Context, id, tenantID, status string, lastError *string) error
	CreatePushTarget(ctx context.Context, req *commodorepb.CreatePushTargetRequest) (*commodorepb.PushTarget, error)
	ListPushTargets(ctx context.Context, streamID string) (*commodorepb.ListPushTargetsResponse, error)
	UpdatePushTarget(ctx context.Context, req *commodorepb.UpdatePushTargetRequest) (*commodorepb.PushTarget, error)
	DeletePushTarget(ctx context.Context, id string) (*commodorepb.DeletePushTargetResponse, error)
	CreateSigningKey(ctx context.Context, name string) (*commodorepb.CreateSigningKeyResponse, error)
	GetSigningKey(ctx context.Context, id string) (*commodorepb.SigningKey, error)
	ListSigningKeys(ctx context.Context, statusFilter string, limit int32, afterID string) (*commodorepb.ListSigningKeysResponse, error)
	RevokeSigningKey(ctx context.Context, id string) (*commodorepb.SigningKey, error)
	SetPlaybackPolicy(ctx context.Context, req *commodorepb.SetPlaybackPolicyRequest) (*commodorepb.SetPlaybackPolicyResponse, error)
	ResolvePlaybackPolicy(ctx context.Context, playbackID string) (*commodorepb.ResolvePlaybackPolicyResponse, error)
	ResolvePlaybackPolicyForEnforcement(ctx context.Context, playbackID string) (*commodorepb.ResolvePlaybackPolicyResponse, error)
	ResolvePlaybackPolicyByInternalName(ctx context.Context, internalName string) (*commodorepb.ResolvePlaybackPolicyResponse, error)
	GetSignedPolicyBundle(ctx context.Context, tenantID, streamID string) (*commodorepb.GetSignedPolicyBundleResponse, error)
	RecordSigningKeyUse(ctx context.Context, tenantID, kid string) error
}

var _ Interface = (*GRPCClient)(nil)
