---
- name: Restart Kafka MirrorMaker
  ansible.builtin.systemd:
    name: frameworks-kafka-mirrormaker
    state: restarted
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode
  listen: kafka_mirrormaker restart
