// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type CursorPaginationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Forward pagination (most common - newest first)
	First int32   `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`      // Number of items to fetch forward
	After *string `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"` // Opaque cursor - fetch items after this position
	// Backward pagination (for "previous page" navigation)
	Last          int32   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`          // Number of items to fetch backward
	Before        *string `protobuf:"bytes,4,opt,name=before,proto3,oneof" json:"before,omitempty"` // Opaque cursor - fetch items before this position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationRequest) Reset() {
	*x = CursorPaginationRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationRequest) ProtoMessage() {}

func (x *CursorPaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationRequest.ProtoReflect.Descriptor instead.
func (*CursorPaginationRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *CursorPaginationRequest) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *CursorPaginationRequest) GetAfter() string {
	if x != nil && x.After != nil {
		return *x.After
	}
	return ""
}

func (x *CursorPaginationRequest) GetLast() int32 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *CursorPaginationRequest) GetBefore() string {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return ""
}

type CursorPaginationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalCount      int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,3,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	StartCursor     *string                `protobuf:"bytes,4,opt,name=start_cursor,json=startCursor,proto3,oneof" json:"start_cursor,omitempty"` // Cursor of first item in result
	EndCursor       *string                `protobuf:"bytes,5,opt,name=end_cursor,json=endCursor,proto3,oneof" json:"end_cursor,omitempty"`       // Cursor of last item in result
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CursorPaginationResponse) Reset() {
	*x = CursorPaginationResponse{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationResponse) ProtoMessage() {}

func (x *CursorPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationResponse.ProtoReflect.Descriptor instead.
func (*CursorPaginationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *CursorPaginationResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CursorPaginationResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *CursorPaginationResponse) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *CursorPaginationResponse) GetStartCursor() string {
	if x != nil && x.StartCursor != nil {
		return *x.StartCursor
	}
	return ""
}

func (x *CursorPaginationResponse) GetEndCursor() string {
	if x != nil && x.EndCursor != nil {
		return *x.EndCursor
	}
	return ""
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type SignupAttribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignupChannel string                 `protobuf:"bytes,1,opt,name=signup_channel,json=signupChannel,proto3" json:"signup_channel,omitempty"`
	SignupMethod  string                 `protobuf:"bytes,2,opt,name=signup_method,json=signupMethod,proto3" json:"signup_method,omitempty"`
	UtmSource     string                 `protobuf:"bytes,3,opt,name=utm_source,json=utmSource,proto3" json:"utm_source,omitempty"`
	UtmMedium     string                 `protobuf:"bytes,4,opt,name=utm_medium,json=utmMedium,proto3" json:"utm_medium,omitempty"`
	UtmCampaign   string                 `protobuf:"bytes,5,opt,name=utm_campaign,json=utmCampaign,proto3" json:"utm_campaign,omitempty"`
	UtmContent    string                 `protobuf:"bytes,6,opt,name=utm_content,json=utmContent,proto3" json:"utm_content,omitempty"`
	UtmTerm       string                 `protobuf:"bytes,7,opt,name=utm_term,json=utmTerm,proto3" json:"utm_term,omitempty"`
	HttpReferer   string                 `protobuf:"bytes,8,opt,name=http_referer,json=httpReferer,proto3" json:"http_referer,omitempty"`
	LandingPage   string                 `protobuf:"bytes,9,opt,name=landing_page,json=landingPage,proto3" json:"landing_page,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,10,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	IsAgent       bool                   `protobuf:"varint,11,opt,name=is_agent,json=isAgent,proto3" json:"is_agent,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,12,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupAttribution) Reset() {
	*x = SignupAttribution{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupAttribution) ProtoMessage() {}

func (x *SignupAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupAttribution.ProtoReflect.Descriptor instead.
func (*SignupAttribution) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *SignupAttribution) GetSignupChannel() string {
	if x != nil {
		return x.SignupChannel
	}
	return ""
}

func (x *SignupAttribution) GetSignupMethod() string {
	if x != nil {
		return x.SignupMethod
	}
	return ""
}

func (x *SignupAttribution) GetUtmSource() string {
	if x != nil {
		return x.UtmSource
	}
	return ""
}

func (x *SignupAttribution) GetUtmMedium() string {
	if x != nil {
		return x.UtmMedium
	}
	return ""
}

func (x *SignupAttribution) GetUtmCampaign() string {
	if x != nil {
		return x.UtmCampaign
	}
	return ""
}

func (x *SignupAttribution) GetUtmContent() string {
	if x != nil {
		return x.UtmContent
	}
	return ""
}

func (x *SignupAttribution) GetUtmTerm() string {
	if x != nil {
		return x.UtmTerm
	}
	return ""
}

func (x *SignupAttribution) GetHttpReferer() string {
	if x != nil {
		return x.HttpReferer
	}
	return ""
}

func (x *SignupAttribution) GetLandingPage() string {
	if x != nil {
		return x.LandingPage
	}
	return ""
}

func (x *SignupAttribution) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *SignupAttribution) GetIsAgent() bool {
	if x != nil {
		return x.IsAgent
	}
	return false
}

func (x *SignupAttribution) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x17CursorPaginationRequest\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x05R\x05first\x12\x19\n" +
	"\x05after\x18\x02 \x01(\tH\x00R\x05after\x88\x01\x01\x12\x12\n" +
	"\x04last\x18\x03 \x01(\x05R\x04last\x12\x1b\n" +
	"\x06before\x18\x04 \x01(\tH\x01R\x06before\x88\x01\x01B\b\n" +
	"\x06_afterB\t\n" +
	"\a_before\"\xf7\x01\n" +
	"\x18CursorPaginationResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\"\n" +
	"\rhas_next_page\x18\x02 \x01(\bR\vhasNextPage\x12*\n" +
	"\x11has_previous_page\x18\x03 \x01(\bR\x0fhasPreviousPage\x12&\n" +
	"\fstart_cursor\x18\x04 \x01(\tH\x00R\vstartCursor\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_cursor\x18\x05 \x01(\tH\x01R\tendCursor\x88\x01\x01B\x0f\n" +
	"\r_start_cursorB\r\n" +
	"\v_end_cursor\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xa7\x03\n" +
	"\x11SignupAttribution\x12%\n" +
	"\x0esignup_channel\x18\x01 \x01(\tR\rsignupChannel\x12#\n" +
	"\rsignup_method\x18\x02 \x01(\tR\fsignupMethod\x12\x1d\n" +
	"\n" +
	"utm_source\x18\x03 \x01(\tR\tutmSource\x12\x1d\n" +
	"\n" +
	"utm_medium\x18\x04 \x01(\tR\tutmMedium\x12!\n" +
	"\futm_campaign\x18\x05 \x01(\tR\vutmCampaign\x12\x1f\n" +
	"\vutm_content\x18\x06 \x01(\tR\n" +
	"utmContent\x12\x19\n" +
	"\butm_term\x18\a \x01(\tR\autmTerm\x12!\n" +
	"\fhttp_referer\x18\b \x01(\tR\vhttpReferer\x12!\n" +
	"\flanding_page\x18\t \x01(\tR\vlandingPage\x12#\n" +
	"\rreferral_code\x18\n" +
	" \x01(\tR\freferralCode\x12\x19\n" +
	"\bis_agent\x18\v \x01(\bR\aisAgent\x12#\n" +
	"\rmetadata_json\x18\f \x01(\tR\fmetadataJson*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02B\x16Z\x14frameworks/pkg/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(SortOrder)(0),                   // 0: common.SortOrder
	(*CursorPaginationRequest)(nil),  // 1: common.CursorPaginationRequest
	(*CursorPaginationResponse)(nil), // 2: common.CursorPaginationResponse
	(*TimeRange)(nil),                // 3: common.TimeRange
	(*SignupAttribution)(nil),        // 4: common.SignupAttribution
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	5, // 0: common.TimeRange.start:type_name -> google.protobuf.Timestamp
	5, // 1: common.TimeRange.end:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
