// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: foghorn.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetNodeModeStatus int32

const (
	SetNodeModeStatus_SET_NODE_MODE_STATUS_UNSPECIFIED     SetNodeModeStatus = 0
	SetNodeModeStatus_SET_NODE_MODE_STATUS_SUCCESS         SetNodeModeStatus = 1
	SetNodeModeStatus_SET_NODE_MODE_STATUS_INVALID_MODE    SetNodeModeStatus = 2
	SetNodeModeStatus_SET_NODE_MODE_STATUS_NOT_FOUND       SetNodeModeStatus = 3
	SetNodeModeStatus_SET_NODE_MODE_STATUS_ALREADY_IN_MODE SetNodeModeStatus = 4
)

// Enum value maps for SetNodeModeStatus.
var (
	SetNodeModeStatus_name = map[int32]string{
		0: "SET_NODE_MODE_STATUS_UNSPECIFIED",
		1: "SET_NODE_MODE_STATUS_SUCCESS",
		2: "SET_NODE_MODE_STATUS_INVALID_MODE",
		3: "SET_NODE_MODE_STATUS_NOT_FOUND",
		4: "SET_NODE_MODE_STATUS_ALREADY_IN_MODE",
	}
	SetNodeModeStatus_value = map[string]int32{
		"SET_NODE_MODE_STATUS_UNSPECIFIED":     0,
		"SET_NODE_MODE_STATUS_SUCCESS":         1,
		"SET_NODE_MODE_STATUS_INVALID_MODE":    2,
		"SET_NODE_MODE_STATUS_NOT_FOUND":       3,
		"SET_NODE_MODE_STATUS_ALREADY_IN_MODE": 4,
	}
)

func (x SetNodeModeStatus) Enum() *SetNodeModeStatus {
	p := new(SetNodeModeStatus)
	*p = x
	return p
}

func (x SetNodeModeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetNodeModeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_foghorn_proto_enumTypes[0].Descriptor()
}

func (SetNodeModeStatus) Type() protoreflect.EnumType {
	return &file_foghorn_proto_enumTypes[0]
}

func (x SetNodeModeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetNodeModeStatus.Descriptor instead.
func (SetNodeModeStatus) EnumDescriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{0}
}

type RetrieveDVRChapterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DvrArtifactId   string                 `protobuf:"bytes,1,opt,name=dvr_artifact_id,json=dvrArtifactId,proto3" json:"dvr_artifact_id,omitempty"`
	Mode            string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                                               // 'window_sized_chapters' | 'fixed_interval' | 'explicit_range'
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // required for fixed_interval
	StartMs         int64                  `protobuf:"varint,4,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`                         // UTC epoch ms
	EndMs           int64                  `protobuf:"varint,5,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`                               // UTC epoch ms
	TenantId        string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                       // for tenant-isolation enforcement
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveDVRChapterRequest) Reset() {
	*x = RetrieveDVRChapterRequest{}
	mi := &file_foghorn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDVRChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDVRChapterRequest) ProtoMessage() {}

func (x *RetrieveDVRChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDVRChapterRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDVRChapterRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveDVRChapterRequest) GetDvrArtifactId() string {
	if x != nil {
		return x.DvrArtifactId
	}
	return ""
}

func (x *RetrieveDVRChapterRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RetrieveDVRChapterRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *RetrieveDVRChapterRequest) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *RetrieveDVRChapterRequest) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *RetrieveDVRChapterRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RetrieveDVRChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     string                 `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	ManifestS3Key string                 `protobuf:"bytes,2,opt,name=manifest_s3_key,json=manifestS3Key,proto3" json:"manifest_s3_key,omitempty"` // e.g. dvr/{tenant}/{stream}/{artifact}/chapters/{chapter_id}.m3u8
	ManifestUrl   string                 `protobuf:"bytes,3,opt,name=manifest_url,json=manifestUrl,proto3" json:"manifest_url,omitempty"`         // Mist playback ID (dvr+{chapter_id}); field name retained for API stability
	IsCurrent     bool                   `protobuf:"varint,4,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`              // EVENT-shaped (no ENDLIST) vs VOD-shaped
	HasGaps       bool                   `protobuf:"varint,5,opt,name=has_gaps,json=hasGaps,proto3" json:"has_gaps,omitempty"`
	SegmentCount  int32                  `protobuf:"varint,6,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveDVRChapterResponse) Reset() {
	*x = RetrieveDVRChapterResponse{}
	mi := &file_foghorn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDVRChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDVRChapterResponse) ProtoMessage() {}

func (x *RetrieveDVRChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDVRChapterResponse.ProtoReflect.Descriptor instead.
func (*RetrieveDVRChapterResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveDVRChapterResponse) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *RetrieveDVRChapterResponse) GetManifestS3Key() string {
	if x != nil {
		return x.ManifestS3Key
	}
	return ""
}

func (x *RetrieveDVRChapterResponse) GetManifestUrl() string {
	if x != nil {
		return x.ManifestUrl
	}
	return ""
}

func (x *RetrieveDVRChapterResponse) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *RetrieveDVRChapterResponse) GetHasGaps() bool {
	if x != nil {
		return x.HasGaps
	}
	return false
}

func (x *RetrieveDVRChapterResponse) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

type ListDVRChaptersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DvrArtifactId   string                 `protobuf:"bytes,1,opt,name=dvr_artifact_id,json=dvrArtifactId,proto3" json:"dvr_artifact_id,omitempty"`
	Mode            string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // restrict to chapters of this mode; empty = all
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	RangeStartMs    int64                  `protobuf:"varint,4,opt,name=range_start_ms,json=rangeStartMs,proto3" json:"range_start_ms,omitempty"` // 0 = no lower bound
	RangeEndMs      int64                  `protobuf:"varint,5,opt,name=range_end_ms,json=rangeEndMs,proto3" json:"range_end_ms,omitempty"`       // 0 = no upper bound
	PageSize        int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`               // default 200, max 1000
	PageToken       string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`             // keyset cursor (start_ms as decimal text)
	TenantId        string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListDVRChaptersRequest) Reset() {
	*x = ListDVRChaptersRequest{}
	mi := &file_foghorn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDVRChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDVRChaptersRequest) ProtoMessage() {}

func (x *ListDVRChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDVRChaptersRequest.ProtoReflect.Descriptor instead.
func (*ListDVRChaptersRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{2}
}

func (x *ListDVRChaptersRequest) GetDvrArtifactId() string {
	if x != nil {
		return x.DvrArtifactId
	}
	return ""
}

func (x *ListDVRChaptersRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ListDVRChaptersRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ListDVRChaptersRequest) GetRangeStartMs() int64 {
	if x != nil {
		return x.RangeStartMs
	}
	return 0
}

func (x *ListDVRChaptersRequest) GetRangeEndMs() int64 {
	if x != nil {
		return x.RangeEndMs
	}
	return 0
}

func (x *ListDVRChaptersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDVRChaptersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListDVRChaptersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ChapterRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChapterId       string                 `protobuf:"bytes,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Mode            string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	StartMs         int64                  `protobuf:"varint,4,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs           int64                  `protobuf:"varint,5,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	IsCurrent       bool                   `protobuf:"varint,6,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	ManifestS3Key   string                 `protobuf:"bytes,7,opt,name=manifest_s3_key,json=manifestS3Key,proto3" json:"manifest_s3_key,omitempty"`
	HasGaps         bool                   `protobuf:"varint,8,opt,name=has_gaps,json=hasGaps,proto3" json:"has_gaps,omitempty"`
	SegmentCount    int32                  `protobuf:"varint,9,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChapterRef) Reset() {
	*x = ChapterRef{}
	mi := &file_foghorn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterRef) ProtoMessage() {}

func (x *ChapterRef) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterRef.ProtoReflect.Descriptor instead.
func (*ChapterRef) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{3}
}

func (x *ChapterRef) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *ChapterRef) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ChapterRef) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ChapterRef) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *ChapterRef) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *ChapterRef) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *ChapterRef) GetManifestS3Key() string {
	if x != nil {
		return x.ManifestS3Key
	}
	return ""
}

func (x *ChapterRef) GetHasGaps() bool {
	if x != nil {
		return x.HasGaps
	}
	return false
}

func (x *ChapterRef) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

type ListDVRChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*ChapterRef          `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty when no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDVRChaptersResponse) Reset() {
	*x = ListDVRChaptersResponse{}
	mi := &file_foghorn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDVRChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDVRChaptersResponse) ProtoMessage() {}

func (x *ListDVRChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDVRChaptersResponse.ProtoReflect.Descriptor instead.
func (*ListDVRChaptersResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{4}
}

func (x *ListDVRChaptersResponse) GetChapters() []*ChapterRef {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *ListDVRChaptersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SetDVRChapterPolicyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DvrArtifactId   string                 `protobuf:"bytes,1,opt,name=dvr_artifact_id,json=dvrArtifactId,proto3" json:"dvr_artifact_id,omitempty"`
	Mode            string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                                               // 'window_sized_chapters' | 'fixed_interval' | '' (clear)
	IntervalSeconds int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // required for fixed_interval
	TenantId        string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDVRChapterPolicyRequest) Reset() {
	*x = SetDVRChapterPolicyRequest{}
	mi := &file_foghorn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDVRChapterPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDVRChapterPolicyRequest) ProtoMessage() {}

func (x *SetDVRChapterPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDVRChapterPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetDVRChapterPolicyRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{5}
}

func (x *SetDVRChapterPolicyRequest) GetDvrArtifactId() string {
	if x != nil {
		return x.DvrArtifactId
	}
	return ""
}

func (x *SetDVRChapterPolicyRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SetDVRChapterPolicyRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *SetDVRChapterPolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SetDVRChapterPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDVRChapterPolicyResponse) Reset() {
	*x = SetDVRChapterPolicyResponse{}
	mi := &file_foghorn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDVRChapterPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDVRChapterPolicyResponse) ProtoMessage() {}

func (x *SetDVRChapterPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDVRChapterPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetDVRChapterPolicyResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{6}
}

func (x *SetDVRChapterPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetDVRChapterPolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PreRegisterEdgeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`   // Bootstrap token for edge enrollment
	ExternalIp      string                 `protobuf:"bytes,2,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`                  // Edge's public IP (detected by CLI)
	PreferredNodeId string                 `protobuf:"bytes,3,opt,name=preferred_node_id,json=preferredNodeId,proto3" json:"preferred_node_id,omitempty"` // Optional human-friendly node ID/hostname hint
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreRegisterEdgeRequest) Reset() {
	*x = PreRegisterEdgeRequest{}
	mi := &file_foghorn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreRegisterEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRegisterEdgeRequest) ProtoMessage() {}

func (x *PreRegisterEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRegisterEdgeRequest.ProtoReflect.Descriptor instead.
func (*PreRegisterEdgeRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{7}
}

func (x *PreRegisterEdgeRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *PreRegisterEdgeRequest) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *PreRegisterEdgeRequest) GetPreferredNodeId() string {
	if x != nil {
		return x.PreferredNodeId
	}
	return ""
}

type PreRegisterEdgeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`             // Assigned node ID
	EdgeDomain      string                 `protobuf:"bytes,2,opt,name=edge_domain,json=edgeDomain,proto3" json:"edge_domain,omitempty"` // e.g., {node_label}.{cluster_slug}.{root_domain}; node_label is node_id with a single edge- prefix
	PoolDomain      string                 `protobuf:"bytes,3,opt,name=pool_domain,json=poolDomain,proto3" json:"pool_domain,omitempty"` // e.g., edge.{cluster_slug}.{root_domain}
	ClusterSlug     string                 `protobuf:"bytes,4,opt,name=cluster_slug,json=clusterSlug,proto3" json:"cluster_slug,omitempty"`
	FoghornGrpcAddr string                 `protobuf:"bytes,5,opt,name=foghorn_grpc_addr,json=foghornGrpcAddr,proto3" json:"foghorn_grpc_addr,omitempty"` // Address for Helmsman's FOGHORN_CONTROL_ADDR
	// Deprecated: Marked as deprecated in foghorn.proto.
	CertPem string `protobuf:"bytes,6,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"` // Deprecated: certs now delivered via ConfigSeed only
	// Deprecated: Marked as deprecated in foghorn.proto.
	KeyPem           string               `protobuf:"bytes,7,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`                                 // Deprecated: certs now delivered via ConfigSeed only
	ClusterId        string               `protobuf:"bytes,8,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`                        // Raw cluster ID (may differ from DNS-safe cluster_slug)
	InternalCaBundle []byte               `protobuf:"bytes,9,opt,name=internal_ca_bundle,json=internalCaBundle,proto3" json:"internal_ca_bundle,omitempty"` // Optional internal CA bundle for pre-Connect trust bootstrap
	Telemetry        *EdgeTelemetryConfig `protobuf:"bytes,10,opt,name=telemetry,proto3" json:"telemetry,omitempty"`                                        // Optional per-edge telemetry remote_write config
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreRegisterEdgeResponse) Reset() {
	*x = PreRegisterEdgeResponse{}
	mi := &file_foghorn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreRegisterEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRegisterEdgeResponse) ProtoMessage() {}

func (x *PreRegisterEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRegisterEdgeResponse.ProtoReflect.Descriptor instead.
func (*PreRegisterEdgeResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{8}
}

func (x *PreRegisterEdgeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PreRegisterEdgeResponse) GetEdgeDomain() string {
	if x != nil {
		return x.EdgeDomain
	}
	return ""
}

func (x *PreRegisterEdgeResponse) GetPoolDomain() string {
	if x != nil {
		return x.PoolDomain
	}
	return ""
}

func (x *PreRegisterEdgeResponse) GetClusterSlug() string {
	if x != nil {
		return x.ClusterSlug
	}
	return ""
}

func (x *PreRegisterEdgeResponse) GetFoghornGrpcAddr() string {
	if x != nil {
		return x.FoghornGrpcAddr
	}
	return ""
}

// Deprecated: Marked as deprecated in foghorn.proto.
func (x *PreRegisterEdgeResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

// Deprecated: Marked as deprecated in foghorn.proto.
func (x *PreRegisterEdgeResponse) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *PreRegisterEdgeResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *PreRegisterEdgeResponse) GetInternalCaBundle() []byte {
	if x != nil {
		return x.InternalCaBundle
	}
	return nil
}

func (x *PreRegisterEdgeResponse) GetTelemetry() *EdgeTelemetryConfig {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type SetNodeModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                // "normal", "draining", "maintenance"
	SetBy         string                 `protobuf:"bytes,3,opt,name=set_by,json=setBy,proto3" json:"set_by,omitempty"` // caller identity for audit trail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeModeRequest) Reset() {
	*x = SetNodeModeRequest{}
	mi := &file_foghorn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeModeRequest) ProtoMessage() {}

func (x *SetNodeModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeModeRequest.ProtoReflect.Descriptor instead.
func (*SetNodeModeRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{9}
}

func (x *SetNodeModeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetNodeModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SetNodeModeRequest) GetSetBy() string {
	if x != nil {
		return x.SetBy
	}
	return ""
}

type SetNodeModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status        SetNodeModeStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=foghorn.SetNodeModeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNodeModeResponse) Reset() {
	*x = SetNodeModeResponse{}
	mi := &file_foghorn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNodeModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNodeModeResponse) ProtoMessage() {}

func (x *SetNodeModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNodeModeResponse.ProtoReflect.Descriptor instead.
func (*SetNodeModeResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{10}
}

func (x *SetNodeModeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SetNodeModeResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SetNodeModeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetNodeModeResponse) GetStatus() SetNodeModeStatus {
	if x != nil {
		return x.Status
	}
	return SetNodeModeStatus_SET_NODE_MODE_STATUS_UNSPECIFIED
}

type GetNodeHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHealthRequest) Reset() {
	*x = GetNodeHealthRequest{}
	mi := &file_foghorn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHealthRequest) ProtoMessage() {}

func (x *GetNodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHealthRequest.ProtoReflect.Descriptor instead.
func (*GetNodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeHealthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeHealthResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	NodeId            string                  `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OperationalMode   string                  `protobuf:"bytes,2,opt,name=operational_mode,json=operationalMode,proto3" json:"operational_mode,omitempty"`
	IsHealthy         bool                    `protobuf:"varint,3,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	ActiveViewers     int32                   `protobuf:"varint,4,opt,name=active_viewers,json=activeViewers,proto3" json:"active_viewers,omitempty"`
	ActiveStreams     int32                   `protobuf:"varint,5,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	LastHeartbeat     string                  `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // ISO8601
	ClusterId         string                  `protobuf:"bytes,7,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TenantId          string                  `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // owning tenant (empty for operator nodes)
	CpuPercent        float64                 `protobuf:"fixed64,9,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamUsedMb         float64                 `protobuf:"fixed64,10,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`
	RamMaxMb          float64                 `protobuf:"fixed64,11,opt,name=ram_max_mb,json=ramMaxMb,proto3" json:"ram_max_mb,omitempty"`
	BandwidthUpMbps   float64                 `protobuf:"fixed64,12,opt,name=bandwidth_up_mbps,json=bandwidthUpMbps,proto3" json:"bandwidth_up_mbps,omitempty"`
	BandwidthDownMbps float64                 `protobuf:"fixed64,13,opt,name=bandwidth_down_mbps,json=bandwidthDownMbps,proto3" json:"bandwidth_down_mbps,omitempty"`
	BwLimitMbps       float64                 `protobuf:"fixed64,14,opt,name=bw_limit_mbps,json=bwLimitMbps,proto3" json:"bw_limit_mbps,omitempty"`
	DiskTotalBytes    uint64                  `protobuf:"varint,15,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes     uint64                  `protobuf:"varint,16,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	Location          string                  `protobuf:"bytes,17,opt,name=location,proto3" json:"location,omitempty"`
	Latitude          *float64                `protobuf:"fixed64,18,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude         *float64                `protobuf:"fixed64,19,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	ComponentVersions []*NodeComponentVersion `protobuf:"bytes,20,rep,name=component_versions,json=componentVersions,proto3" json:"component_versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetNodeHealthResponse) Reset() {
	*x = GetNodeHealthResponse{}
	mi := &file_foghorn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHealthResponse) ProtoMessage() {}

func (x *GetNodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHealthResponse.ProtoReflect.Descriptor instead.
func (*GetNodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{12}
}

func (x *GetNodeHealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeHealthResponse) GetOperationalMode() string {
	if x != nil {
		return x.OperationalMode
	}
	return ""
}

func (x *GetNodeHealthResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *GetNodeHealthResponse) GetActiveViewers() int32 {
	if x != nil {
		return x.ActiveViewers
	}
	return 0
}

func (x *GetNodeHealthResponse) GetActiveStreams() int32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *GetNodeHealthResponse) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *GetNodeHealthResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetNodeHealthResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetNodeHealthResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *GetNodeHealthResponse) GetRamUsedMb() float64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *GetNodeHealthResponse) GetRamMaxMb() float64 {
	if x != nil {
		return x.RamMaxMb
	}
	return 0
}

func (x *GetNodeHealthResponse) GetBandwidthUpMbps() float64 {
	if x != nil {
		return x.BandwidthUpMbps
	}
	return 0
}

func (x *GetNodeHealthResponse) GetBandwidthDownMbps() float64 {
	if x != nil {
		return x.BandwidthDownMbps
	}
	return 0
}

func (x *GetNodeHealthResponse) GetBwLimitMbps() float64 {
	if x != nil {
		return x.BwLimitMbps
	}
	return 0
}

func (x *GetNodeHealthResponse) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *GetNodeHealthResponse) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *GetNodeHealthResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetNodeHealthResponse) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GetNodeHealthResponse) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *GetNodeHealthResponse) GetComponentVersions() []*NodeComponentVersion {
	if x != nil {
		return x.ComponentVersions
	}
	return nil
}

type NodeComponentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeComponentVersion) Reset() {
	*x = NodeComponentVersion{}
	mi := &file_foghorn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeComponentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeComponentVersion) ProtoMessage() {}

func (x *NodeComponentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeComponentVersion.ProtoReflect.Descriptor instead.
func (*NodeComponentVersion) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{13}
}

func (x *NodeComponentVersion) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *NodeComponentVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InvalidatePlaybackAuthRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// internal_names is the list of MistServer internal stream names whose
	// active sessions need re-evaluating. Empty means "every protected
	// stream/artifact for the tenant" (used on signing-key revoke when the
	// policy may reference the revoked kid on any object).
	InternalNames []string `protobuf:"bytes,2,rep,name=internal_names,json=internalNames,proto3" json:"internal_names,omitempty"`
	Reason        string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // e.g., "policy_change", "key_revoked", "webhook_rotated", "bundle_revoke"
	// Signed-policy-bundle revocation fields. When reason == "bundle_revoke",
	// Foghorn calls policybundle.Cache.BumpWatermark(tenant_id, stream_id,
	// bundle_min_version) on receipt, invalidating cached bundles below the
	// watermark. stream_id empty means "all streams for this tenant" (used on
	// tenant-wide plan downgrades; Foghorn loops over its cache).
	StreamId         string `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	BundleMinVersion int64  `protobuf:"varint,5,opt,name=bundle_min_version,json=bundleMinVersion,proto3" json:"bundle_min_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvalidatePlaybackAuthRequest) Reset() {
	*x = InvalidatePlaybackAuthRequest{}
	mi := &file_foghorn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidatePlaybackAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidatePlaybackAuthRequest) ProtoMessage() {}

func (x *InvalidatePlaybackAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidatePlaybackAuthRequest.ProtoReflect.Descriptor instead.
func (*InvalidatePlaybackAuthRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{14}
}

func (x *InvalidatePlaybackAuthRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InvalidatePlaybackAuthRequest) GetInternalNames() []string {
	if x != nil {
		return x.InternalNames
	}
	return nil
}

func (x *InvalidatePlaybackAuthRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InvalidatePlaybackAuthRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *InvalidatePlaybackAuthRequest) GetBundleMinVersion() int64 {
	if x != nil {
		return x.BundleMinVersion
	}
	return 0
}

type InvalidatePlaybackAuthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StreamsInvalidated int32                  `protobuf:"varint,1,opt,name=streams_invalidated,json=streamsInvalidated,proto3" json:"streams_invalidated,omitempty"` // Number of internal_names dispatched
	NodesDispatched    int32                  `protobuf:"varint,2,opt,name=nodes_dispatched,json=nodesDispatched,proto3" json:"nodes_dispatched,omitempty"`          // Number of Helmsmen successfully contacted
	NodesAttempted     int32                  `protobuf:"varint,3,opt,name=nodes_attempted,json=nodesAttempted,proto3" json:"nodes_attempted,omitempty"`             // Total Helmsmen targeted (dispatched + failed)
	NodesFailed        int32                  `protobuf:"varint,4,opt,name=nodes_failed,json=nodesFailed,proto3" json:"nodes_failed,omitempty"`                      // Helmsmen the dispatch could not reach; >0 means caller must retry
	FailedNodeIds      []string               `protobuf:"bytes,5,rep,name=failed_node_ids,json=failedNodeIds,proto3" json:"failed_node_ids,omitempty"`               // Identifiers of unreachable Helmsmen, for diagnostic logging
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvalidatePlaybackAuthResponse) Reset() {
	*x = InvalidatePlaybackAuthResponse{}
	mi := &file_foghorn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidatePlaybackAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidatePlaybackAuthResponse) ProtoMessage() {}

func (x *InvalidatePlaybackAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidatePlaybackAuthResponse.ProtoReflect.Descriptor instead.
func (*InvalidatePlaybackAuthResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{15}
}

func (x *InvalidatePlaybackAuthResponse) GetStreamsInvalidated() int32 {
	if x != nil {
		return x.StreamsInvalidated
	}
	return 0
}

func (x *InvalidatePlaybackAuthResponse) GetNodesDispatched() int32 {
	if x != nil {
		return x.NodesDispatched
	}
	return 0
}

func (x *InvalidatePlaybackAuthResponse) GetNodesAttempted() int32 {
	if x != nil {
		return x.NodesAttempted
	}
	return 0
}

func (x *InvalidatePlaybackAuthResponse) GetNodesFailed() int32 {
	if x != nil {
		return x.NodesFailed
	}
	return 0
}

func (x *InvalidatePlaybackAuthResponse) GetFailedNodeIds() []string {
	if x != nil {
		return x.FailedNodeIds
	}
	return nil
}

// InvalidateTenantCacheRequest is sent when a tenant's suspension status changes
type InvalidateTenantCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // e.g., "reactivated", "balance_topped_up"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateTenantCacheRequest) Reset() {
	*x = InvalidateTenantCacheRequest{}
	mi := &file_foghorn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateTenantCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateTenantCacheRequest) ProtoMessage() {}

func (x *InvalidateTenantCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateTenantCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateTenantCacheRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{16}
}

func (x *InvalidateTenantCacheRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *InvalidateTenantCacheRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// InvalidateTenantCacheResponse indicates cache entries invalidated
type InvalidateTenantCacheResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntriesInvalidated int32                  `protobuf:"varint,1,opt,name=entries_invalidated,json=entriesInvalidated,proto3" json:"entries_invalidated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvalidateTenantCacheResponse) Reset() {
	*x = InvalidateTenantCacheResponse{}
	mi := &file_foghorn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateTenantCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateTenantCacheResponse) ProtoMessage() {}

func (x *InvalidateTenantCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateTenantCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateTenantCacheResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{17}
}

func (x *InvalidateTenantCacheResponse) GetEntriesInvalidated() int32 {
	if x != nil {
		return x.EntriesInvalidated
	}
	return 0
}

// TerminateTenantStreamsRequest is sent by Purser when a tenant is suspended
type TerminateTenantStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // e.g., "insufficient_balance", "suspended"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateTenantStreamsRequest) Reset() {
	*x = TerminateTenantStreamsRequest{}
	mi := &file_foghorn_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateTenantStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateTenantStreamsRequest) ProtoMessage() {}

func (x *TerminateTenantStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateTenantStreamsRequest.ProtoReflect.Descriptor instead.
func (*TerminateTenantStreamsRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{18}
}

func (x *TerminateTenantStreamsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TerminateTenantStreamsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TerminateTenantStreamsResponse indicates the result of termination
type TerminateTenantStreamsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StreamsTerminated  int32                  `protobuf:"varint,1,opt,name=streams_terminated,json=streamsTerminated,proto3" json:"streams_terminated,omitempty"`    // Number of streams that were stopped
	SessionsTerminated int32                  `protobuf:"varint,2,opt,name=sessions_terminated,json=sessionsTerminated,proto3" json:"sessions_terminated,omitempty"` // Total number of sessions stopped
	StreamNames        []string               `protobuf:"bytes,3,rep,name=stream_names,json=streamNames,proto3" json:"stream_names,omitempty"`                       // Names of streams that were stopped
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TerminateTenantStreamsResponse) Reset() {
	*x = TerminateTenantStreamsResponse{}
	mi := &file_foghorn_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateTenantStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateTenantStreamsResponse) ProtoMessage() {}

func (x *TerminateTenantStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateTenantStreamsResponse.ProtoReflect.Descriptor instead.
func (*TerminateTenantStreamsResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{19}
}

func (x *TerminateTenantStreamsResponse) GetStreamsTerminated() int32 {
	if x != nil {
		return x.StreamsTerminated
	}
	return 0
}

func (x *TerminateTenantStreamsResponse) GetSessionsTerminated() int32 {
	if x != nil {
		return x.SessionsTerminated
	}
	return 0
}

func (x *TerminateTenantStreamsResponse) GetStreamNames() []string {
	if x != nil {
		return x.StreamNames
	}
	return nil
}

// OverrideArtifactRetentionRequest pushes a new retention horizon onto a
// foghorn.artifacts row. Used by Commodore.UpdateAssetRetention after a
// customer adjusts retention on a finalized DVR / clip / VOD. Active
// artifacts are rejected (retention applies post-finalize only).
type OverrideArtifactRetentionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DvrHash        string                 `protobuf:"bytes,2,opt,name=dvr_hash,json=dvrHash,proto3" json:"dvr_hash,omitempty"` // dvr_hash | clip_hash | vod_hash; matched against foghorn.artifacts.artifact_hash
	RetentionUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=retention_until,json=retentionUntil,proto3" json:"retention_until,omitempty"`
	// Empty string defaults to "dvr"; callers that handle clips or VOD set this
	// explicitly so Foghorn filters the matching artifact type.
	ArtifactType     string `protobuf:"bytes,4,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`     // 'dvr' | 'clip' | 'vod'
	RetentionDays    int32  `protobuf:"varint,5,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"` // used with anchor_to_ended_at
	AnchorToEndedAt  bool   `protobuf:"varint,6,opt,name=anchor_to_ended_at,json=anchorToEndedAt,proto3" json:"anchor_to_ended_at,omitempty"`
	MaxRetentionDays int32  `protobuf:"varint,7,opt,name=max_retention_days,json=maxRetentionDays,proto3" json:"max_retention_days,omitempty"` // tier entitlement bound, enforced against ended_at
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OverrideArtifactRetentionRequest) Reset() {
	*x = OverrideArtifactRetentionRequest{}
	mi := &file_foghorn_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideArtifactRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideArtifactRetentionRequest) ProtoMessage() {}

func (x *OverrideArtifactRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideArtifactRetentionRequest.ProtoReflect.Descriptor instead.
func (*OverrideArtifactRetentionRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{20}
}

func (x *OverrideArtifactRetentionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OverrideArtifactRetentionRequest) GetDvrHash() string {
	if x != nil {
		return x.DvrHash
	}
	return ""
}

func (x *OverrideArtifactRetentionRequest) GetRetentionUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RetentionUntil
	}
	return nil
}

func (x *OverrideArtifactRetentionRequest) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *OverrideArtifactRetentionRequest) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *OverrideArtifactRetentionRequest) GetAnchorToEndedAt() bool {
	if x != nil {
		return x.AnchorToEndedAt
	}
	return false
}

func (x *OverrideArtifactRetentionRequest) GetMaxRetentionDays() int32 {
	if x != nil {
		return x.MaxRetentionDays
	}
	return 0
}

type OverrideArtifactRetentionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Applied        bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	RetentionUntil *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=retention_until,json=retentionUntil,proto3" json:"retention_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OverrideArtifactRetentionResponse) Reset() {
	*x = OverrideArtifactRetentionResponse{}
	mi := &file_foghorn_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideArtifactRetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideArtifactRetentionResponse) ProtoMessage() {}

func (x *OverrideArtifactRetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideArtifactRetentionResponse.ProtoReflect.Descriptor instead.
func (*OverrideArtifactRetentionResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{21}
}

func (x *OverrideArtifactRetentionResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *OverrideArtifactRetentionResponse) GetRetentionUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RetentionUntil
	}
	return nil
}

// TestPlaybackAccessRequest carries the policy target plus the variant the
// caller wants to test. tenant_id is set by Commodore after ownership
// validation; this RPC trusts it.
type TestPlaybackAccessRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Exactly one of playback_id / internal_name must be set. internal_name
	// is what the live USER_NEW path keys on; playback_id is the public
	// identifier customers use everywhere else.
	PlaybackId   string `protobuf:"bytes,2,opt,name=playback_id,json=playbackId,proto3" json:"playback_id,omitempty"`
	InternalName string `protobuf:"bytes,3,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	// JWT mode: caller-supplied token + optional viewer context that the
	// evaluator would ordinarily get from the MistServer trigger payload.
	// viewer_token must be set; the rest are optional and surface only in
	// the deny detail / webhook payload path.
	ViewerToken string `protobuf:"bytes,4,opt,name=viewer_token,json=viewerToken,proto3" json:"viewer_token,omitempty"`
	ViewerIp    string `protobuf:"bytes,5,opt,name=viewer_ip,json=viewerIp,proto3" json:"viewer_ip,omitempty"`
	RequestUrl  string `protobuf:"bytes,6,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	Connector   string `protobuf:"bytes,7,opt,name=connector,proto3" json:"connector,omitempty"`
	SessionId   string `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Webhook mode: when true and the resolved policy is type=webhook, the
	// evaluator fires a real outbound request to the customer URL. Caller
	// is responsible for showing a confirmation in the UI before setting
	// this — webhooks have side effects.
	FireWebhook   bool `protobuf:"varint,9,opt,name=fire_webhook,json=fireWebhook,proto3" json:"fire_webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPlaybackAccessRequest) Reset() {
	*x = TestPlaybackAccessRequest{}
	mi := &file_foghorn_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPlaybackAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPlaybackAccessRequest) ProtoMessage() {}

func (x *TestPlaybackAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPlaybackAccessRequest.ProtoReflect.Descriptor instead.
func (*TestPlaybackAccessRequest) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{22}
}

func (x *TestPlaybackAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetPlaybackId() string {
	if x != nil {
		return x.PlaybackId
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetViewerToken() string {
	if x != nil {
		return x.ViewerToken
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetViewerIp() string {
	if x != nil {
		return x.ViewerIp
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TestPlaybackAccessRequest) GetFireWebhook() bool {
	if x != nil {
		return x.FireWebhook
	}
	return false
}

type TestPlaybackAccessResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	PolicyType       string                 `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`                      // "public" | "jwt" | "webhook" | ""
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                // empty on allow; deny reason token otherwise
	Detail           string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                                                // free-form context (verifier error, status code as text)
	Kid              string                 `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`                                                      // JWT key ID claimed by the token (if any)
	ClaimsJson       string                 `protobuf:"bytes,6,opt,name=claims_json,json=claimsJson,proto3" json:"claims_json,omitempty"`                      // JSON-encoded claims map (verified or not)
	WebhookStatus    int32                  `protobuf:"varint,7,opt,name=webhook_status,json=webhookStatus,proto3" json:"webhook_status,omitempty"`            // HTTP status from the customer URL (webhook mode)
	WebhookLatencyMs int32                  `protobuf:"varint,8,opt,name=webhook_latency_ms,json=webhookLatencyMs,proto3" json:"webhook_latency_ms,omitempty"` // RTT for the webhook call
	// Echo of which policy target the evaluator resolved against. Useful
	// when Commodore mapped a public playback_id to an internal_name for
	// the caller.
	ResolvedInternalName string `protobuf:"bytes,9,opt,name=resolved_internal_name,json=resolvedInternalName,proto3" json:"resolved_internal_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TestPlaybackAccessResponse) Reset() {
	*x = TestPlaybackAccessResponse{}
	mi := &file_foghorn_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPlaybackAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPlaybackAccessResponse) ProtoMessage() {}

func (x *TestPlaybackAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foghorn_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPlaybackAccessResponse.ProtoReflect.Descriptor instead.
func (*TestPlaybackAccessResponse) Descriptor() ([]byte, []int) {
	return file_foghorn_proto_rawDescGZIP(), []int{23}
}

func (x *TestPlaybackAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *TestPlaybackAccessResponse) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *TestPlaybackAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TestPlaybackAccessResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *TestPlaybackAccessResponse) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *TestPlaybackAccessResponse) GetClaimsJson() string {
	if x != nil {
		return x.ClaimsJson
	}
	return ""
}

func (x *TestPlaybackAccessResponse) GetWebhookStatus() int32 {
	if x != nil {
		return x.WebhookStatus
	}
	return 0
}

func (x *TestPlaybackAccessResponse) GetWebhookLatencyMs() int32 {
	if x != nil {
		return x.WebhookLatencyMs
	}
	return 0
}

func (x *TestPlaybackAccessResponse) GetResolvedInternalName() string {
	if x != nil {
		return x.ResolvedInternalName
	}
	return ""
}

var File_foghorn_proto protoreflect.FileDescriptor

const file_foghorn_proto_rawDesc = "" +
	"\n" +
	"\rfoghorn.proto\x12\afoghorn\x1a\fcommon.proto\x1a\fshared.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n" +
	"\x19RetrieveDVRChapterRequest\x12&\n" +
	"\x0fdvr_artifact_id\x18\x01 \x01(\tR\rdvrArtifactId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12\x19\n" +
	"\bstart_ms\x18\x04 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x05 \x01(\x03R\x05endMs\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xf2\x01\n" +
	"\x1aRetrieveDVRChapterResponse\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\tR\tchapterId\x12&\n" +
	"\x0fmanifest_s3_key\x18\x02 \x01(\tR\rmanifestS3Key\x12!\n" +
	"\fmanifest_url\x18\x03 \x01(\tR\vmanifestUrl\x12\x1d\n" +
	"\n" +
	"is_current\x18\x04 \x01(\bR\tisCurrent\x12\x19\n" +
	"\bhas_gaps\x18\x05 \x01(\bR\ahasGaps\x12#\n" +
	"\rsegment_count\x18\x06 \x01(\x05R\fsegmentCountJ\x04\b\a\x10\bR\x05error\"\xa0\x02\n" +
	"\x16ListDVRChaptersRequest\x12&\n" +
	"\x0fdvr_artifact_id\x18\x01 \x01(\tR\rdvrArtifactId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12$\n" +
	"\x0erange_start_ms\x18\x04 \x01(\x03R\frangeStartMs\x12 \n" +
	"\frange_end_ms\x18\x05 \x01(\x03R\n" +
	"rangeEndMs\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\"\xa3\x02\n" +
	"\n" +
	"ChapterRef\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\tR\tchapterId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12\x19\n" +
	"\bstart_ms\x18\x04 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x05 \x01(\x03R\x05endMs\x12\x1d\n" +
	"\n" +
	"is_current\x18\x06 \x01(\bR\tisCurrent\x12&\n" +
	"\x0fmanifest_s3_key\x18\a \x01(\tR\rmanifestS3Key\x12\x19\n" +
	"\bhas_gaps\x18\b \x01(\bR\ahasGaps\x12#\n" +
	"\rsegment_count\x18\t \x01(\x05R\fsegmentCount\"r\n" +
	"\x17ListDVRChaptersResponse\x12/\n" +
	"\bchapters\x18\x01 \x03(\v2\x13.foghorn.ChapterRefR\bchapters\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa0\x01\n" +
	"\x1aSetDVRChapterPolicyRequest\x12&\n" +
	"\x0fdvr_artifact_id\x18\x01 \x01(\tR\rdvrArtifactId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"Q\n" +
	"\x1bSetDVRChapterPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\x16PreRegisterEdgeRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x1f\n" +
	"\vexternal_ip\x18\x02 \x01(\tR\n" +
	"externalIp\x12*\n" +
	"\x11preferred_node_id\x18\x03 \x01(\tR\x0fpreferredNodeId\"\x87\x03\n" +
	"\x17PreRegisterEdgeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vedge_domain\x18\x02 \x01(\tR\n" +
	"edgeDomain\x12\x1f\n" +
	"\vpool_domain\x18\x03 \x01(\tR\n" +
	"poolDomain\x12!\n" +
	"\fcluster_slug\x18\x04 \x01(\tR\vclusterSlug\x12*\n" +
	"\x11foghorn_grpc_addr\x18\x05 \x01(\tR\x0ffoghornGrpcAddr\x12\x1d\n" +
	"\bcert_pem\x18\x06 \x01(\tB\x02\x18\x01R\acertPem\x12\x1b\n" +
	"\akey_pem\x18\a \x01(\tB\x02\x18\x01R\x06keyPem\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\b \x01(\tR\tclusterId\x12,\n" +
	"\x12internal_ca_bundle\x18\t \x01(\fR\x10internalCaBundle\x129\n" +
	"\ttelemetry\x18\n" +
	" \x01(\v2\x1b.common.EdgeTelemetryConfigR\ttelemetry\"X\n" +
	"\x12SetNodeModeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x15\n" +
	"\x06set_by\x18\x03 \x01(\tR\x05setBy\"\x90\x01\n" +
	"\x13SetNodeModeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.foghorn.SetNodeModeStatusR\x06status\"/\n" +
	"\x14GetNodeHealthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa5\x06\n" +
	"\x15GetNodeHealthResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x10operational_mode\x18\x02 \x01(\tR\x0foperationalMode\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x03 \x01(\bR\tisHealthy\x12%\n" +
	"\x0eactive_viewers\x18\x04 \x01(\x05R\ractiveViewers\x12%\n" +
	"\x0eactive_streams\x18\x05 \x01(\x05R\ractiveStreams\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\tR\rlastHeartbeat\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\a \x01(\tR\tclusterId\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x1f\n" +
	"\vcpu_percent\x18\t \x01(\x01R\n" +
	"cpuPercent\x12\x1e\n" +
	"\vram_used_mb\x18\n" +
	" \x01(\x01R\tramUsedMb\x12\x1c\n" +
	"\n" +
	"ram_max_mb\x18\v \x01(\x01R\bramMaxMb\x12*\n" +
	"\x11bandwidth_up_mbps\x18\f \x01(\x01R\x0fbandwidthUpMbps\x12.\n" +
	"\x13bandwidth_down_mbps\x18\r \x01(\x01R\x11bandwidthDownMbps\x12\"\n" +
	"\rbw_limit_mbps\x18\x0e \x01(\x01R\vbwLimitMbps\x12(\n" +
	"\x10disk_total_bytes\x18\x0f \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x10 \x01(\x04R\rdiskUsedBytes\x12\x1a\n" +
	"\blocation\x18\x11 \x01(\tR\blocation\x12\x1f\n" +
	"\blatitude\x18\x12 \x01(\x01H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x13 \x01(\x01H\x01R\tlongitude\x88\x01\x01\x12L\n" +
	"\x12component_versions\x18\x14 \x03(\v2\x1d.foghorn.NodeComponentVersionR\x11componentVersionsB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"N\n" +
	"\x14NodeComponentVersion\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xc6\x01\n" +
	"\x1dInvalidatePlaybackAuthRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0einternal_names\x18\x02 \x03(\tR\rinternalNames\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x12,\n" +
	"\x12bundle_min_version\x18\x05 \x01(\x03R\x10bundleMinVersion\"\xf0\x01\n" +
	"\x1eInvalidatePlaybackAuthResponse\x12/\n" +
	"\x13streams_invalidated\x18\x01 \x01(\x05R\x12streamsInvalidated\x12)\n" +
	"\x10nodes_dispatched\x18\x02 \x01(\x05R\x0fnodesDispatched\x12'\n" +
	"\x0fnodes_attempted\x18\x03 \x01(\x05R\x0enodesAttempted\x12!\n" +
	"\fnodes_failed\x18\x04 \x01(\x05R\vnodesFailed\x12&\n" +
	"\x0ffailed_node_ids\x18\x05 \x03(\tR\rfailedNodeIds\"S\n" +
	"\x1cInvalidateTenantCacheRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"P\n" +
	"\x1dInvalidateTenantCacheResponse\x12/\n" +
	"\x13entries_invalidated\x18\x01 \x01(\x05R\x12entriesInvalidated\"T\n" +
	"\x1dTerminateTenantStreamsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa3\x01\n" +
	"\x1eTerminateTenantStreamsResponse\x12-\n" +
	"\x12streams_terminated\x18\x01 \x01(\x05R\x11streamsTerminated\x12/\n" +
	"\x13sessions_terminated\x18\x02 \x01(\x05R\x12sessionsTerminated\x12!\n" +
	"\fstream_names\x18\x03 \x03(\tR\vstreamNames\"\xc6\x02\n" +
	" OverrideArtifactRetentionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bdvr_hash\x18\x02 \x01(\tR\advrHash\x12C\n" +
	"\x0fretention_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eretentionUntil\x12#\n" +
	"\rartifact_type\x18\x04 \x01(\tR\fartifactType\x12%\n" +
	"\x0eretention_days\x18\x05 \x01(\x05R\rretentionDays\x12+\n" +
	"\x12anchor_to_ended_at\x18\x06 \x01(\bR\x0fanchorToEndedAt\x12,\n" +
	"\x12max_retention_days\x18\a \x01(\x05R\x10maxRetentionDays\"\x82\x01\n" +
	"!OverrideArtifactRetentionResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12C\n" +
	"\x0fretention_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eretentionUntil\"\xbf\x02\n" +
	"\x19TestPlaybackAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vplayback_id\x18\x02 \x01(\tR\n" +
	"playbackId\x12#\n" +
	"\rinternal_name\x18\x03 \x01(\tR\finternalName\x12!\n" +
	"\fviewer_token\x18\x04 \x01(\tR\vviewerToken\x12\x1b\n" +
	"\tviewer_ip\x18\x05 \x01(\tR\bviewerIp\x12\x1f\n" +
	"\vrequest_url\x18\x06 \x01(\tR\n" +
	"requestUrl\x12\x1c\n" +
	"\tconnector\x18\a \x01(\tR\tconnector\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12!\n" +
	"\ffire_webhook\x18\t \x01(\bR\vfireWebhook\"\xc5\x02\n" +
	"\x1aTestPlaybackAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1f\n" +
	"\vpolicy_type\x18\x02 \x01(\tR\n" +
	"policyType\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x10\n" +
	"\x03kid\x18\x05 \x01(\tR\x03kid\x12\x1f\n" +
	"\vclaims_json\x18\x06 \x01(\tR\n" +
	"claimsJson\x12%\n" +
	"\x0ewebhook_status\x18\a \x01(\x05R\rwebhookStatus\x12,\n" +
	"\x12webhook_latency_ms\x18\b \x01(\x05R\x10webhookLatencyMs\x124\n" +
	"\x16resolved_internal_name\x18\t \x01(\tR\x14resolvedInternalName*\xd0\x01\n" +
	"\x11SetNodeModeStatus\x12$\n" +
	" SET_NODE_MODE_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSET_NODE_MODE_STATUS_SUCCESS\x10\x01\x12%\n" +
	"!SET_NODE_MODE_STATUS_INVALID_MODE\x10\x02\x12\"\n" +
	"\x1eSET_NODE_MODE_STATUS_NOT_FOUND\x10\x03\x12(\n" +
	"$SET_NODE_MODE_STATUS_ALREADY_IN_MODE\x10\x042\x9e\x01\n" +
	"\x12ClipControlService\x12C\n" +
	"\n" +
	"CreateClip\x12\x19.shared.CreateClipRequest\x1a\x1a.shared.CreateClipResponse\x12C\n" +
	"\n" +
	"DeleteClip\x12\x19.shared.DeleteClipRequest\x1a\x1a.shared.DeleteClipResponse2\xba\x05\n" +
	"\x11DVRControlService\x12=\n" +
	"\bStartDVR\x12\x17.shared.StartDVRRequest\x1a\x18.shared.StartDVRResponse\x12:\n" +
	"\aStopDVR\x12\x16.shared.StopDVRRequest\x1a\x17.shared.StopDVRResponse\x12@\n" +
	"\tDeleteDVR\x12\x18.shared.DeleteDVRRequest\x1a\x19.shared.DeleteDVRResponse\x12]\n" +
	"\x12RetrieveDVRChapter\x12\".foghorn.RetrieveDVRChapterRequest\x1a#.foghorn.RetrieveDVRChapterResponse\x12T\n" +
	"\x0fListDVRChapters\x12\x1f.foghorn.ListDVRChaptersRequest\x1a .foghorn.ListDVRChaptersResponse\x12`\n" +
	"\x13SetDVRChapterPolicy\x12#.foghorn.SetDVRChapterPolicyRequest\x1a$.foghorn.SetDVRChapterPolicyResponse\x12r\n" +
	"\x19OverrideArtifactRetention\x12).foghorn.OverrideArtifactRetentionRequest\x1a*.foghorn.OverrideArtifactRetentionResponse\x12]\n" +
	"\x12TestPlaybackAccess\x12\".foghorn.TestPlaybackAccessRequest\x1a#.foghorn.TestPlaybackAccessResponse2\xc6\x01\n" +
	"\x14ViewerControlService\x12V\n" +
	"\x15ResolveViewerEndpoint\x12\x1d.shared.ViewerEndpointRequest\x1a\x1e.shared.ViewerEndpointResponse\x12V\n" +
	"\x15ResolveIngestEndpoint\x12\x1d.shared.IngestEndpointRequest\x1a\x1e.shared.IngestEndpointResponse2\xcf\x04\n" +
	"\x11VodControlService\x12R\n" +
	"\x0fCreateVodUpload\x12\x1e.shared.CreateVodUploadRequest\x1a\x1f.shared.CreateVodUploadResponse\x12X\n" +
	"\x11CompleteVodUpload\x12 .shared.CompleteVodUploadRequest\x1a!.shared.CompleteVodUploadResponse\x12O\n" +
	"\x0eAbortVodUpload\x12\x1d.shared.AbortVodUploadRequest\x1a\x1e.shared.AbortVodUploadResponse\x12[\n" +
	"\x12GetVodUploadStatus\x12!.shared.GetVodUploadStatusRequest\x1a\".shared.GetVodUploadStatusResponse\x12?\n" +
	"\vGetVodAsset\x12\x1a.shared.GetVodAssetRequest\x1a\x14.shared.VodAssetInfo\x12L\n" +
	"\rListVodAssets\x12\x1c.shared.ListVodAssetsRequest\x1a\x1d.shared.ListVodAssetsResponse\x12O\n" +
	"\x0eDeleteVodAsset\x12\x1d.shared.DeleteVodAssetRequest\x1a\x1e.shared.DeleteVodAssetResponse2o\n" +
	"\x17EdgeProvisioningService\x12T\n" +
	"\x0fPreRegisterEdge\x12\x1f.foghorn.PreRegisterEdgeRequest\x1a .foghorn.PreRegisterEdgeResponse2\xb9\x01\n" +
	"\x12NodeControlService\x12S\n" +
	"\x16SetNodeOperationalMode\x12\x1b.foghorn.SetNodeModeRequest\x1a\x1c.foghorn.SetNodeModeResponse\x12N\n" +
	"\rGetNodeHealth\x12\x1d.foghorn.GetNodeHealthRequest\x1a\x1e.foghorn.GetNodeHealthResponse2\xd4\x02\n" +
	"\x14TenantControlService\x12i\n" +
	"\x16TerminateTenantStreams\x12&.foghorn.TerminateTenantStreamsRequest\x1a'.foghorn.TerminateTenantStreamsResponse\x12f\n" +
	"\x15InvalidateTenantCache\x12%.foghorn.InvalidateTenantCacheRequest\x1a&.foghorn.InvalidateTenantCacheResponse\x12i\n" +
	"\x16InvalidatePlaybackAuth\x12&.foghorn.InvalidatePlaybackAuthRequest\x1a'.foghorn.InvalidatePlaybackAuthResponseB3Z1github.com/Livepeer-FrameWorks/monorepo/pkg/protob\x06proto3"

var (
	file_foghorn_proto_rawDescOnce sync.Once
	file_foghorn_proto_rawDescData []byte
)

func file_foghorn_proto_rawDescGZIP() []byte {
	file_foghorn_proto_rawDescOnce.Do(func() {
		file_foghorn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foghorn_proto_rawDesc), len(file_foghorn_proto_rawDesc)))
	})
	return file_foghorn_proto_rawDescData
}

var file_foghorn_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_foghorn_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_foghorn_proto_goTypes = []any{
	(SetNodeModeStatus)(0),                    // 0: foghorn.SetNodeModeStatus
	(*RetrieveDVRChapterRequest)(nil),         // 1: foghorn.RetrieveDVRChapterRequest
	(*RetrieveDVRChapterResponse)(nil),        // 2: foghorn.RetrieveDVRChapterResponse
	(*ListDVRChaptersRequest)(nil),            // 3: foghorn.ListDVRChaptersRequest
	(*ChapterRef)(nil),                        // 4: foghorn.ChapterRef
	(*ListDVRChaptersResponse)(nil),           // 5: foghorn.ListDVRChaptersResponse
	(*SetDVRChapterPolicyRequest)(nil),        // 6: foghorn.SetDVRChapterPolicyRequest
	(*SetDVRChapterPolicyResponse)(nil),       // 7: foghorn.SetDVRChapterPolicyResponse
	(*PreRegisterEdgeRequest)(nil),            // 8: foghorn.PreRegisterEdgeRequest
	(*PreRegisterEdgeResponse)(nil),           // 9: foghorn.PreRegisterEdgeResponse
	(*SetNodeModeRequest)(nil),                // 10: foghorn.SetNodeModeRequest
	(*SetNodeModeResponse)(nil),               // 11: foghorn.SetNodeModeResponse
	(*GetNodeHealthRequest)(nil),              // 12: foghorn.GetNodeHealthRequest
	(*GetNodeHealthResponse)(nil),             // 13: foghorn.GetNodeHealthResponse
	(*NodeComponentVersion)(nil),              // 14: foghorn.NodeComponentVersion
	(*InvalidatePlaybackAuthRequest)(nil),     // 15: foghorn.InvalidatePlaybackAuthRequest
	(*InvalidatePlaybackAuthResponse)(nil),    // 16: foghorn.InvalidatePlaybackAuthResponse
	(*InvalidateTenantCacheRequest)(nil),      // 17: foghorn.InvalidateTenantCacheRequest
	(*InvalidateTenantCacheResponse)(nil),     // 18: foghorn.InvalidateTenantCacheResponse
	(*TerminateTenantStreamsRequest)(nil),     // 19: foghorn.TerminateTenantStreamsRequest
	(*TerminateTenantStreamsResponse)(nil),    // 20: foghorn.TerminateTenantStreamsResponse
	(*OverrideArtifactRetentionRequest)(nil),  // 21: foghorn.OverrideArtifactRetentionRequest
	(*OverrideArtifactRetentionResponse)(nil), // 22: foghorn.OverrideArtifactRetentionResponse
	(*TestPlaybackAccessRequest)(nil),         // 23: foghorn.TestPlaybackAccessRequest
	(*TestPlaybackAccessResponse)(nil),        // 24: foghorn.TestPlaybackAccessResponse
	(*EdgeTelemetryConfig)(nil),               // 25: common.EdgeTelemetryConfig
	(*timestamppb.Timestamp)(nil),             // 26: google.protobuf.Timestamp
	(*CreateClipRequest)(nil),                 // 27: shared.CreateClipRequest
	(*DeleteClipRequest)(nil),                 // 28: shared.DeleteClipRequest
	(*StartDVRRequest)(nil),                   // 29: shared.StartDVRRequest
	(*StopDVRRequest)(nil),                    // 30: shared.StopDVRRequest
	(*DeleteDVRRequest)(nil),                  // 31: shared.DeleteDVRRequest
	(*ViewerEndpointRequest)(nil),             // 32: shared.ViewerEndpointRequest
	(*IngestEndpointRequest)(nil),             // 33: shared.IngestEndpointRequest
	(*CreateVodUploadRequest)(nil),            // 34: shared.CreateVodUploadRequest
	(*CompleteVodUploadRequest)(nil),          // 35: shared.CompleteVodUploadRequest
	(*AbortVodUploadRequest)(nil),             // 36: shared.AbortVodUploadRequest
	(*GetVodUploadStatusRequest)(nil),         // 37: shared.GetVodUploadStatusRequest
	(*GetVodAssetRequest)(nil),                // 38: shared.GetVodAssetRequest
	(*ListVodAssetsRequest)(nil),              // 39: shared.ListVodAssetsRequest
	(*DeleteVodAssetRequest)(nil),             // 40: shared.DeleteVodAssetRequest
	(*CreateClipResponse)(nil),                // 41: shared.CreateClipResponse
	(*DeleteClipResponse)(nil),                // 42: shared.DeleteClipResponse
	(*StartDVRResponse)(nil),                  // 43: shared.StartDVRResponse
	(*StopDVRResponse)(nil),                   // 44: shared.StopDVRResponse
	(*DeleteDVRResponse)(nil),                 // 45: shared.DeleteDVRResponse
	(*ViewerEndpointResponse)(nil),            // 46: shared.ViewerEndpointResponse
	(*IngestEndpointResponse)(nil),            // 47: shared.IngestEndpointResponse
	(*CreateVodUploadResponse)(nil),           // 48: shared.CreateVodUploadResponse
	(*CompleteVodUploadResponse)(nil),         // 49: shared.CompleteVodUploadResponse
	(*AbortVodUploadResponse)(nil),            // 50: shared.AbortVodUploadResponse
	(*GetVodUploadStatusResponse)(nil),        // 51: shared.GetVodUploadStatusResponse
	(*VodAssetInfo)(nil),                      // 52: shared.VodAssetInfo
	(*ListVodAssetsResponse)(nil),             // 53: shared.ListVodAssetsResponse
	(*DeleteVodAssetResponse)(nil),            // 54: shared.DeleteVodAssetResponse
}
var file_foghorn_proto_depIdxs = []int32{
	4,  // 0: foghorn.ListDVRChaptersResponse.chapters:type_name -> foghorn.ChapterRef
	25, // 1: foghorn.PreRegisterEdgeResponse.telemetry:type_name -> common.EdgeTelemetryConfig
	0,  // 2: foghorn.SetNodeModeResponse.status:type_name -> foghorn.SetNodeModeStatus
	14, // 3: foghorn.GetNodeHealthResponse.component_versions:type_name -> foghorn.NodeComponentVersion
	26, // 4: foghorn.OverrideArtifactRetentionRequest.retention_until:type_name -> google.protobuf.Timestamp
	26, // 5: foghorn.OverrideArtifactRetentionResponse.retention_until:type_name -> google.protobuf.Timestamp
	27, // 6: foghorn.ClipControlService.CreateClip:input_type -> shared.CreateClipRequest
	28, // 7: foghorn.ClipControlService.DeleteClip:input_type -> shared.DeleteClipRequest
	29, // 8: foghorn.DVRControlService.StartDVR:input_type -> shared.StartDVRRequest
	30, // 9: foghorn.DVRControlService.StopDVR:input_type -> shared.StopDVRRequest
	31, // 10: foghorn.DVRControlService.DeleteDVR:input_type -> shared.DeleteDVRRequest
	1,  // 11: foghorn.DVRControlService.RetrieveDVRChapter:input_type -> foghorn.RetrieveDVRChapterRequest
	3,  // 12: foghorn.DVRControlService.ListDVRChapters:input_type -> foghorn.ListDVRChaptersRequest
	6,  // 13: foghorn.DVRControlService.SetDVRChapterPolicy:input_type -> foghorn.SetDVRChapterPolicyRequest
	21, // 14: foghorn.DVRControlService.OverrideArtifactRetention:input_type -> foghorn.OverrideArtifactRetentionRequest
	23, // 15: foghorn.DVRControlService.TestPlaybackAccess:input_type -> foghorn.TestPlaybackAccessRequest
	32, // 16: foghorn.ViewerControlService.ResolveViewerEndpoint:input_type -> shared.ViewerEndpointRequest
	33, // 17: foghorn.ViewerControlService.ResolveIngestEndpoint:input_type -> shared.IngestEndpointRequest
	34, // 18: foghorn.VodControlService.CreateVodUpload:input_type -> shared.CreateVodUploadRequest
	35, // 19: foghorn.VodControlService.CompleteVodUpload:input_type -> shared.CompleteVodUploadRequest
	36, // 20: foghorn.VodControlService.AbortVodUpload:input_type -> shared.AbortVodUploadRequest
	37, // 21: foghorn.VodControlService.GetVodUploadStatus:input_type -> shared.GetVodUploadStatusRequest
	38, // 22: foghorn.VodControlService.GetVodAsset:input_type -> shared.GetVodAssetRequest
	39, // 23: foghorn.VodControlService.ListVodAssets:input_type -> shared.ListVodAssetsRequest
	40, // 24: foghorn.VodControlService.DeleteVodAsset:input_type -> shared.DeleteVodAssetRequest
	8,  // 25: foghorn.EdgeProvisioningService.PreRegisterEdge:input_type -> foghorn.PreRegisterEdgeRequest
	10, // 26: foghorn.NodeControlService.SetNodeOperationalMode:input_type -> foghorn.SetNodeModeRequest
	12, // 27: foghorn.NodeControlService.GetNodeHealth:input_type -> foghorn.GetNodeHealthRequest
	19, // 28: foghorn.TenantControlService.TerminateTenantStreams:input_type -> foghorn.TerminateTenantStreamsRequest
	17, // 29: foghorn.TenantControlService.InvalidateTenantCache:input_type -> foghorn.InvalidateTenantCacheRequest
	15, // 30: foghorn.TenantControlService.InvalidatePlaybackAuth:input_type -> foghorn.InvalidatePlaybackAuthRequest
	41, // 31: foghorn.ClipControlService.CreateClip:output_type -> shared.CreateClipResponse
	42, // 32: foghorn.ClipControlService.DeleteClip:output_type -> shared.DeleteClipResponse
	43, // 33: foghorn.DVRControlService.StartDVR:output_type -> shared.StartDVRResponse
	44, // 34: foghorn.DVRControlService.StopDVR:output_type -> shared.StopDVRResponse
	45, // 35: foghorn.DVRControlService.DeleteDVR:output_type -> shared.DeleteDVRResponse
	2,  // 36: foghorn.DVRControlService.RetrieveDVRChapter:output_type -> foghorn.RetrieveDVRChapterResponse
	5,  // 37: foghorn.DVRControlService.ListDVRChapters:output_type -> foghorn.ListDVRChaptersResponse
	7,  // 38: foghorn.DVRControlService.SetDVRChapterPolicy:output_type -> foghorn.SetDVRChapterPolicyResponse
	22, // 39: foghorn.DVRControlService.OverrideArtifactRetention:output_type -> foghorn.OverrideArtifactRetentionResponse
	24, // 40: foghorn.DVRControlService.TestPlaybackAccess:output_type -> foghorn.TestPlaybackAccessResponse
	46, // 41: foghorn.ViewerControlService.ResolveViewerEndpoint:output_type -> shared.ViewerEndpointResponse
	47, // 42: foghorn.ViewerControlService.ResolveIngestEndpoint:output_type -> shared.IngestEndpointResponse
	48, // 43: foghorn.VodControlService.CreateVodUpload:output_type -> shared.CreateVodUploadResponse
	49, // 44: foghorn.VodControlService.CompleteVodUpload:output_type -> shared.CompleteVodUploadResponse
	50, // 45: foghorn.VodControlService.AbortVodUpload:output_type -> shared.AbortVodUploadResponse
	51, // 46: foghorn.VodControlService.GetVodUploadStatus:output_type -> shared.GetVodUploadStatusResponse
	52, // 47: foghorn.VodControlService.GetVodAsset:output_type -> shared.VodAssetInfo
	53, // 48: foghorn.VodControlService.ListVodAssets:output_type -> shared.ListVodAssetsResponse
	54, // 49: foghorn.VodControlService.DeleteVodAsset:output_type -> shared.DeleteVodAssetResponse
	9,  // 50: foghorn.EdgeProvisioningService.PreRegisterEdge:output_type -> foghorn.PreRegisterEdgeResponse
	11, // 51: foghorn.NodeControlService.SetNodeOperationalMode:output_type -> foghorn.SetNodeModeResponse
	13, // 52: foghorn.NodeControlService.GetNodeHealth:output_type -> foghorn.GetNodeHealthResponse
	20, // 53: foghorn.TenantControlService.TerminateTenantStreams:output_type -> foghorn.TerminateTenantStreamsResponse
	18, // 54: foghorn.TenantControlService.InvalidateTenantCache:output_type -> foghorn.InvalidateTenantCacheResponse
	16, // 55: foghorn.TenantControlService.InvalidatePlaybackAuth:output_type -> foghorn.InvalidatePlaybackAuthResponse
	31, // [31:56] is the sub-list for method output_type
	6,  // [6:31] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_foghorn_proto_init() }
func file_foghorn_proto_init() {
	if File_foghorn_proto != nil {
		return
	}
	file_common_proto_init()
	file_shared_proto_init()
	file_foghorn_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foghorn_proto_rawDesc), len(file_foghorn_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_foghorn_proto_goTypes,
		DependencyIndexes: file_foghorn_proto_depIdxs,
		EnumInfos:         file_foghorn_proto_enumTypes,
		MessageInfos:      file_foghorn_proto_msgTypes,
	}.Build()
	File_foghorn_proto = out.File
	file_foghorn_proto_goTypes = nil
	file_foghorn_proto_depIdxs = nil
}
