// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: ipc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	HelmsmanControl_Connect_FullMethodName         = "/helmsmancontrol.HelmsmanControl/Connect"
	HelmsmanControl_ResolveClipHash_FullMethodName = "/helmsmancontrol.HelmsmanControl/ResolveClipHash"
)

// HelmsmanControlClient is the client API for HelmsmanControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelmsmanControlClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (HelmsmanControl_ConnectClient, error)
	ResolveClipHash(ctx context.Context, in *ClipHashRequest, opts ...grpc.CallOption) (*ClipHashResponse, error)
}

type helmsmanControlClient struct {
	cc grpc.ClientConnInterface
}

func NewHelmsmanControlClient(cc grpc.ClientConnInterface) HelmsmanControlClient {
	return &helmsmanControlClient{cc}
}

func (c *helmsmanControlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (HelmsmanControl_ConnectClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HelmsmanControl_ServiceDesc.Streams[0], HelmsmanControl_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &helmsmanControlConnectClient{ClientStream: stream}
	return x, nil
}

type HelmsmanControl_ConnectClient interface {
	Send(*ControlMessage) error
	Recv() (*ControlMessage, error)
	grpc.ClientStream
}

type helmsmanControlConnectClient struct {
	grpc.ClientStream
}

func (x *helmsmanControlConnectClient) Send(m *ControlMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helmsmanControlConnectClient) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helmsmanControlClient) ResolveClipHash(ctx context.Context, in *ClipHashRequest, opts ...grpc.CallOption) (*ClipHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClipHashResponse)
	err := c.cc.Invoke(ctx, HelmsmanControl_ResolveClipHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelmsmanControlServer is the server API for HelmsmanControl service.
// All implementations must embed UnimplementedHelmsmanControlServer
// for forward compatibility
type HelmsmanControlServer interface {
	Connect(HelmsmanControl_ConnectServer) error
	ResolveClipHash(context.Context, *ClipHashRequest) (*ClipHashResponse, error)
	mustEmbedUnimplementedHelmsmanControlServer()
}

// UnimplementedHelmsmanControlServer must be embedded to have forward compatible implementations.
type UnimplementedHelmsmanControlServer struct {
}

func (UnimplementedHelmsmanControlServer) Connect(HelmsmanControl_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHelmsmanControlServer) ResolveClipHash(context.Context, *ClipHashRequest) (*ClipHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveClipHash not implemented")
}
func (UnimplementedHelmsmanControlServer) mustEmbedUnimplementedHelmsmanControlServer() {}

// UnsafeHelmsmanControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelmsmanControlServer will
// result in compilation errors.
type UnsafeHelmsmanControlServer interface {
	mustEmbedUnimplementedHelmsmanControlServer()
}

func RegisterHelmsmanControlServer(s grpc.ServiceRegistrar, srv HelmsmanControlServer) {
	s.RegisterService(&HelmsmanControl_ServiceDesc, srv)
}

func _HelmsmanControl_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelmsmanControlServer).Connect(&helmsmanControlConnectServer{ServerStream: stream})
}

type HelmsmanControl_ConnectServer interface {
	Send(*ControlMessage) error
	Recv() (*ControlMessage, error)
	grpc.ServerStream
}

type helmsmanControlConnectServer struct {
	grpc.ServerStream
}

func (x *helmsmanControlConnectServer) Send(m *ControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helmsmanControlConnectServer) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelmsmanControl_ResolveClipHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmsmanControlServer).ResolveClipHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelmsmanControl_ResolveClipHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmsmanControlServer).ResolveClipHash(ctx, req.(*ClipHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelmsmanControl_ServiceDesc is the grpc.ServiceDesc for HelmsmanControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelmsmanControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helmsmancontrol.HelmsmanControl",
	HandlerType: (*HelmsmanControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveClipHash",
			Handler:    _HelmsmanControl_ResolveClipHash_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _HelmsmanControl_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ipc.proto",
}

const (
	DecklogService_SendEvent_FullMethodName        = "/helmsmancontrol.DecklogService/SendEvent"
	DecklogService_SendServiceEvent_FullMethodName = "/helmsmancontrol.DecklogService/SendServiceEvent"
)

// DecklogServiceClient is the client API for DecklogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for sending events to Decklog (Foghorn -> Decklog/api_firehose)
// - MistTrigger: media-plane analytics/events
// - ServiceEvent: service-plane telemetry (API usage, messaging, etc.)
// All producers MUST preserve the original payload (no rewriting).
type DecklogServiceClient interface {
	// Unified entrypoint for all events (unary is fine for now).
	SendEvent(ctx context.Context, in *MistTrigger, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Service-plane events (non-media).
	SendServiceEvent(ctx context.Context, in *ServiceEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type decklogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecklogServiceClient(cc grpc.ClientConnInterface) DecklogServiceClient {
	return &decklogServiceClient{cc}
}

func (c *decklogServiceClient) SendEvent(ctx context.Context, in *MistTrigger, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DecklogService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decklogServiceClient) SendServiceEvent(ctx context.Context, in *ServiceEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DecklogService_SendServiceEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecklogServiceServer is the server API for DecklogService service.
// All implementations must embed UnimplementedDecklogServiceServer
// for forward compatibility
//
// Service for sending events to Decklog (Foghorn -> Decklog/api_firehose)
// - MistTrigger: media-plane analytics/events
// - ServiceEvent: service-plane telemetry (API usage, messaging, etc.)
// All producers MUST preserve the original payload (no rewriting).
type DecklogServiceServer interface {
	// Unified entrypoint for all events (unary is fine for now).
	SendEvent(context.Context, *MistTrigger) (*emptypb.Empty, error)
	// Service-plane events (non-media).
	SendServiceEvent(context.Context, *ServiceEvent) (*emptypb.Empty, error)
	mustEmbedUnimplementedDecklogServiceServer()
}

// UnimplementedDecklogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDecklogServiceServer struct {
}

func (UnimplementedDecklogServiceServer) SendEvent(context.Context, *MistTrigger) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedDecklogServiceServer) SendServiceEvent(context.Context, *ServiceEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendServiceEvent not implemented")
}
func (UnimplementedDecklogServiceServer) mustEmbedUnimplementedDecklogServiceServer() {}

// UnsafeDecklogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecklogServiceServer will
// result in compilation errors.
type UnsafeDecklogServiceServer interface {
	mustEmbedUnimplementedDecklogServiceServer()
}

func RegisterDecklogServiceServer(s grpc.ServiceRegistrar, srv DecklogServiceServer) {
	s.RegisterService(&DecklogService_ServiceDesc, srv)
}

func _DecklogService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MistTrigger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecklogServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecklogService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecklogServiceServer).SendEvent(ctx, req.(*MistTrigger))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecklogService_SendServiceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecklogServiceServer).SendServiceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecklogService_SendServiceEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecklogServiceServer).SendServiceEvent(ctx, req.(*ServiceEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// DecklogService_ServiceDesc is the grpc.ServiceDesc for DecklogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecklogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helmsmancontrol.DecklogService",
	HandlerType: (*DecklogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _DecklogService_SendEvent_Handler,
		},
		{
			MethodName: "SendServiceEvent",
			Handler:    _DecklogService_SendServiceEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipc.proto",
}
