// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: skipper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkipperChatService_Chat_FullMethodName                    = "/skipper.SkipperChatService/Chat"
	SkipperChatService_ListConversations_FullMethodName       = "/skipper.SkipperChatService/ListConversations"
	SkipperChatService_GetConversation_FullMethodName         = "/skipper.SkipperChatService/GetConversation"
	SkipperChatService_DeleteConversation_FullMethodName      = "/skipper.SkipperChatService/DeleteConversation"
	SkipperChatService_UpdateConversationTitle_FullMethodName = "/skipper.SkipperChatService/UpdateConversationTitle"
)

// SkipperChatServiceClient is the client API for SkipperChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkipperChatServiceClient interface {
	// Stream chat completion with tool execution.
	// Creates a new conversation if conversation_id is empty.
	Chat(ctx context.Context, in *SkipperChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SkipperChatEvent], error)
	ListConversations(ctx context.Context, in *ListSkipperConversationsRequest, opts ...grpc.CallOption) (*ListSkipperConversationsResponse, error)
	GetConversation(ctx context.Context, in *GetSkipperConversationRequest, opts ...grpc.CallOption) (*SkipperConversationDetail, error)
	DeleteConversation(ctx context.Context, in *DeleteSkipperConversationRequest, opts ...grpc.CallOption) (*DeleteSkipperConversationResponse, error)
	UpdateConversationTitle(ctx context.Context, in *UpdateSkipperConversationTitleRequest, opts ...grpc.CallOption) (*SkipperConversationSummary, error)
}

type skipperChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkipperChatServiceClient(cc grpc.ClientConnInterface) SkipperChatServiceClient {
	return &skipperChatServiceClient{cc}
}

func (c *skipperChatServiceClient) Chat(ctx context.Context, in *SkipperChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SkipperChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SkipperChatService_ServiceDesc.Streams[0], SkipperChatService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SkipperChatRequest, SkipperChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkipperChatService_ChatClient = grpc.ServerStreamingClient[SkipperChatEvent]

func (c *skipperChatServiceClient) ListConversations(ctx context.Context, in *ListSkipperConversationsRequest, opts ...grpc.CallOption) (*ListSkipperConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkipperConversationsResponse)
	err := c.cc.Invoke(ctx, SkipperChatService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skipperChatServiceClient) GetConversation(ctx context.Context, in *GetSkipperConversationRequest, opts ...grpc.CallOption) (*SkipperConversationDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkipperConversationDetail)
	err := c.cc.Invoke(ctx, SkipperChatService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skipperChatServiceClient) DeleteConversation(ctx context.Context, in *DeleteSkipperConversationRequest, opts ...grpc.CallOption) (*DeleteSkipperConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSkipperConversationResponse)
	err := c.cc.Invoke(ctx, SkipperChatService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skipperChatServiceClient) UpdateConversationTitle(ctx context.Context, in *UpdateSkipperConversationTitleRequest, opts ...grpc.CallOption) (*SkipperConversationSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkipperConversationSummary)
	err := c.cc.Invoke(ctx, SkipperChatService_UpdateConversationTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkipperChatServiceServer is the server API for SkipperChatService service.
// All implementations must embed UnimplementedSkipperChatServiceServer
// for forward compatibility.
type SkipperChatServiceServer interface {
	// Stream chat completion with tool execution.
	// Creates a new conversation if conversation_id is empty.
	Chat(*SkipperChatRequest, grpc.ServerStreamingServer[SkipperChatEvent]) error
	ListConversations(context.Context, *ListSkipperConversationsRequest) (*ListSkipperConversationsResponse, error)
	GetConversation(context.Context, *GetSkipperConversationRequest) (*SkipperConversationDetail, error)
	DeleteConversation(context.Context, *DeleteSkipperConversationRequest) (*DeleteSkipperConversationResponse, error)
	UpdateConversationTitle(context.Context, *UpdateSkipperConversationTitleRequest) (*SkipperConversationSummary, error)
	mustEmbedUnimplementedSkipperChatServiceServer()
}

// UnimplementedSkipperChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkipperChatServiceServer struct{}

func (UnimplementedSkipperChatServiceServer) Chat(*SkipperChatRequest, grpc.ServerStreamingServer[SkipperChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedSkipperChatServiceServer) ListConversations(context.Context, *ListSkipperConversationsRequest) (*ListSkipperConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedSkipperChatServiceServer) GetConversation(context.Context, *GetSkipperConversationRequest) (*SkipperConversationDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedSkipperChatServiceServer) DeleteConversation(context.Context, *DeleteSkipperConversationRequest) (*DeleteSkipperConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedSkipperChatServiceServer) UpdateConversationTitle(context.Context, *UpdateSkipperConversationTitleRequest) (*SkipperConversationSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConversationTitle not implemented")
}
func (UnimplementedSkipperChatServiceServer) mustEmbedUnimplementedSkipperChatServiceServer() {}
func (UnimplementedSkipperChatServiceServer) testEmbeddedByValue()                            {}

// UnsafeSkipperChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkipperChatServiceServer will
// result in compilation errors.
type UnsafeSkipperChatServiceServer interface {
	mustEmbedUnimplementedSkipperChatServiceServer()
}

func RegisterSkipperChatServiceServer(s grpc.ServiceRegistrar, srv SkipperChatServiceServer) {
	// If the following call panics, it indicates UnimplementedSkipperChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkipperChatService_ServiceDesc, srv)
}

func _SkipperChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SkipperChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkipperChatServiceServer).Chat(m, &grpc.GenericServerStream[SkipperChatRequest, SkipperChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SkipperChatService_ChatServer = grpc.ServerStreamingServer[SkipperChatEvent]

func _SkipperChatService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkipperConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipperChatServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipperChatService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipperChatServiceServer).ListConversations(ctx, req.(*ListSkipperConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkipperChatService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkipperConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipperChatServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipperChatService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipperChatServiceServer).GetConversation(ctx, req.(*GetSkipperConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkipperChatService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkipperConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipperChatServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipperChatService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipperChatServiceServer).DeleteConversation(ctx, req.(*DeleteSkipperConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkipperChatService_UpdateConversationTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkipperConversationTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkipperChatServiceServer).UpdateConversationTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkipperChatService_UpdateConversationTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkipperChatServiceServer).UpdateConversationTitle(ctx, req.(*UpdateSkipperConversationTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkipperChatService_ServiceDesc is the grpc.ServiceDesc for SkipperChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkipperChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skipper.SkipperChatService",
	HandlerType: (*SkipperChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConversations",
			Handler:    _SkipperChatService_ListConversations_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _SkipperChatService_GetConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _SkipperChatService_DeleteConversation_Handler,
		},
		{
			MethodName: "UpdateConversationTitle",
			Handler:    _SkipperChatService_UpdateConversationTitle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _SkipperChatService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "skipper.proto",
}
