-- Listmonk self-hosted newsletter service
-- Database and user are created by the provisioner (pgCreateApplicationUser).
-- Listmonk handles its own table migrations upon startup; no schema DDL here.
