---
- name: Caddy | install
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: Caddy | configure
  ansible.builtin.import_tasks: configure.yml
  tags: [configure]

- name: Caddy | flush handlers before service
  ansible.builtin.meta: flush_handlers
  tags: [configure, service]

- name: Caddy | service
  ansible.builtin.import_tasks: service.yml
  tags: [service]

- name: Caddy | flush handlers before validate
  ansible.builtin.meta: flush_handlers
  tags: [service, validate]

- name: Caddy | validate
  ansible.builtin.import_tasks: validate.yml
  tags: [validate]

- name: Caddy | restart
  ansible.builtin.import_tasks: restart.yml
  tags: [restart, never]

- name: Caddy | cleanup
  ansible.builtin.import_tasks: cleanup.yml
  tags: [cleanup, never]
