---
- name: Stop and disable {{ go_service_systemd_name }}
  ansible.builtin.systemd:
    name: "{{ go_service_systemd_name }}"
    state: stopped
    enabled: false
  failed_when: false

- name: Remove {{ go_service_systemd_name }} unit file
  ansible.builtin.file:
    path: "{{ go_service_unit_path }}"
    state: absent

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false
