---
- name: Render env file
  ansible.builtin.copy:
    dest: "{{ go_service_env_file }}"
    content: |
      {% for k, v in (go_service_env | dictsort) %}
      {{ k }}={{ (v | string | replace('\r', '') | replace('\n', '\\n')) | quote }}
      {% endfor %}
    owner: "{{ omit if ansible_check_mode else go_service_user }}"
    group: "{{ omit if ansible_check_mode else go_service_group }}"
    mode: "0600"
  no_log: true
  notify: go_service restart

- name: Render systemd unit
  ansible.builtin.template:
    src: service.j2
    dest: "{{ go_service_unit_path }}"
    owner: root
    group: root
    mode: "0644"
  register: go_service_unit_changed
  notify:
    - go_service restart
