---
- name: Restart {{ go_service_systemd_name }}
  ansible.builtin.systemd:
    name: "{{ go_service_systemd_name }}"
    state: restarted

- name: Wait for port after restart {{ go_service_name }}
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: "{{ go_service_port }}"
    timeout: 60
  when: go_service_port | int > 0
