---
role_name_check: 1
prerun: false
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper-instance
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    dns_servers:
      - "1.1.1.1"
      - "8.8.8.8"
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  playbooks:
    prepare: ../../../../molecule/prepare-apt.yml
  inventory:
    group_vars:
      all:
        zookeeper_version: "3.9.5"
        zookeeper_artifact_url: >-
          {{ lookup('env', 'ZOOKEEPER_ARTIFACT_URL') |
             default('https://downloads.apache.org/zookeeper/zookeeper-3.9.5/apache-zookeeper-3.9.5-bin.tar.gz', true) }}
        zookeeper_artifact_checksum: >-
          {{ lookup('env', 'ZOOKEEPER_ARTIFACT_CHECKSUM') |
             default(
               'sha512:baa1c21dda4d57238fca751e4fa2bbf1daff9a28612b125e497' ~
               'dccd5c188ee6449e2f79947e474c2dd4d19992789d4d36b27b1ba2feb80c2b0c45e7df0e22aa8',
               true) }}
        zookeeper_node_id: 1
        zookeeper_ensemble: []
verifier:
  name: ansible
